# -*- coding: utf-8 -*-
"""Copy of Datvis_UAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rurABff5gHkLCSNw_8WkUjyDBuToWlN_

1. LOAD DATA
"""

import pandas as pd

# 1. LOAD DATASET (FIX SEPARATOR)
file_name = 'dataset_nutrisi_text_300.csv'
df = pd.read_csv(file_name)  # ← DEFAULT = koma

# 2. CEK NAMA KOLOM
print(df.columns)

# 3. BERSIHKAN NAMA KOLOM
df.columns = df.columns.str.strip()

# 4. PERBAIKI FORMAT DESIMAL
numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']

for col in numeric_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(',', '.', regex=False)
    )
    df[col] = pd.to_numeric(df[col], errors='coerce')
(df.head())

"""2. PREPROCESSING NUMERIK"""

numerical_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
df_numeric = df[numerical_cols].copy()

missing_check = pd.DataFrame({
    'Kolom': numerical_cols,
    'Jumlah Missing': [df[col].isnull().sum() for col in numerical_cols]
})

missing_check

df_numeric_imputed = df_numeric.copy()

for col in numerical_cols:
    median_val = df_numeric_imputed[col].median()
    df_numeric_imputed[col] = df_numeric_imputed[col].fillna(median_val)

missing_check_after = pd.DataFrame({
    'Kolom': numerical_cols,
    'Jumlah Missing Setelah Imputasi': [
        df_numeric_imputed[col].isnull().sum() for col in numerical_cols
    ]
})

missing_check_after

outlier_summary = []

for col in numerical_cols:
    Q1 = df_numeric_imputed[col].quantile(0.25)
    Q3 = df_numeric_imputed[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    jumlah_outlier = df_numeric_imputed[
        (df_numeric_imputed[col] < lower) |
        (df_numeric_imputed[col] > upper)
    ].shape[0]

    outlier_summary.append([col, lower, upper, jumlah_outlier])

outlier_df = pd.DataFrame(
    outlier_summary,
    columns=['Kolom', 'Batas_Bawah', 'Batas_Atas', 'Jumlah_Outlier']
)

outlier_df

df_numeric_capped = df_numeric_imputed.copy()

for col in numerical_cols:
    Q1 = df_numeric_capped[col].quantile(0.25)
    Q3 = df_numeric_capped[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_numeric_capped[col] = df_numeric_capped[col].clip(lower, upper)

import pandas as pd
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_array = scaler.fit_transform(df_numeric_capped)

df_numeric_scaled = pd.DataFrame(
    scaled_array,
    columns=[f'{col}_scaled' for col in numerical_cols],
    index=df_numeric_capped.index  # biar index rapi
)

(df_numeric_scaled.head())

df_preprocessed_numeric = pd.concat(
    [df[['Food_Name', 'Label_Kesehatan']],
     df_numeric_capped,
     df_numeric_scaled],
    axis=1
)

df_preprocessed_numeric.head()

"""3. PREPROCESSING TEKS"""

text_col = 'Food_Text'
label_col = 'Label_Kesehatan'

df_text = df[[text_col, label_col]].copy()
df_text.head()

df_text['text_lower'] = df_text[text_col].str.lower()
df_text[['Food_Text', 'text_lower']].head()

df_text['tokens'] = df_text['text_lower'].str.split()
df_text[['text_lower', 'tokens']].head()

custom_stopwords = {'and', 'or', 'with', 'of', 'the'}

df_text['tokens_clean'] = df_text['tokens'].apply(
    lambda x: [word for word in x if word not in custom_stopwords]
)

df_text[['tokens', 'tokens_clean']].head()

df_text['clean_text'] = df_text['tokens_clean'].apply(lambda x: ' '.join(x))
df_text[['text_lower', 'clean_text']].head()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df_text['clean_text'])

tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df.head()

from sklearn.feature_selection import mutual_info_classif

y = df_text[label_col].map({'Sehat': 1, 'Tidak Sehat': 0})

mi_scores = mutual_info_classif(tfidf_df, y, random_state=42)

mi_df = pd.DataFrame({
    'Fitur': tfidf_df.columns,
    'Information_Gain': mi_scores
}).sort_values(by='Information_Gain', ascending=False)

mi_df.head(10)

import numpy as np

corr_matrix = tfidf_df.corr().abs()

upper_triangle = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

high_corr_features = [
    column for column in upper_triangle.columns
    if any(upper_triangle[column] > 0.9)
]

tfidf_cbfs = tfidf_df.drop(columns=high_corr_features)

tfidf_cbfs.head()

df_text_final = pd.concat(
    [df_text[[label_col, 'clean_text']], tfidf_cbfs],
    axis=1
)

df_text_final.head()

df_numeric_final = df_numeric_capped.copy()
df_numeric_final['Label_Kesehatan'] = df['Label_Kesehatan'].values

df_text_features = tfidf_cbfs.copy()

df_integrated = pd.concat(
    [df_numeric_final.reset_index(drop=True),
     df_text_features.reset_index(drop=True)],
    axis=1
)

df_integrated.head()

import matplotlib.pyplot as plt

# Rata-rata Kandungan Protein pada Berbagai Jenis Makanan (Bar Chart)
plt.figure(figsize=(8,5))
avg_protein = df.groupby("Food_Name")["Protein_g"].mean()

avg_protein.plot(kind="bar")
plt.title("Rata-rata Kandungan Protein pada Berbagai Jenis Makanan")
plt.xlabel("Kategori Makanan")
plt.ylabel("Protein (gram)")
plt.xticks(rotation=0)
plt.show()

import matplotlib.pyplot as plt

# RATA-RATA GULA & NATRIUM BERDASARKAN LABEL KESEHATAN
avg_sugar_sodium = (
    df.groupby("Label_Kesehatan")[["Sugar_g", "Sodium_mg"]]
    .mean()
)

avg_sugar_sodium.plot(kind="bar", figsize=(8,5))
plt.title("Perbandingan Rata-rata Gula dan Natrium")
plt.xlabel("Label Kesehatan")
plt.ylabel("Rata-rata Kandungan")
plt.xticks(rotation=0)
plt.legend(["Gula (g)", "Natrium (mg)"])
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# PERBANDINGAN KADAR GULA & NATRIUM (GROUPED BAR)
avg_sugar_sodium = (
    df.groupby("Label_Kesehatan")[["Sugar_g", "Sodium_mg"]]
    .mean()
)

avg_sugar_sodium.plot(kind="bar", figsize=(8,5))
plt.title("Perbandingan Rata-rata Gula dan Natrium")
plt.xlabel("Label Kesehatan")
plt.ylabel("Rata-rata Kandungan")
plt.xticks(rotation=0)
plt.legend(["Gula (g)", "Natrium (mg)"])
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# HUBUNGAN PROTEIN & LEMAK (SCATTER PLOT)
plt.figure(figsize=(7,5))
sns.scatterplot(
    data=df,
    x="Protein_g",
    y="Fat_g",
    hue="Label_Kesehatan"
)

plt.title("Hubungan Kandungan Protein dan Lemak")
plt.xlabel("Protein (gram)")
plt.ylabel("Lemak (gram)")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt


# DISTRIBUSI ENERGI (KALORI) – HISTOGRAM
plt.figure(figsize=(7,5))
plt.hist(df["Energy_kcal"], bins=20)

plt.title("Distribusi Energi (Kalori) pada Dataset Makanan")
plt.xlabel("Energi (kcal)")
plt.ylabel("Frekuensi")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from wordcloud import WordCloud


# WORD CLOUD MAKANAN SEHAT & TIDAK SEHAT

text_sehat = " ".join(
    df[df["Label_Kesehatan"] == "Sehat"]["Food_Text"].astype(str)
)

text_tidak = " ".join(
    df[df["Label_Kesehatan"] == "Tidak Sehat"]["Food_Text"].astype(str)
)

# WordCloud Makanan Sehat
wc_sehat = WordCloud(
    width=800,
    height=400,
    background_color="white"
).generate(text_sehat)

plt.figure(figsize=(10,4))
plt.imshow(wc_sehat)
plt.axis("off")
plt.title("Word Cloud Makanan Sehat")
plt.tight_layout()
plt.show()

# WordCloud Makanan Tidak Sehat
wc_tidak = WordCloud(
    width=800,
    height=400,
    background_color="white"
).generate(text_tidak)

plt.figure(figsize=(10,4))
plt.imshow(wc_tidak)
plt.axis("off")
plt.title("Word Cloud Makanan Tidak Sehat")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif

# FITUR TEKS PALING BERPENGARUH (INFORMATION GAIN)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(
    max_features=20,
    stop_words="english"
)

X = vectorizer.fit_transform(df["Food_Text"].astype(str))

# Encoding label
y = df["Label_Kesehatan"].map({
    "Sehat": 0,
    "Tidak Sehat": 1
})

# Hitung Information Gain
ig = mutual_info_classif(X, y)

# Ambil nama fitur
features = vectorizer.get_feature_names_out()

# Buat DataFrame hasil
ig_df = (
    pd.DataFrame({
        "Fitur": features,
        "Information Gain": ig
    })
    .sort_values(by="Information Gain", ascending=False)
)

# Visualisasi
plt.figure(figsize=(8,5))
sns.barplot(
    data=ig_df,
    x="Information Gain",
    y="Fitur"
)
plt.title("Fitur Teks Paling Berpengaruh Berdasarkan Information Gain")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# KORELASI ANTAR KANDUNGAN GIZI (HEATMAP)
nutrisi = df[
    [
        "Protein_g",
        "Fat_g",
        "Sugar_g",
        "Sodium_mg",
        "Energy_kcal"
    ]
]

corr = nutrisi.corr()

plt.figure(figsize=(8,6))
sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Korelasi Antar Kandungan Gizi Makanan")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================
# INTEGRASI ANALISIS GIZI & TEKS (MULTI-VISUALISASI)
# =====================================================

fig, axes = plt.subplots(1, 2, figsize=(14,5))

# -----------------------------------------------------
# Scatter Plot: Protein vs Lemak
# -----------------------------------------------------
sns.scatterplot(
    data=df,
    x="Protein_g",
    y="Fat_g",
    hue="Label_Kesehatan",
    ax=axes[0]
)
axes[0].set_title("Protein vs Lemak")
axes[0].set_xlabel("Protein (gram)")
axes[0].set_ylabel("Lemak (gram)")

# Bar Plot: Top 10 Fitur Teks (Information Gain)
sns.barplot(
    data=ig_df.head(10),
    x="Information Gain",
    y="Fitur",
    ax=axes[1]
)
axes[1].set_title("Top 10 Fitur Teks Berdasarkan Information Gain")

plt.tight_layout()
plt.show()