# -*- coding: utf-8 -*-
"""Copy of Datvis_UAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EUf4ipYBvZ9SZ1I97EvTXcEbjLk62f_8
"""

# ===============================
# IMPORT LIBRARY
# ===============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from collections import Counter
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# ===============================
# LOAD DATA
# ===============================
# Pastikan nilai_gizi.csv sudah di-upload ke Colab
df = pd.read_csv("nilai_gizi.csv", sep=";")
df.columns = df.columns.str.strip()

# ===============================
# PREPROCESSING NUMERIK
# ===============================
numeric_cols = [
    'Energy_kcal', 'Protein_g', 'Fat_g',
    'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
]

for col in numeric_cols:
    df[col] = (
        df[col].astype(str)
        .str.replace(',', '.', regex=False)
    )
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Imputasi median
for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

# Capping outlier (IQR)
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df[col] = df[col].clip(Q1 - 1.5 * IQR, Q3 + 1.5 * IQR)

# Scaling
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df[numeric_cols])
df_scaled = pd.DataFrame(
    df_scaled,
    columns=[f"{c}_scaled" for c in numeric_cols]
)

df_final = pd.concat([df, df_scaled], axis=1)

# ===============================
# 1. OVERVIEW DATA
# ===============================
print("===== OVERVIEW DATA =====")
display(df.head())
display(df.describe())

plt.figure(figsize=(6,4))
df['Label_Kesehatan'].value_counts().plot(
    kind='bar', color=['green','orange','red']
)
plt.title("Distribusi Label Kesehatan")
plt.xlabel("Label")
plt.ylabel("Jumlah")
plt.show()

# ===============================
# 2. ANALISIS NUMERIK
# ===============================
avg_nutrisi = df.groupby("Label_Kesehatan")[
    ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
].mean()

avg_nutrisi.plot(kind='bar', figsize=(10,6))
plt.title("Rata-rata Kandungan Nutrisi per Label")
plt.ylabel("Rata-rata")
plt.xticks(rotation=0)
plt.show()

# ===============================
# 3. ANALISIS TOKEN TEKS (OPS 2)
# ===============================
print("===== ANALISIS TOKEN TEKS =====")

# Gabungkan semua teks
text_data = " ".join(df['Food_Text'].dropna().astype(str)).lower()

# Tokenisasi (aman untuk bahasa Indonesia)
tokens = re.findall(r'\b\w+\b', text_data)

# Stopwords sederhana
stopwords = {
    'dan','yang','dengan','untuk','atau','tanpa',
    'mengandung','tinggi','rendah'
}

tokens = [
    t for t in tokens
    if t not in stopwords
    and not t.isdigit()
    and len(t) > 2
]

print("Jumlah token:", len(tokens))
print("Contoh token:", tokens[:15])

# Hitung frekuensi
token_counts = Counter(tokens).most_common(15)
token_df = pd.DataFrame(token_counts, columns=['Token','Frekuensi'])

display(token_df)

# Visualisasi token
plt.figure(figsize=(8,5))
plt.barh(token_df['Token'], token_df['Frekuensi'])
plt.gca().invert_yaxis()
plt.title("Top 15 Token Paling Sering Muncul")
plt.xlabel("Frekuensi")
plt.show()

# ===============================
# 4. TOP 10 MAKANAN
# ===============================
top_protein = df.sort_values("Protein_g", ascending=False).head(10)

plt.figure(figsize=(8,5))
plt.barh(top_protein['Food_Name'], top_protein['Protein_g'])
plt.gca().invert_yaxis()
plt.title("Top 10 Makanan dengan Protein Tertinggi")
plt.xlabel("Protein (g)")
plt.show()

display(top_protein[['Food_Name','Protein_g','Label_Kesehatan']])

# ===============================
# 5. ANALISIS MULTI-DIMENSI
# ===============================
plt.figure(figsize=(8,6))
colors = {'Sehat':'green','Cukup Sehat':'orange','Kurang Sehat':'red'}

for label, color in colors.items():
    subset = df[df['Label_Kesehatan'] == label]
    plt.scatter(
        subset['Protein_g'],
        subset['Fat_g'],
        label=label,
        color=color,
        alpha=0.7
    )

plt.xlabel("Protein (g)")
plt.ylabel("Lemak (g)")
plt.title("Scatter Plot Protein vs Lemak")
plt.legend()
plt.grid(alpha=0.3)
plt.show()