# -*- coding: utf-8 -*-
"""Datvis_UAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RvKp5BkbRmUROJHceP5cjDs2gUKa40DT
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
import warnings
warnings.filterwarnings('ignore')

# Konfigurasi halaman
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    page_icon="🍎",
    layout="wide"
)

# Title dashboard
st.title("🍎 Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# Fungsi untuk load dan preprocessing data
@st.cache_data
def load_and_preprocess_data():
    # Load data
    file_name = 'nilai_gizi.csv'
    df = pd.read_csv(file_name, sep=';')

    # Bersihkan nama kolom
    df.columns = df.columns.str.strip()

    # Perbaiki format desimal
    numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']

    for col in numeric_cols:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace(',', '.', regex=False)
        )
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Preprocessing numerik
    numerical_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
    df_numeric = df[numerical_cols].copy()

    # Imputasi missing values dengan median
    for col in numerical_cols:
        median_val = df_numeric[col].median()
        df_numeric[col] = df_numeric[col].fillna(median_val)

    # Capping outliers
    df_numeric_capped = df_numeric.copy()
    for col in numerical_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        df_numeric_capped[col] = df_numeric_capped[col].clip(lower, upper)

    # Scaling
    scaler = StandardScaler()
    scaled_array = scaler.fit_transform(df_numeric_capped)
    df_numeric_scaled = pd.DataFrame(
        scaled_array,
        columns=[f'{col}_scaled' for col in numerical_cols],
        index=df_numeric_capped.index
    )

    # Gabungkan data
    df_preprocessed_numeric = pd.concat(
        [df[['Food_Name', 'Label_Kesehatan']],
         df_numeric_capped,
         df_numeric_scaled],
        axis=1
    )

    return df, df_preprocessed_numeric, df_numeric_capped

# Load data
df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# Sidebar untuk navigasi
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    ["📊 Overview Data",
     "📈 Analisis Numerik",
     "📝 Analisis Teks",
     "🏆 Top 10 Makanan",
     "🔍 Analisis Multi-Dimensi"]
)

# 1. Halaman Overview Data
if page == "📊 Overview Data":
    st.header("📊 Overview Data")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Data Sample")
        st.dataframe(df.head(10), use_container_width=True)

        st.subheader("Statistik Deskriptif")
        st.dataframe(df.describe(), use_container_width=True)

    with col2:
        st.subheader("Distribusi Label Kesehatan")
        fig, ax = plt.subplots(figsize=(6, 4))
        df['Label_Kesehatan'].value_counts().plot(kind='bar', ax=ax, color=['green', 'orange', 'red'])
        ax.set_title("Distribusi Label Kesehatan")
        ax.set_xlabel("Label Kesehatan")
        ax.set_ylabel("Jumlah")
        st.pyplot(fig)

        st.subheader("Informasi Dataset")
        st.metric("Total Data", f"{len(df)} rows")
        st.metric("Total Kolom", f"{len(df.columns)} columns")

        # Tampilkan info missing values
        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum().values,
            'Persentase Missing': (df.isnull().sum() / len(df) * 100).round(2).values
        })
        st.dataframe(missing_data[missing_data['Missing Values'] > 0], use_container_width=True)

# 2. Halaman Analisis Numerik
elif page == "📈 Analisis Numerik":
    st.header("📈 Analisis Numerik")

    # Tab untuk analisis numerik
    tab1, tab2, tab3, tab4 = st.tabs([
        "📊 Distribusi",
        "📈 Perbandingan",
        "🔗 Korelasi",
        "📉 Histogram"
    ])

    with tab1:
        st.subheader("Rata-rata Kandungan Nutrisi per Label Kesehatan")

        # Hitung rata-rata
        avg_nutrisi = df_preprocessed_numeric.groupby('Label_Kesehatan')[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

        fig, axes = plt.subplots(2, 2, figsize=(12, 8))
        nutrients = [('Protein_g', 'Protein (g)'), ('Fat_g', 'Lemak (g)'),
                    ('Sugar_g', 'Gula (g)'), ('Sodium_mg', 'Natrium (mg)')]

        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for idx, (col, title) in enumerate(nutrients):
            ax = axes[idx//2, idx%2]
            values = avg_nutrisi[col]
            bars = ax.bar(values.index, values.values,
                         color=[colors[label] for label in values.index])
            ax.set_title(f'Rata-rata {title}')
            ax.set_ylabel(title)
            ax.tick_params(axis='x', rotation=45)

            # Tambahkan nilai di atas bar
            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
                       f'{height:.1f}', ha='center', va='bottom')

        plt.tight_layout()
        st.pyplot(fig)

    with tab2:
        st.subheader("Perbandingan Gula dan Natrium per Label Kesehatan")

        # Agregasi data
        df_food = (
            df_preprocessed_numeric
            .groupby(["Food_Name", "Label_Kesehatan"], as_index=False)[
                ["Sugar_g", "Sodium_mg"]
            ]
            .mean()
        )

        avg_sugar_sodium = (
            df_food
            .groupby("Label_Kesehatan")[["Sugar_g", "Sodium_mg"]]
            .mean()
        )

        fig, ax = plt.subplots(figsize=(10, 6))
        avg_sugar_sodium.plot(kind="bar", ax=ax)
        ax.set_title("Perbandingan Rata-rata Gula dan Natrium Berdasarkan Label Kesehatan")
        ax.set_xlabel("Label Kesehatan")
        ax.set_ylabel("Rata-rata Kandungan")
        ax.legend(["Gula (g)", "Natrium (mg)"])
        st.pyplot(fig)

    with tab3:
        st.subheader("Korelasi Antar Kandungan Gizi")

        # Hitung korelasi
        nutrisi_mean = (
            df_preprocessed_numeric
            .groupby('Food_Name', as_index=False)[
                ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
            ]
            .mean()
        )

        corr = nutrisi_mean[
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
        ].corr()

        fig, ax = plt.subplots(figsize=(10, 8))
        sns.heatmap(
            corr,
            annot=True,
            cmap="coolwarm",
            fmt=".2f",
            square=True,
            ax=ax
        )
        ax.set_title("Korelasi Antar Kandungan Gizi Makanan")
        st.pyplot(fig)

        # Insight dari korelasi
        st.markdown("### Insight Korelasi")
        st.markdown("""
        - **Energi dan Lemak**: Biasanya memiliki korelasi positif tinggi
        - **Protein dan Lemak**: Dapat berkorelasi positif atau negatif tergantung jenis makanan
        - **Gula dan Karbohidrat**: Biasanya berkorelasi positif
        """)

    with tab4:
        st.subheader("Distribusi Kandungan Nutrisi")

        col1, col2 = st.columns(2)

        with col1:
            # Distribusi Energi
            fig, ax = plt.subplots(figsize=(8, 5))
            ax.hist(df_numeric_capped["Energy_kcal"], bins=20, color='skyblue', edgecolor='black')
            ax.set_title("Distribusi Energi (Kalori) Makanan")
            ax.set_xlabel("Energi (kcal)")
            ax.set_ylabel("Frekuensi")
            st.pyplot(fig)

        with col2:
            # Distribusi Protein
            fig, ax = plt.subplots(figsize=(8, 5))
            ax.hist(df_numeric_capped["Protein_g"], bins=20, color='lightgreen', edgecolor='black')
            ax.set_title("Distribusi Protein")
            ax.set_xlabel("Protein (g)")
            ax.set_ylabel("Frekuensi")
            st.pyplot(fig)

# 3. Halaman Analisis Teks
elif page == "📝 Analisis Teks":
    st.header("📝 Analisis Teks")

    # Preprocessing teks untuk word cloud
    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    # Tab untuk analisis teks
    tab1, tab2 = st.tabs(["☁️ Word Cloud", "📊 Information Gain"])

    with tab1:
        st.subheader("Word Cloud Berdasarkan Label Kesehatan")

        # Pilih label untuk ditampilkan
        label_option = st.selectbox(
            "Pilih Label Kesehatan:",
            ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat']
        )

        if label_option == 'Semua':
            text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
            title = "Word Cloud Semua Makanan"
        else:
            text_data = " ".join(
                df_text[df_text["Label_Kesehatan"] == label_option]["Food_Text"]
                .dropna()
                .astype(str)
            )
            title = f"Word Cloud Makanan {label_option}"

        if len(text_data.strip()) > 0:
            fig, ax = plt.subplots(figsize=(12, 6))
            wc = WordCloud(
                width=800,
                height=400,
                background_color="white",
                colormap="viridis",
                max_words=100
            ).generate(text_data)

            ax.imshow(wc)
            ax.axis("off")
            ax.set_title(title, fontsize=16, fontweight='bold')
            st.pyplot(fig)
        else:
            st.warning("Tidak ada data teks untuk label yang dipilih.")

    with tab2:
        st.subheader("Fitur Teks Paling Berpengaruh")

        # TF-IDF dan Information Gain
        with st.spinner("Menghitung Information Gain..."):
            vectorizer = TfidfVectorizer(max_features=30, stop_words="english")
            X = vectorizer.fit_transform(df["Food_Text"].astype(str))

            label_mapping = {
                "Kurang Sehat": 0,
                "Cukup Sehat": 1,
                "Sehat": 2
            }

            y = df["Label_Kesehatan"].map(label_mapping)
            valid_idx = y.notnull()
            X_valid = X[valid_idx.values]
            y_valid = y[valid_idx]

            ig = mutual_info_classif(X_valid, y_valid, random_state=42)
            features = vectorizer.get_feature_names_out()

            ig_df = (
                pd.DataFrame({
                    "Fitur": features,
                    "Information_Gain": ig
                })
                .sort_values(by="Information_Gain", ascending=False)
                .head(15)
            )

            # Plot
            fig, ax = plt.subplots(figsize=(10, 6))
            sns.barplot(data=ig_df, x="Information_Gain", y="Fitur", ax=ax, palette="viridis")
            ax.set_title("Top 15 Fitur Teks Berdasarkan Information Gain")
            ax.set_xlabel("Information Gain")
            ax.set_ylabel("Fitur Teks")
            st.pyplot(fig)

            # Tampilkan tabel
            st.dataframe(ig_df, use_container_width=True)

# 4. Halaman Top 10 Makanan
elif page == "🏆 Top 10 Makanan":
    st.header("🏆 Top 10 Makanan")

    # Pilih nutrisi untuk ditampilkan
    nutrient_options = {
        "Protein (g)": "Protein_g",
        "Lemak (g)": "Fat_g",
        "Gula (g)": "Sugar_g",
        "Natrium (mg)": "Sodium_mg",
        "Energi (kcal)": "Energy_kcal",
        "Karbohidrat (g)": "Carbohydrate_g"
    }

    selected_nutrient = st.selectbox(
        "Pilih Kandungan Nutrisi:",
        list(nutrient_options.keys())
    )

    col_name = nutrient_options[selected_nutrient]

    # Pilih jumlah data
    n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 20, 10)

    # Ambil top makanan
    top_foods = (
        df.sort_values(col_name, ascending=False)
        .head(n_top)
    )

    # Plot
    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
    ax.set_xlabel(selected_nutrient)
    ax.set_title(f"Top {n_top} Makanan dengan Kandungan {selected_nutrient} Tertinggi")
    ax.invert_yaxis()

    # Warna berdasarkan label kesehatan
    for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
        if label == "Sehat":
            bar.set_color('green')
        elif label == "Cukup Sehat":
            bar.set_color('orange')
        else:
            bar.set_color('red')

    # Tambahkan legend
    import matplotlib.patches as mpatches
    healthy_patch = mpatches.Patch(color='green', label='Sehat')
    moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
    unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
    ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch])

    st.pyplot(fig)

    # Tampilkan data dalam tabel
    st.subheader("Data Detail")
    display_cols = ['Food_Name', 'Label_Kesehatan', col_name, 'Food_Text']
    st.dataframe(top_foods[display_cols], use_container_width=True)

# 5. Halaman Analisis Multi-Dimensi
elif page == "🔍 Analisis Multi-Dimensi":
    st.header("🔍 Analisis Multi-Dimensi")

    st.subheader("Scatter Plot: Hubungan Protein vs Lemak")

    # Agregasi data
    df_food = (
        df_preprocessed_numeric
        .groupby(["Food_Name", "Label_Kesehatan"], as_index=False)[
            ["Protein_g", "Fat_g"]
        ]
        .mean()
    )

    fig, ax = plt.subplots(figsize=(10, 6))
    scatter = ax.scatter(
        data=df_food,
        x="Protein_g",
        y="Fat_g",
        c=df_food["Label_Kesehatan"].map({"Sehat": "green", "Cukup Sehat": "orange", "Kurang Sehat": "red"}),
        s=80,
        alpha=0.7
    )

    ax.set_title("Hubungan Kandungan Protein dan Lemak")
    ax.set_xlabel("Protein (gram)")
    ax.set_ylabel("Lemak (gram)")

    # Tambahkan legend
    import matplotlib.patches as mpatches
    healthy_patch = mpatches.Patch(color='green', label='Sehat')
    moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
    unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
    ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch])

    st.pyplot(fig)

    # Analisis per kategori
    st.subheader("Profil Nutrisi per Kategori Kesehatan")

    categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']
    nutrients_for_radar = ['Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg', 'Energy_kcal']
    nutrient_labels = ['Protein', 'Lemak', 'Gula', 'Karbo', 'Natrium', 'Energi']

    # Hitung rata-rata dan normalisasi
    category_profiles = {}

    for category in categories:
        subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
        means = []
        for nutrient in nutrients_for_radar:
            means.append(subset[nutrient].mean())

        # Normalisasi min-max
        means_array = np.array(means)
        if means_array.max() - means_array.min() > 0:
            normalized = (means_array - means_array.min()) / (means_array.max() - means_array.min())
        else:
            normalized = np.zeros_like(means_array)

        category_profiles[category] = normalized

    # Buat radar chart
    angles = np.linspace(0, 2*np.pi, len(nutrients_for_radar), endpoint=False).tolist()
    angles += angles[:1]  # Tutup lingkaran

    fig, ax = plt.subplots(figsize=(10, 8), subplot_kw=dict(projection='polar'))

    for category, color in zip(categories, ['green', 'orange', 'red']):
        values = category_profiles[category].tolist()
        values += values[:1]  # Tutup lingkaran

        ax.plot(angles, values, 'o-', linewidth=2, label=category, color=color)
        ax.fill(angles, values, alpha=0.25, color=color)

    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(nutrient_labels)
    ax.set_ylim(0, 1)
    ax.set_title('PROFIL NUTRISI NORMALISASI\n(Perbandingan Relatif Antar Kategori)',
                fontsize=14, fontweight='bold', pad=20)
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.0))
    ax.grid(True)

    st.pyplot(fig)

    # Insight pola
    st.subheader("Insight Pola Nutrisi")

    for category in categories:
        profile = category_profiles[category]
        max_idx = np.argmax(profile)
        min_idx = np.argmin(profile)

        with st.expander(f"**{category.upper()}**"):
            col_a, col_b = st.columns(2)
            with col_a:
                st.metric("Nutrisi Dominan", nutrient_labels[max_idx],
                         f"{profile[max_idx]:.2f}")
            with col_b:
                st.metric("Nutrisi Terendah", nutrient_labels[min_idx],
                         f"{profile[min_idx]:.2f}")

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv •
    Dibuat dengan Streamlit
    </div>
    """,
    unsafe_allow_html=True
)