# -*- coding: utf-8 -*-
"""Datvis Final Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oo_fHrKdxc8K-HtHlxhMiz3xM69v1msn
"""

# -*- coding: utf-8 -*-

# =========================
# IMPORT
# =========================
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN (WAJIB DI SINI - PERUBAHAN PERTAMA)
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="centered",  # PERUBAHAN PENTING: dari "wide" jadi "centered"
    initial_sidebar_state="expanded"
)

# =========================
# GLOBAL VISUAL CONFIG - DIPERBAIKI
# =========================
VIS_SCALE = 0.6  # Scale untuk semua visualisasi

# Konfigurasi Matplotlib global
mpl.rcParams.update({
    "figure.figsize": (6, 3),  # UKURAN FIXED, tidak pakai multiplier
    "figure.dpi": 100,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "font.size": 10,
    "figure.autolayout": True,  # Untuk tight layout otomatis
})

# Set style Seaborn
sns.set_style("whitegrid")
sns.set_context("notebook", font_scale=VIS_SCALE)

# =========================
# FUNGSI BANTU UNTUK VISUALISASI YANG KONSISTEN
# =========================
def create_small_figure(width=6, height=3):
    """Membuat figure dengan ukuran terkontrol"""
    return plt.subplots(figsize=(width * VIS_SCALE, height * VIS_SCALE))

def display_figure(fig, use_container=False):
    """Menampilkan figure dengan kontrol width"""
    st.pyplot(fig, use_container_width=use_container)

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan', 'Food_Text']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped


df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("📊 Navigasi Dashboard")
page = st.sidebar.radio(
    "Pilih Halaman Analisis:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi",
        "Word Cloud Protein",
        "Scatter Plot"
    ]
)

# =========================
# 1. OVERVIEW DATA - DENGAN TAB NAVIGASI
# =========================
if page == "Overview Data":
    st.header("📊 Overview Dataset Nilai Gizi")

    # Tab navigation untuk Overview Data
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "📈 Metrik Utama",
        "📋 Data Sample",
        "📊 Distribusi",
        "🔍 Missing Values",
        "ℹ️ Informasi Dataset"
    ])

    with tab1:
        st.subheader("Metrik Utama Dataset")

        # Container untuk metrik ringkas dalam grid
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            total_data = len(df)
            st.metric("Total Data", f"{total_data:,}",
                     help="Jumlah total baris data dalam dataset")

        with col2:
            total_cols = len(df.columns)
            st.metric("Total Kolom", total_cols,
                     help="Jumlah total kolom/fitur dalam dataset")

        with col3:
            missing_total = df.isnull().sum().sum()
            st.metric("Missing Values", f"{missing_total:,}",
                     help="Total nilai yang hilang (missing) dalam dataset")

        with col4:
            sehat_count = len(df[df['Label_Kesehatan'] == 'Sehat'])
            st.metric("Makanan Sehat", f"{sehat_count:,}",
                     help="Jumlah makanan dengan label 'Sehat'")

        # Divider
        st.divider()

        # Statistik ringkas numerik dalam container kecil
        st.subheader("Statistik Numerik Ringkas")

        numeric_stats = df.select_dtypes(include=[np.number]).describe().T
        numeric_stats = numeric_stats[['mean', 'std', 'min', '50%', 'max']]
        numeric_stats.columns = ['Rata-rata', 'Std Dev', 'Minimum', 'Median', 'Maksimum']

        st.dataframe(
            numeric_stats.round(2),
            use_container_width=True,
            height=300,
            hide_index=True
        )

    with tab2:
        st.subheader("Data Sample Dataset")

        # Kontrol untuk jumlah data yang ditampilkan
        col_control1, col_control2 = st.columns(2)
        with col_control1:
            num_rows = st.slider("Jumlah baris:", 5, 20, 10)

        # Tampilkan data sample dengan container width
        display_cols = ['Food_Name', 'Label_Kesehatan', 'Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g']
        st.dataframe(
            df[display_cols].head(num_rows),
            use_container_width=True,
            height=350,
            hide_index=True
        )

    with tab3:
        st.subheader("Distribusi Data")

        # Distribusi Label Kesehatan - DIPERBAIKI UKURANNYA
        st.markdown("##### Distribusi Label Kesehatan")

        # Gunakan column layout untuk kontrol ukuran
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            counts = df['Label_Kesehatan'].value_counts()
            colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}
            bar_colors = [colors.get(label, 'gray') for label in counts.index]

            fig, ax = plt.subplots(figsize=(5, 3))  # UKURAN DIPERKECIL
            bars = ax.bar(counts.index, counts.values, color=bar_colors)
            ax.set_title("Distribusi Label Kesehatan", fontsize=11)
            ax.set_xlabel("Label Kesehatan", fontsize=10)
            ax.set_ylabel("Jumlah", fontsize=10)
            ax.grid(axis='y', alpha=0.3)

            # Tambah nilai di atas bar
            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height,
                       f'{int(height)}', ha='center', va='bottom', fontsize=9)

            # TAMPILKAN DENGAN KONTROL WIDTH
            st.pyplot(fig, use_container_width=False)

        st.divider()

        # Distribusi Kolom Numerik - DIPERBAIKI
        st.markdown("##### Distribusi Kolom Numerik")

        numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
        selected_numeric = st.selectbox(
            "Pilih kolom numerik:",
            numeric_cols,
            key="dist_numeric"
        )

        if selected_numeric in df.columns:
            # Gunakan column layout lagi
            left_col, center_col, right_col = st.columns([1, 3, 1])

            with center_col:
                fig2, ax2 = plt.subplots(figsize=(5, 2.5))  # UKURAN DIPERKECIL
                ax2.hist(df[selected_numeric].dropna(), bins=20, edgecolor='black', alpha=0.7)
                ax2.set_title(f"Distribusi {selected_numeric}", fontsize=11)
                ax2.set_xlabel(selected_numeric, fontsize=10)
                ax2.set_ylabel("Frekuensi", fontsize=10)
                ax2.grid(alpha=0.3)

                # Tambah statistik pada plot
                mean_val = df[selected_numeric].mean()
                median_val = df[selected_numeric].median()
                ax2.axvline(mean_val, color='red', linestyle='--', label=f'Mean: {mean_val:.1f}')
                ax2.axvline(median_val, color='green', linestyle='--', label=f'Median: {median_val:.1f}')
                ax2.legend(fontsize=9)

                st.pyplot(fig2, use_container_width=False)

    with tab4:
        st.subheader("Analisis Missing Values")

        # Hitung missing values
        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum(),
            'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
        }).sort_values('Missing Values', ascending=False)

        # Tampilkan hanya yang ada missing values
        missing_filtered = missing_data[missing_data['Missing Values'] > 0]

        if len(missing_filtered) > 0:
            st.warning(f"⚠️ Ditemukan {len(missing_filtered)} kolom dengan missing values")

            # Tampilkan tabel missing values
            st.dataframe(
                missing_filtered,
                use_container_width=True,
                height=200,
                hide_index=True
            )
        else:
            st.success("✅ Tidak ada missing values pada dataset!")

    with tab5:
        st.subheader("Informasi Dataset")

        # Informasi dasar dataset
        info_data = {
            'Attribute': ['Nama File', 'Total Baris', 'Total Kolom', 'Ukuran Memori'],
            'Value': ['nilai_gizi.csv', f"{len(df):,}", f"{len(df.columns)}",
                     f"{df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB"]
        }

        info_df = pd.DataFrame(info_data)
        st.dataframe(info_df, use_container_width=True, height=150, hide_index=True)

# =========================
# 2. ANALISIS NUMERIK - DIPERBAIKI UKURANNYA
# =========================
elif page == "Analisis Numerik":
    st.header("📈 Analisis Numerik")

    # Gunakan tabs untuk organisasi yang lebih baik
    tab1, tab2, tab3, tab4 = st.tabs([
        "📊 Distribusi",
        "⚖️ Perbandingan",
        "🔗 Korelasi",
        "📉 Histogram"
    ])

    with tab1:
        st.subheader("Distribusi Rata-rata Nutrisi per Kategori")

        # Gunakan container untuk kontrol layout
        with st.container():
            avg_nutrisi = df_preprocessed_numeric.groupby(
                'Label_Kesehatan'
            )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

            # Buat subplot dengan ukuran yang lebih kecil
            fig, axes = plt.subplots(2, 2, figsize=(8, 5))
            nutrients = [
                ('Protein_g', 'Protein (g)'),
                ('Fat_g', 'Lemak (g)'),
                ('Sugar_g', 'Gula (g)'),
                ('Sodium_mg', 'Natrium (mg)')
            ]

            colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

            for idx, (col, title) in enumerate(nutrients):
                ax = axes[idx // 2, idx % 2]
                values = avg_nutrisi[col]
                bars = ax.bar(
                    values.index,
                    values.values,
                    color=[colors[label] for label in values.index]
                )
                ax.set_title(f'Rata-rata {title}', fontsize=10)
                ax.tick_params(axis='x', rotation=45, labelsize=8)
                ax.tick_params(axis='y', labelsize=8)

                for bar in bars:
                    h = bar.get_height()
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        h,
                        f"{h:.1f}",
                        ha='center',
                        va='bottom',
                        fontsize=8
                    )
                ax.grid(axis='y', alpha=0.3)

            plt.tight_layout()
            # TAMPILKAN DENGAN KONTROL WIDTH
            st.pyplot(fig, use_container_width=False)

    with tab2:
        st.subheader("Perbandingan Gula & Natrium")

        with st.container():
            avg = df_preprocessed_numeric.groupby(
                'Label_Kesehatan'
            )[['Sugar_g', 'Sodium_mg']].mean()

            fig, ax = plt.subplots(figsize=(5, 3))
            avg.plot(kind='bar', ax=ax)
            ax.set_title("Perbandingan Gula & Natrium", fontsize=11)
            ax.set_xlabel("Label Kesehatan", fontsize=10)
            ax.set_ylabel("Rata-rata", fontsize=10)
            ax.tick_params(axis='x', rotation=0, labelsize=9)
            ax.tick_params(axis='y', labelsize=9)
            ax.legend(fontsize=9)
            ax.grid(axis='y', alpha=0.3)

            st.pyplot(fig, use_container_width=False)

    with tab3:
        st.subheader("Korelasi Antar Nutrisi")

        with st.container():
            corr = df_preprocessed_numeric[
                ['Energy_kcal', 'Protein_g', 'Fat_g',
                 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
            ].corr()

            fig, ax = plt.subplots(figsize=(5, 4))
            sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax, fmt='.2f',
                       annot_kws={"size": 8}, cbar_kws={"shrink": 0.8})
            ax.set_title("Heatmap Korelasi", fontsize=11)

            st.pyplot(fig, use_container_width=False)

    with tab4:
        st.subheader("Distribusi Energi")

        with st.container():
            fig, ax = plt.subplots(figsize=(5, 3))
            ax.hist(df_numeric_capped["Energy_kcal"], bins=20, edgecolor='black', alpha=0.7)
            ax.set_title("Distribusi Energy (kcal)", fontsize=11)
            ax.set_xlabel("Energy (kcal)", fontsize=10)
            ax.set_ylabel("Frekuensi", fontsize=10)
            ax.tick_params(labelsize=9)
            ax.grid(alpha=0.3)

            # Tambah garis mean dan median
            mean_val = df_numeric_capped["Energy_kcal"].mean()
            median_val = df_numeric_capped["Energy_kcal"].median()
            ax.axvline(mean_val, color='red', linestyle='--', label=f'Mean: {mean_val:.0f}')
            ax.axvline(median_val, color='green', linestyle='--', label=f'Median: {median_val:.0f}')
            ax.legend(fontsize=9)

            st.pyplot(fig, use_container_width=False)

# =========================
# 3. ANALISIS TEKS - DIPERBAIKI
# =========================
elif page == "Analisis Teks":
    st.header("📝 Analisis Teks")

    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    st.subheader("Word Cloud")

    label_option = st.selectbox(
        "Pilih Label:",
        ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat'],
        key="wordcloud_label"
    )

    if label_option == 'Semua':
        text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
    else:
        text_data = " ".join(
            df_text[df_text['Label_Kesehatan'] == label_option]
            ['Food_Text'].dropna().astype(str)
        )

    if text_data.strip():
        # Gunakan container untuk kontrol layout
        with st.container():
            left_col, center_col, right_col = st.columns([1, 2, 1])

            with center_col:
                fig, ax = plt.subplots(figsize=(5, 2.5))
                wc = WordCloud(
                    background_color="white",
                    width=400,
                    height=200,
                    max_words=50
                ).generate(text_data)
                ax.imshow(wc, interpolation='bilinear')
                ax.axis("off")
                ax.set_title(f"Word Cloud - {label_option}", fontsize=11)

                st.pyplot(fig, use_container_width=False)

                # Informasi tambahan
                word_count = len(text_data.split())
                st.caption(f"**Jumlah kata:** {word_count:,} kata")
    else:
        st.warning("Tidak ada data teks untuk ditampilkan")

# =========================
# 4. TOP 10 MAKANAN - DIPERBAIKI
# =========================
elif page == "Top 10 Makanan":
    st.header("🏆 Top 10 Makanan")

    nutrient_options = {
        "Protein (g)": "Protein_g",
        "Lemak (g)": "Fat_g",
        "Gula (g)": "Sugar_g",
        "Natrium (mg)": "Sodium_mg",
        "Energi (kcal)": "Energy_kcal",
        "Karbohidrat (g)": "Carbohydrate_g"
    }

    selected_nutrient = st.selectbox(
        "Pilih Kandungan Nutrisi:",
        list(nutrient_options.keys())
    )

    col_name = nutrient_options[selected_nutrient]

    n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 15, 10)

    top_foods = (
        df.sort_values(col_name, ascending=False)
        .head(n_top)
    )

    # Gunakan container untuk kontrol layout
    with st.container():
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            fig, ax = plt.subplots(figsize=(6, 4))
            bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
            ax.set_xlabel(selected_nutrient, fontsize=10)
            ax.set_title(f"Top {n_top} Makanan {selected_nutrient} Tertinggi", fontsize=11)
            ax.invert_yaxis()
            ax.tick_params(labelsize=9)
            ax.grid(axis='x', alpha=0.3)

            # Warna berdasarkan label kesehatan
            for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
                if label == "Sehat":
                    bar.set_color('green')
                elif label == "Cukup Sehat":
                    bar.set_color('orange')
                else:
                    bar.set_color('red')

            # Legend
            import matplotlib.patches as mpatches
            healthy_patch = mpatches.Patch(color='green', label='Sehat')
            moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
            unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
            ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch],
                      fontsize=9, loc='lower right')

            st.pyplot(fig, use_container_width=False)

    # Tabel detail
    st.subheader("Data Detail")
    display_cols = ['Food_Name', 'Label_Kesehatan', col_name]
    st.dataframe(top_foods[display_cols],
                 use_container_width=True,
                 height=300,
                 hide_index=True)

# =========================
# 5. ANALISIS MULTI-DIMENSI - DIPERBAIKI
# =========================
elif page == "Analisis Multi-Dimensi":
    st.header("🔍 Analisis Multi-Dimensi")

    categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']

    # Ringkasan per kategori
    for idx, category in enumerate(categories):
        with st.expander(f"**{category.upper()}**", expanded=(idx==0)):
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]

            col1, col2 = st.columns(2)

            with col1:
                st.metric("Jumlah Makanan", f"{len(subset)}")
                avg_protein = subset['Protein_g'].mean()
                st.metric("Rata-rata Protein", f"{avg_protein:.1f}g")

            with col2:
                avg_sugar = subset['Sugar_g'].mean()
                st.metric("Rata-rata Gula", f"{avg_sugar:.1f}g")
                avg_sodium = subset['Sodium_mg'].mean()
                st.metric("Rata-rata Natrium", f"{avg_sodium:.1f}mg")

    st.divider()

    # Perbandingan antar kategori
    st.subheader("Perbandingan Antar Kategori")

    selected_nutrient = st.selectbox(
        "Pilih Nutrisi untuk Perbandingan:",
        ['Protein', 'Gula', 'Lemak', 'Natrium', 'Energi'],
        key="compare_nutrient"
    )

    # Mapping
    nutrient_map = {
        'Protein': 'Protein_g',
        'Gula': 'Sugar_g',
        'Lemak': 'Fat_g',
        'Natrium': 'Sodium_mg',
        'Energi': 'Energy_kcal'
    }

    selected_col = nutrient_map[selected_nutrient]

    with st.container():
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            comparison_data = []
            for category in categories:
                subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
                avg_val = subset[selected_col].mean()
                comparison_data.append({
                    'Kategori': category,
                    'Rata_rata': avg_val
                })

            comparison_df = pd.DataFrame(comparison_data)

            # Plot perbandingan
            fig, ax = plt.subplots(figsize=(5, 3))
            colors = ['green', 'orange', 'red']
            bars = ax.bar(comparison_df['Kategori'], comparison_df['Rata_rata'], color=colors)

            ax.set_title(f'Perbandingan {selected_nutrient}', fontsize=11)
            ax.set_ylabel(f'Rata-rata {selected_nutrient}', fontsize=10)
            ax.tick_params(labelsize=9)
            ax.grid(axis='y', alpha=0.3)

            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
                       f'{height:.1f}', ha='center', va='bottom', fontsize=9)

            st.pyplot(fig, use_container_width=False)

# =========================
# 6. WORD CLOUD PROTEIN - DIPERBAIKI
# =========================
elif page == "Word Cloud Protein":
    st.header("☁️ Word Cloud Berdasarkan Level Protein")

    # Preprocessing teks
    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()
    df_text['tokens'] = df_text['text_lower'].str.split()

    custom_stopwords = {'and', 'or', 'with', 'of', 'the'}
    df_text['tokens_clean'] = df_text['tokens'].apply(
        lambda x: [word for word in x if word not in custom_stopwords]
    )
    df_text['clean_text'] = df_text['tokens_clean'].apply(lambda x: ' '.join(x))

    # Bagi makanan berdasarkan kuartil protein
    protein_quartiles = pd.qcut(df_preprocessed_numeric['Protein_g'], 4,
                                labels=['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi'])

    st.subheader("Word Cloud per Kuartil Protein")

    # Buat 2 kolom untuk layout
    cols = st.columns(2)

    for idx, quartile in enumerate(['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi']):
        with cols[idx % 2]:
            st.markdown(f"**{quartile}**")

            idx_quartile = protein_quartiles[protein_quartiles == quartile].index
            quartile_texts = df_text.loc[idx_quartile, 'clean_text'].dropna()

            if len(quartile_texts) > 0:
                all_text = ' '.join(quartile_texts.astype(str))

                if len(all_text.strip()) > 0:
                    # Buat WordCloud kecil
                    wc = WordCloud(
                        width=200,
                        height=150,
                        background_color='white',
                        colormap='viridis',
                        max_words=15,
                        min_font_size=8,
                        max_font_size=25,
                        random_state=42
                    ).generate(all_text)

                    # Buat figure kecil
                    fig, ax = plt.subplots(figsize=(3, 2))
                    ax.imshow(wc, interpolation='bilinear')
                    ax.axis("off")

                    st.pyplot(fig, use_container_width=False)

                    # Info statistik
                    mean_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].mean()
                    st.caption(f"Protein: {mean_protein:.1f}g | {len(quartile_texts)} makanan")

# =========================
# 7. SCATTER PLOT - DIPERBAIKI
# =========================
elif page == "Scatter Plot":
    st.header("📈 Scatter Plot Analisis Hubungan")

    col1, col2 = st.columns(2)

    with col1:
        x_axis = st.selectbox(
            "Pilih sumbu X:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=3
        )

    with col2:
        y_axis = st.selectbox(
            "Pilih sumbu Y:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=0
        )

    # Hitung korelasi
    correlation = df_preprocessed_numeric[x_axis].corr(df_preprocessed_numeric[y_axis])

    # Plot dengan container untuk kontrol ukuran
    with st.container():
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            fig, ax = plt.subplots(figsize=(5, 3))

            scatter = sns.scatterplot(
                data=df_preprocessed_numeric,
                x=x_axis,
                y=y_axis,
                hue='Label_Kesehatan',
                palette={'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'},
                alpha=0.7,
                s=40,
                ax=ax
            )

            ax.set_title(f'Hubungan {x_axis} dan {y_axis}', fontsize=11)
            ax.set_xlabel(x_axis.replace('_', ' '), fontsize=10)
            ax.set_ylabel(y_axis.replace('_', ' '), fontsize=10)
            ax.tick_params(labelsize=9)
            ax.grid(True, alpha=0.3)

            ax.legend(title='Label Kesehatan', fontsize=9, title_fontsize=10)

            st.pyplot(fig, use_container_width=False)

    # Analisis korelasi
    st.divider()
    st.subheader("Analisis Korelasi")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Koefisien Korelasi", f"{correlation:.3f}")

    with col2:
        if abs(correlation) > 0.7:
            strength = "Kuat"
        elif abs(correlation) > 0.3:
            strength = "Sedang"
        else:
            strength = "Lemah"
        st.metric("Kekuatan Hubungan", strength)

    with col3:
        direction = "Positif" if correlation > 0 else "Negatif"
        st.metric("Arah Hubungan", direction)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray; font-size: 0.8em; padding: 10px;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv • Created with Streamlit
    </div>
    """,
    unsafe_allow_html=True
)# -*- coding: utf-8 -*-

# =========================
# IMPORT
# =========================
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN (WAJIB DI SINI - PERUBAHAN PERTAMA)
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="centered",  # PERUBAHAN PENTING: dari "wide" jadi "centered"
    initial_sidebar_state="expanded"
)

# =========================
# GLOBAL VISUAL CONFIG - DIPERBAIKI
# =========================
VIS_SCALE = 0.6  # Scale untuk semua visualisasi

# Konfigurasi Matplotlib global
mpl.rcParams.update({
    "figure.figsize": (6, 3),  # UKURAN FIXED, tidak pakai multiplier
    "figure.dpi": 100,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "font.size": 10,
    "figure.autolayout": True,  # Untuk tight layout otomatis
})

# Set style Seaborn
sns.set_style("whitegrid")
sns.set_context("notebook", font_scale=VIS_SCALE)

# =========================
# FUNGSI BANTU UNTUK VISUALISASI YANG KONSISTEN
# =========================
def create_small_figure(width=6, height=3):
    """Membuat figure dengan ukuran terkontrol"""
    return plt.subplots(figsize=(width * VIS_SCALE, height * VIS_SCALE))

def display_figure(fig, use_container=False):
    """Menampilkan figure dengan kontrol width"""
    st.pyplot(fig, use_container_width=use_container)

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan', 'Food_Text']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped


df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("📊 Navigasi Dashboard")
page = st.sidebar.radio(
    "Pilih Halaman Analisis:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi",
        "Word Cloud Protein",
        "Scatter Plot"
    ]
)

# =========================
# 1. OVERVIEW DATA - DENGAN TAB NAVIGASI
# =========================
if page == "Overview Data":
    st.header("📊 Overview Dataset Nilai Gizi")

    # Tab navigation untuk Overview Data
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "📈 Metrik Utama",
        "📋 Data Sample",
        "📊 Distribusi",
        "🔍 Missing Values",
        "ℹ️ Informasi Dataset"
    ])

    with tab1:
        st.subheader("Metrik Utama Dataset")

        # Container untuk metrik ringkas dalam grid
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            total_data = len(df)
            st.metric("Total Data", f"{total_data:,}",
                     help="Jumlah total baris data dalam dataset")

        with col2:
            total_cols = len(df.columns)
            st.metric("Total Kolom", total_cols,
                     help="Jumlah total kolom/fitur dalam dataset")

        with col3:
            missing_total = df.isnull().sum().sum()
            st.metric("Missing Values", f"{missing_total:,}",
                     help="Total nilai yang hilang (missing) dalam dataset")

        with col4:
            sehat_count = len(df[df['Label_Kesehatan'] == 'Sehat'])
            st.metric("Makanan Sehat", f"{sehat_count:,}",
                     help="Jumlah makanan dengan label 'Sehat'")

        # Divider
        st.divider()

        # Statistik ringkas numerik dalam container kecil
        st.subheader("Statistik Numerik Ringkas")

        numeric_stats = df.select_dtypes(include=[np.number]).describe().T
        numeric_stats = numeric_stats[['mean', 'std', 'min', '50%', 'max']]
        numeric_stats.columns = ['Rata-rata', 'Std Dev', 'Minimum', 'Median', 'Maksimum']

        st.dataframe(
            numeric_stats.round(2),
            use_container_width=True,
            height=300,
            hide_index=True
        )

    with tab2:
        st.subheader("Data Sample Dataset")

        # Kontrol untuk jumlah data yang ditampilkan
        col_control1, col_control2 = st.columns(2)
        with col_control1:
            num_rows = st.slider("Jumlah baris:", 5, 20, 10)

        # Tampilkan data sample dengan container width
        display_cols = ['Food_Name', 'Label_Kesehatan', 'Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g']
        st.dataframe(
            df[display_cols].head(num_rows),
            use_container_width=True,
            height=350,
            hide_index=True
        )

    with tab3:
        st.subheader("Distribusi Data")

        # Distribusi Label Kesehatan - DIPERBAIKI UKURANNYA
        st.markdown("##### Distribusi Label Kesehatan")

        # Gunakan column layout untuk kontrol ukuran
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            counts = df['Label_Kesehatan'].value_counts()
            colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}
            bar_colors = [colors.get(label, 'gray') for label in counts.index]

            fig, ax = plt.subplots(figsize=(5, 3))  # UKURAN DIPERKECIL
            bars = ax.bar(counts.index, counts.values, color=bar_colors)
            ax.set_title("Distribusi Label Kesehatan", fontsize=11)
            ax.set_xlabel("Label Kesehatan", fontsize=10)
            ax.set_ylabel("Jumlah", fontsize=10)
            ax.grid(axis='y', alpha=0.3)

            # Tambah nilai di atas bar
            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height,
                       f'{int(height)}', ha='center', va='bottom', fontsize=9)

            # TAMPILKAN DENGAN KONTROL WIDTH
            st.pyplot(fig, use_container_width=False)

        st.divider()

        # Distribusi Kolom Numerik - DIPERBAIKI
        st.markdown("##### Distribusi Kolom Numerik")

        numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
        selected_numeric = st.selectbox(
            "Pilih kolom numerik:",
            numeric_cols,
            key="dist_numeric"
        )

        if selected_numeric in df.columns:
            # Gunakan column layout lagi
            left_col, center_col, right_col = st.columns([1, 3, 1])

            with center_col:
                fig2, ax2 = plt.subplots(figsize=(5, 2.5))  # UKURAN DIPERKECIL
                ax2.hist(df[selected_numeric].dropna(), bins=20, edgecolor='black', alpha=0.7)
                ax2.set_title(f"Distribusi {selected_numeric}", fontsize=11)
                ax2.set_xlabel(selected_numeric, fontsize=10)
                ax2.set_ylabel("Frekuensi", fontsize=10)
                ax2.grid(alpha=0.3)

                # Tambah statistik pada plot
                mean_val = df[selected_numeric].mean()
                median_val = df[selected_numeric].median()
                ax2.axvline(mean_val, color='red', linestyle='--', label=f'Mean: {mean_val:.1f}')
                ax2.axvline(median_val, color='green', linestyle='--', label=f'Median: {median_val:.1f}')
                ax2.legend(fontsize=9)

                st.pyplot(fig2, use_container_width=False)

    with tab4:
        st.subheader("Analisis Missing Values")

        # Hitung missing values
        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum(),
            'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
        }).sort_values('Missing Values', ascending=False)

        # Tampilkan hanya yang ada missing values
        missing_filtered = missing_data[missing_data['Missing Values'] > 0]

        if len(missing_filtered) > 0:
            st.warning(f"⚠️ Ditemukan {len(missing_filtered)} kolom dengan missing values")

            # Tampilkan tabel missing values
            st.dataframe(
                missing_filtered,
                use_container_width=True,
                height=200,
                hide_index=True
            )
        else:
            st.success("✅ Tidak ada missing values pada dataset!")

    with tab5:
        st.subheader("Informasi Dataset")

        # Informasi dasar dataset
        info_data = {
            'Attribute': ['Nama File', 'Total Baris', 'Total Kolom', 'Ukuran Memori'],
            'Value': ['nilai_gizi.csv', f"{len(df):,}", f"{len(df.columns)}",
                     f"{df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB"]
        }

        info_df = pd.DataFrame(info_data)
        st.dataframe(info_df, use_container_width=True, height=150, hide_index=True)

# =========================
# 2. ANALISIS NUMERIK - DIPERBAIKI UKURANNYA
# =========================
elif page == "Analisis Numerik":
    st.header("📈 Analisis Numerik")

    # Gunakan tabs untuk organisasi yang lebih baik
    tab1, tab2, tab3, tab4 = st.tabs([
        "📊 Distribusi",
        "⚖️ Perbandingan",
        "🔗 Korelasi",
        "📉 Histogram"
    ])

    with tab1:
        st.subheader("Distribusi Rata-rata Nutrisi per Kategori")

        # Gunakan container untuk kontrol layout
        with st.container():
            avg_nutrisi = df_preprocessed_numeric.groupby(
                'Label_Kesehatan'
            )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

            # Buat subplot dengan ukuran yang lebih kecil
            fig, axes = plt.subplots(2, 2, figsize=(8, 5))
            nutrients = [
                ('Protein_g', 'Protein (g)'),
                ('Fat_g', 'Lemak (g)'),
                ('Sugar_g', 'Gula (g)'),
                ('Sodium_mg', 'Natrium (mg)')
            ]

            colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

            for idx, (col, title) in enumerate(nutrients):
                ax = axes[idx // 2, idx % 2]
                values = avg_nutrisi[col]
                bars = ax.bar(
                    values.index,
                    values.values,
                    color=[colors[label] for label in values.index]
                )
                ax.set_title(f'Rata-rata {title}', fontsize=10)
                ax.tick_params(axis='x', rotation=45, labelsize=8)
                ax.tick_params(axis='y', labelsize=8)

                for bar in bars:
                    h = bar.get_height()
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        h,
                        f"{h:.1f}",
                        ha='center',
                        va='bottom',
                        fontsize=8
                    )
                ax.grid(axis='y', alpha=0.3)

            plt.tight_layout()
            # TAMPILKAN DENGAN KONTROL WIDTH
            st.pyplot(fig, use_container_width=False)

    with tab2:
        st.subheader("Perbandingan Gula & Natrium")

        with st.container():
            avg = df_preprocessed_numeric.groupby(
                'Label_Kesehatan'
            )[['Sugar_g', 'Sodium_mg']].mean()

            fig, ax = plt.subplots(figsize=(5, 3))
            avg.plot(kind='bar', ax=ax)
            ax.set_title("Perbandingan Gula & Natrium", fontsize=11)
            ax.set_xlabel("Label Kesehatan", fontsize=10)
            ax.set_ylabel("Rata-rata", fontsize=10)
            ax.tick_params(axis='x', rotation=0, labelsize=9)
            ax.tick_params(axis='y', labelsize=9)
            ax.legend(fontsize=9)
            ax.grid(axis='y', alpha=0.3)

            st.pyplot(fig, use_container_width=False)

    with tab3:
        st.subheader("Korelasi Antar Nutrisi")

        with st.container():
            corr = df_preprocessed_numeric[
                ['Energy_kcal', 'Protein_g', 'Fat_g',
                 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
            ].corr()

            fig, ax = plt.subplots(figsize=(5, 4))
            sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax, fmt='.2f',
                       annot_kws={"size": 8}, cbar_kws={"shrink": 0.8})
            ax.set_title("Heatmap Korelasi", fontsize=11)

            st.pyplot(fig, use_container_width=False)

    with tab4:
        st.subheader("Distribusi Energi")

        with st.container():
            fig, ax = plt.subplots(figsize=(5, 3))
            ax.hist(df_numeric_capped["Energy_kcal"], bins=20, edgecolor='black', alpha=0.7)
            ax.set_title("Distribusi Energy (kcal)", fontsize=11)
            ax.set_xlabel("Energy (kcal)", fontsize=10)
            ax.set_ylabel("Frekuensi", fontsize=10)
            ax.tick_params(labelsize=9)
            ax.grid(alpha=0.3)

            # Tambah garis mean dan median
            mean_val = df_numeric_capped["Energy_kcal"].mean()
            median_val = df_numeric_capped["Energy_kcal"].median()
            ax.axvline(mean_val, color='red', linestyle='--', label=f'Mean: {mean_val:.0f}')
            ax.axvline(median_val, color='green', linestyle='--', label=f'Median: {median_val:.0f}')
            ax.legend(fontsize=9)

            st.pyplot(fig, use_container_width=False)

# =========================
# 3. ANALISIS TEKS - DIPERBAIKI
# =========================
elif page == "Analisis Teks":
    st.header("📝 Analisis Teks")

    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    st.subheader("Word Cloud")

    label_option = st.selectbox(
        "Pilih Label:",
        ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat'],
        key="wordcloud_label"
    )

    if label_option == 'Semua':
        text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
    else:
        text_data = " ".join(
            df_text[df_text['Label_Kesehatan'] == label_option]
            ['Food_Text'].dropna().astype(str)
        )

    if text_data.strip():
        # Gunakan container untuk kontrol layout
        with st.container():
            left_col, center_col, right_col = st.columns([1, 2, 1])

            with center_col:
                fig, ax = plt.subplots(figsize=(5, 2.5))
                wc = WordCloud(
                    background_color="white",
                    width=400,
                    height=200,
                    max_words=50
                ).generate(text_data)
                ax.imshow(wc, interpolation='bilinear')
                ax.axis("off")
                ax.set_title(f"Word Cloud - {label_option}", fontsize=11)

                st.pyplot(fig, use_container_width=False)

                # Informasi tambahan
                word_count = len(text_data.split())
                st.caption(f"**Jumlah kata:** {word_count:,} kata")
    else:
        st.warning("Tidak ada data teks untuk ditampilkan")

# =========================
# 4. TOP 10 MAKANAN - DIPERBAIKI
# =========================
elif page == "Top 10 Makanan":
    st.header("🏆 Top 10 Makanan")

    nutrient_options = {
        "Protein (g)": "Protein_g",
        "Lemak (g)": "Fat_g",
        "Gula (g)": "Sugar_g",
        "Natrium (mg)": "Sodium_mg",
        "Energi (kcal)": "Energy_kcal",
        "Karbohidrat (g)": "Carbohydrate_g"
    }

    selected_nutrient = st.selectbox(
        "Pilih Kandungan Nutrisi:",
        list(nutrient_options.keys())
    )

    col_name = nutrient_options[selected_nutrient]

    n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 15, 10)

    top_foods = (
        df.sort_values(col_name, ascending=False)
        .head(n_top)
    )

    # Gunakan container untuk kontrol layout
    with st.container():
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            fig, ax = plt.subplots(figsize=(6, 4))
            bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
            ax.set_xlabel(selected_nutrient, fontsize=10)
            ax.set_title(f"Top {n_top} Makanan {selected_nutrient} Tertinggi", fontsize=11)
            ax.invert_yaxis()
            ax.tick_params(labelsize=9)
            ax.grid(axis='x', alpha=0.3)

            # Warna berdasarkan label kesehatan
            for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
                if label == "Sehat":
                    bar.set_color('green')
                elif label == "Cukup Sehat":
                    bar.set_color('orange')
                else:
                    bar.set_color('red')

            # Legend
            import matplotlib.patches as mpatches
            healthy_patch = mpatches.Patch(color='green', label='Sehat')
            moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
            unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
            ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch],
                      fontsize=9, loc='lower right')

            st.pyplot(fig, use_container_width=False)

    # Tabel detail
    st.subheader("Data Detail")
    display_cols = ['Food_Name', 'Label_Kesehatan', col_name]
    st.dataframe(top_foods[display_cols],
                 use_container_width=True,
                 height=300,
                 hide_index=True)

# =========================
# 5. ANALISIS MULTI-DIMENSI - DIPERBAIKI
# =========================
elif page == "Analisis Multi-Dimensi":
    st.header("🔍 Analisis Multi-Dimensi")

    categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']

    # Ringkasan per kategori
    for idx, category in enumerate(categories):
        with st.expander(f"**{category.upper()}**", expanded=(idx==0)):
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]

            col1, col2 = st.columns(2)

            with col1:
                st.metric("Jumlah Makanan", f"{len(subset)}")
                avg_protein = subset['Protein_g'].mean()
                st.metric("Rata-rata Protein", f"{avg_protein:.1f}g")

            with col2:
                avg_sugar = subset['Sugar_g'].mean()
                st.metric("Rata-rata Gula", f"{avg_sugar:.1f}g")
                avg_sodium = subset['Sodium_mg'].mean()
                st.metric("Rata-rata Natrium", f"{avg_sodium:.1f}mg")

    st.divider()

    # Perbandingan antar kategori
    st.subheader("Perbandingan Antar Kategori")

    selected_nutrient = st.selectbox(
        "Pilih Nutrisi untuk Perbandingan:",
        ['Protein', 'Gula', 'Lemak', 'Natrium', 'Energi'],
        key="compare_nutrient"
    )

    # Mapping
    nutrient_map = {
        'Protein': 'Protein_g',
        'Gula': 'Sugar_g',
        'Lemak': 'Fat_g',
        'Natrium': 'Sodium_mg',
        'Energi': 'Energy_kcal'
    }

    selected_col = nutrient_map[selected_nutrient]

    with st.container():
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            comparison_data = []
            for category in categories:
                subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
                avg_val = subset[selected_col].mean()
                comparison_data.append({
                    'Kategori': category,
                    'Rata_rata': avg_val
                })

            comparison_df = pd.DataFrame(comparison_data)

            # Plot perbandingan
            fig, ax = plt.subplots(figsize=(5, 3))
            colors = ['green', 'orange', 'red']
            bars = ax.bar(comparison_df['Kategori'], comparison_df['Rata_rata'], color=colors)

            ax.set_title(f'Perbandingan {selected_nutrient}', fontsize=11)
            ax.set_ylabel(f'Rata-rata {selected_nutrient}', fontsize=10)
            ax.tick_params(labelsize=9)
            ax.grid(axis='y', alpha=0.3)

            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
                       f'{height:.1f}', ha='center', va='bottom', fontsize=9)

            st.pyplot(fig, use_container_width=False)

# =========================
# 6. WORD CLOUD PROTEIN - DIPERBAIKI
# =========================
elif page == "Word Cloud Protein":
    st.header("☁️ Word Cloud Berdasarkan Level Protein")

    # Preprocessing teks
    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()
    df_text['tokens'] = df_text['text_lower'].str.split()

    custom_stopwords = {'and', 'or', 'with', 'of', 'the'}
    df_text['tokens_clean'] = df_text['tokens'].apply(
        lambda x: [word for word in x if word not in custom_stopwords]
    )
    df_text['clean_text'] = df_text['tokens_clean'].apply(lambda x: ' '.join(x))

    # Bagi makanan berdasarkan kuartil protein
    protein_quartiles = pd.qcut(df_preprocessed_numeric['Protein_g'], 4,
                                labels=['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi'])

    st.subheader("Word Cloud per Kuartil Protein")

    # Buat 2 kolom untuk layout
    cols = st.columns(2)

    for idx, quartile in enumerate(['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi']):
        with cols[idx % 2]:
            st.markdown(f"**{quartile}**")

            idx_quartile = protein_quartiles[protein_quartiles == quartile].index
            quartile_texts = df_text.loc[idx_quartile, 'clean_text'].dropna()

            if len(quartile_texts) > 0:
                all_text = ' '.join(quartile_texts.astype(str))

                if len(all_text.strip()) > 0:
                    # Buat WordCloud kecil
                    wc = WordCloud(
                        width=200,
                        height=150,
                        background_color='white',
                        colormap='viridis',
                        max_words=15,
                        min_font_size=8,
                        max_font_size=25,
                        random_state=42
                    ).generate(all_text)

                    # Buat figure kecil
                    fig, ax = plt.subplots(figsize=(3, 2))
                    ax.imshow(wc, interpolation='bilinear')
                    ax.axis("off")

                    st.pyplot(fig, use_container_width=False)

                    # Info statistik
                    mean_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].mean()
                    st.caption(f"Protein: {mean_protein:.1f}g | {len(quartile_texts)} makanan")

# =========================
# 7. SCATTER PLOT - DIPERBAIKI
# =========================
elif page == "Scatter Plot":
    st.header("📈 Scatter Plot Analisis Hubungan")

    col1, col2 = st.columns(2)

    with col1:
        x_axis = st.selectbox(
            "Pilih sumbu X:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=3
        )

    with col2:
        y_axis = st.selectbox(
            "Pilih sumbu Y:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=0
        )

    # Hitung korelasi
    correlation = df_preprocessed_numeric[x_axis].corr(df_preprocessed_numeric[y_axis])

    # Plot dengan container untuk kontrol ukuran
    with st.container():
        left_col, center_col, right_col = st.columns([1, 3, 1])

        with center_col:
            fig, ax = plt.subplots(figsize=(5, 3))

            scatter = sns.scatterplot(
                data=df_preprocessed_numeric,
                x=x_axis,
                y=y_axis,
                hue='Label_Kesehatan',
                palette={'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'},
                alpha=0.7,
                s=40,
                ax=ax
            )

            ax.set_title(f'Hubungan {x_axis} dan {y_axis}', fontsize=11)
            ax.set_xlabel(x_axis.replace('_', ' '), fontsize=10)
            ax.set_ylabel(y_axis.replace('_', ' '), fontsize=10)
            ax.tick_params(labelsize=9)
            ax.grid(True, alpha=0.3)

            ax.legend(title='Label Kesehatan', fontsize=9, title_fontsize=10)

            st.pyplot(fig, use_container_width=False)

    # Analisis korelasi
    st.divider()
    st.subheader("Analisis Korelasi")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Koefisien Korelasi", f"{correlation:.3f}")

    with col2:
        if abs(correlation) > 0.7:
            strength = "Kuat"
        elif abs(correlation) > 0.3:
            strength = "Sedang"
        else:
            strength = "Lemah"
        st.metric("Kekuatan Hubungan", strength)

    with col3:
        direction = "Positif" if correlation > 0 else "Negatif"
        st.metric("Arah Hubungan", direction)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray; font-size: 0.8em; padding: 10px;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv • Created with Streamlit
    </div>
    """,
    unsafe_allow_html=True
)