# -*- coding: utf-8 -*-
"""Datvis Final Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oo_fHrKdxc8K-HtHlxhMiz3xM69v1msn
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="wide"
)

st.title("Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan', 'Food_Text']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped


df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi",
        "Word Cloud Protein",
        "Scatter Plot"
    ]
)

# =========================
# 1. OVERVIEW DATA - DENGAN TAB NAVIGASI
# =========================
if page == "Overview Data":
    st.header("📊 Overview Data")

    # Tab navigation untuk Overview Data
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "Metrik Utama",
        "Data Sample",
        "Distribusi",
        "Missing Values",
        "Informasi Dataset"
    ])

    with tab1:
        st.subheader("📈 Metrik Utama Dataset")

        # Container untuk metrik ringkas
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            total_data = len(df)
            st.metric("Total Data", f"{total_data:,}",
                     help="Jumlah total baris data dalam dataset")

        with col2:
            total_cols = len(df.columns)
            st.metric("Total Kolom", total_cols,
                     help="Jumlah total kolom/fitur dalam dataset")

        with col3:
            missing_total = df.isnull().sum().sum()
            missing_percent = (missing_total / (total_data * total_cols) * 100)
            st.metric("Missing Values", f"{missing_total:,}",
                     delta=f"{missing_percent:.1f}%",
                     delta_color="inverse" if missing_percent > 5 else "normal",
                     help="Total nilai yang hilang (missing) dalam dataset")

        with col4:
            sehat_count = len(df[df['Label_Kesehatan'] == 'Sehat'])
            sehat_percent = (sehat_count / total_data * 100)
            st.metric("Makanan Sehat", f"{sehat_count:,}",
                     delta=f"{sehat_percent:.1f}%",
                     help="Jumlah makanan dengan label 'Sehat'")

        # Metrik tambahan
        col5, col6, col7, col8 = st.columns(4)

        with col5:
            cukup_sehat = len(df[df['Label_Kesehatan'] == 'Cukup Sehat'])
            st.metric("Cukup Sehat", f"{cukup_sehat:,}",
                     delta=f"{(cukup_sehat/total_data*100):.1f}%")

        with col6:
            kurang_sehat = len(df[df['Label_Kesehatan'] == 'Kurang Sehat'])
            st.metric("Kurang Sehat", f"{kurang_sehat:,}",
                     delta=f"{(kurang_sehat/total_data*100):.1f}%")

        with col7:
            unique_foods = df['Food_Name'].nunique()
            st.metric("Makanan Unik", f"{unique_foods:,}",
                     help="Jumlah nama makanan yang berbeda")

        with col8:
            avg_energy = df['Energy_kcal'].mean()
            st.metric("Rata-rata Energi", f"{avg_energy:.0f} kcal",
                     help="Rata-rata kandungan energi dalam dataset")

        # Statistik ringkas numerik
        st.divider()
        st.subheader("📊 Statistik Numerik Ringkas")

        numeric_stats = df.select_dtypes(include=[np.number]).describe().T
        numeric_stats = numeric_stats[['mean', 'std', 'min', '50%', 'max']]
        numeric_stats.columns = ['Rata-rata', 'Std Dev', 'Minimum', 'Median', 'Maksimum']

        st.dataframe(
            numeric_stats.round(2),
            use_container_width=True,
            height=250,
            hide_index=True
        )

    with tab2:
        st.subheader("📋 Data Sample Dataset")

        # Kontrol untuk jumlah data yang ditampilkan
        col_control1, col_control2 = st.columns(2)
        with col_control1:
            num_rows = st.slider("Jumlah baris yang ditampilkan:", 5, 50, 10)
        with col_control2:
            show_all_cols = st.checkbox("Tampilkan semua kolom", value=False)

        # Pilih kolom yang akan ditampilkan
        if not show_all_cols:
            default_cols = ['Food_Name', 'Label_Kesehatan', 'Energy_kcal',
                          'Protein_g', 'Fat_g', 'Sugar_g']
            selected_cols = st.multiselect(
                "Pilih kolom yang ditampilkan:",
                df.columns.tolist(),
                default=default_cols
            )
            display_df = df[selected_cols] if selected_cols else df[default_cols]
        else:
            display_df = df

        # Tampilkan data sample
        st.dataframe(
            display_df.head(num_rows),
            use_container_width=True,
            height=400,
            hide_index=True
        )

        # Informasi tentang data sample
        st.info(f"""
        **Informasi Data Sample:**
        - Menampilkan **{min(num_rows, len(df))} dari {len(df)}** baris data
        - Menampilkan **{len(display_df.columns)} dari {len(df.columns)}** kolom
        - Data diambil dari baris pertama dataset
        """)

    with tab3:
        st.subheader("📊 Distribusi Data")

        # Distribusi Label Kesehatan
        st.markdown("#### 🏷️ Distribusi Label Kesehatan")

        counts = df['Label_Kesehatan'].value_counts()
        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}
        bar_colors = [colors.get(label, 'gray') for label in counts.index]

        # Layout untuk chart dan tabel
        chart_col, table_col = st.columns([2, 1])

        with chart_col:
            fig, ax = plt.subplots(figsize=(8, 4))
            bars = ax.bar(counts.index, counts.values, color=bar_colors)
            ax.set_title("Distribusi Label Kesehatan", fontsize=12)
            ax.set_xlabel("Label Kesehatan", fontsize=10)
            ax.set_ylabel("Jumlah", fontsize=10)
            ax.grid(axis='y', alpha=0.3)

            # Tambah nilai di atas bar
            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height,
                       f'{int(height):,}', ha='center', va='bottom', fontsize=10)

            st.pyplot(fig)

        with table_col:
            distribusi_df = pd.DataFrame({
                'Label': counts.index,
                'Jumlah': counts.values,
                'Persentase': (counts.values / len(df) * 100).round(1)
            })
            st.dataframe(
                distribusi_df,
                use_container_width=True,
                height=200,
                hide_index=True
            )

        # Distribusi Kolom Numerik
        st.divider()
        st.markdown("#### 📈 Distribusi Kolom Numerik")

        numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
        selected_numeric = st.selectbox(
            "Pilih kolom numerik untuk melihat distribusi:",
            numeric_cols,
            key="dist_numeric"
        )

        if selected_numeric in df.columns:
            fig2, ax2 = plt.subplots(figsize=(8, 4))
            ax2.hist(df[selected_numeric].dropna(), bins=30, edgecolor='black', alpha=0.7)
            ax2.set_title(f"Distribusi {selected_numeric}", fontsize=12)
            ax2.set_xlabel(selected_numeric, fontsize=10)
            ax2.set_ylabel("Frekuensi", fontsize=10)
            ax2.grid(alpha=0.3)

            # Tambah statistik pada plot
            mean_val = df[selected_numeric].mean()
            median_val = df[selected_numeric].median()
            ax2.axvline(mean_val, color='red', linestyle='--', label=f'Mean: {mean_val:.1f}')
            ax2.axvline(median_val, color='green', linestyle='--', label=f'Median: {median_val:.1f}')
            ax2.legend()

            st.pyplot(fig2)

            # Statistik untuk kolom terpilih
            col_stats = df[selected_numeric].describe()
            st.dataframe(
                pd.DataFrame({
                    'Statistik': col_stats.index,
                    'Nilai': col_stats.values.round(2)
                }),
                use_container_width=True,
                height=300,
                hide_index=True
            )

    with tab4:
        st.subheader("🔍 Analisis Missing Values")

        # Hitung missing values
        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum(),
            'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
        }).sort_values('Missing Values', ascending=False)

        # Tampilkan hanya yang ada missing values
        missing_filtered = missing_data[missing_data['Missing Values'] > 0]

        if len(missing_filtered) > 0:
            st.warning(f"⚠️ **Ditemukan {len(missing_filtered)} kolom dengan missing values**")

            # Tampilkan tabel missing values
            st.dataframe(
                missing_filtered,
                use_container_width=True,
                height=300,
                hide_index=True
            )

            # Visualisasi missing values
            st.markdown("#### 📊 Visualisasi Missing Values")

            fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

            # Bar chart
            missing_bars = missing_filtered.set_index('Kolom')['Missing Values']
            missing_bars.plot(kind='bar', ax=ax1, color='coral')
            ax1.set_title("Missing Values per Kolom", fontsize=11)
            ax1.set_ylabel("Jumlah Missing", fontsize=9)
            ax1.tick_params(axis='x', rotation=45, labelsize=8)
            ax1.grid(axis='y', alpha=0.3)

            # Pie chart untuk persentase
            total_missing = missing_filtered['Missing Values'].sum()
            total_cells = len(df) * len(df.columns)
            present_cells = total_cells - total_missing

            sizes = [present_cells, total_missing]
            labels = ['Data Valid', 'Missing']
            colors_pie = ['lightgreen', 'coral']

            ax2.pie(sizes, labels=labels, colors=colors_pie, autopct='%1.1f%%',
                   startangle=90, explode=(0.1, 0))
            ax2.set_title(f"Persentase Missing Values\n({total_missing:,} dari {total_cells:,} sel)",
                         fontsize=11)

            plt.tight_layout()
            st.pyplot(fig)

            # Rekomendasi penanganan
            st.markdown("#### 💡 Rekomendasi Penanganan")

            high_missing = missing_filtered[missing_filtered['Persentase (%)'] > 30]
            medium_missing = missing_filtered[(missing_filtered['Persentase (%)'] > 5) &
                                            (missing_filtered['Persentase (%)'] <= 30)]
            low_missing = missing_filtered[missing_filtered['Persentase (%)'] <= 5]

            if len(high_missing) > 0:
                st.error(f"""
                **Kolom dengan missing values tinggi (>30%):**
                {', '.join(high_missing['Kolom'].tolist())}

                *Rekomendasi: Pertimbangkan untuk menghapus kolom ini atau melakukan imputasi yang hati-hati.*
                """)

            if len(medium_missing) > 0:
                st.warning(f"""
                **Kolom dengan missing values sedang (5-30%):**
                {', '.join(medium_missing['Kolom'].tolist())}

                *Rekomendasi: Gunakan imputasi statistik (mean, median, mode) atau model-based imputation.*
                """)

            if len(low_missing) > 0:
                st.success(f"""
                **Kolom dengan missing values rendah (≤5%):**
                {', '.join(low_missing['Kolom'].tolist())}

                *Rekomendasi: Simple imputation (mean/median) atau hapus baris yang mengandung missing.*
                """)

        else:
            st.success("✅ **Tidak ada missing values pada dataset!**")
            st.info("Dataset sudah bersih dan siap untuk dianalisis lebih lanjut.")

    with tab5:
        st.subheader("ℹ️ Informasi Dataset")

        # Informasi dasar dataset
        st.markdown("#### 📁 Informasi Umum")

        info_data = {
            'Attribute': ['Nama File', 'Total Baris', 'Total Kolom',
                         'Tipe Data', 'Ukuran Memori', 'Range Tanggal'],
            'Value': ['nilai_gizi.csv', f"{len(df):,}", f"{len(df.columns)}",
                     'CSV (Comma Separated Values)',
                     f"{df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB",
                     'Tidak tersedia']
        }

        info_df = pd.DataFrame(info_data)
        st.dataframe(info_df, use_container_width=True, height=250, hide_index=True)

        st.divider()

        # Informasi kolom
        st.markdown("#### 📋 Daftar Kolom Dataset")

        col_info = []
        for col in df.columns:
            dtype = str(df[col].dtype)
            non_null = df[col].count()
            unique = df[col].nunique()
            sample = str(df[col].iloc[0])[:30] + "..." if len(str(df[col].iloc[0])) > 30 else str(df[col].iloc[0])

            col_info.append({
                'Kolom': col,
                'Tipe Data': dtype,
                'Non-Null': non_null,
                'Unique': unique,
                'Contoh Nilai': sample
            })

        col_info_df = pd.DataFrame(col_info)
        st.dataframe(
            col_info_df,
            use_container_width=True,
            height=400,
            hide_index=True
        )

        st.divider()

        # Struktur data berdasarkan tipe
        st.markdown("#### 🏗️ Struktur Data Berdasarkan Tipe")

        dtype_counts = df.dtypes.value_counts()

        fig, ax = plt.subplots(figsize=(8, 4))
        bars = ax.bar([str(d) for d in dtype_counts.index], dtype_counts.values)
        ax.set_title("Distribusi Tipe Data", fontsize=12)
        ax.set_xlabel("Tipe Data", fontsize=10)
        ax.set_ylabel("Jumlah Kolom", fontsize=10)
        ax.grid(axis='y', alpha=0.3)

        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{int(height)}', ha='center', va='bottom', fontsize=10)

        st.pyplot(fig)

        # Ringkasan tipe data
        col1, col2, col3 = st.columns(3)

        with col1:
            numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
            st.metric("Kolom Numerik", len(numeric_cols))

        with col2:
            text_cols = df.select_dtypes(include=['object']).columns.tolist()
            st.metric("Kolom Teks", len(text_cols))

        with col3:
            other_cols = len(df.columns) - len(numeric_cols) - len(text_cols)
            st.metric("Tipe Lain", other_cols)

# =========================
# 2. ANALISIS NUMERIK
# =========================
elif page == "Analisis Numerik":
    st.header("Analisis Numerik")

    tab1, tab2, tab3, tab4 = st.tabs(
        ["Distribusi", "Perbandingan", "Korelasi", "Histogram"]
    )

    with tab1:
        avg_nutrisi = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

        fig, axes = plt.subplots(2, 2, figsize=(10, 6))
        nutrients = [
            ('Protein_g', 'Protein (g)'),
            ('Fat_g', 'Lemak (g)'),
            ('Sugar_g', 'Gula (g)'),
            ('Sodium_mg', 'Natrium (mg)')
        ]

        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for idx, (col, title) in enumerate(nutrients):
            ax = axes[idx // 2, idx % 2]
            values = avg_nutrisi[col]
            bars = ax.bar(
                values.index,
                values.values,
                color=[colors[label] for label in values.index]
            )
            ax.set_title(f'Rata-rata {title}', fontsize=10)
            ax.tick_params(axis='x', rotation=45, labelsize=8)
            ax.tick_params(axis='y', labelsize=8)

            for bar in bars:
                h = bar.get_height()
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    h,
                    f"{h:.1f}",
                    ha='center',
                    va='bottom',
                    fontsize=8
                )

        plt.tight_layout()
        st.pyplot(fig)

    with tab2:
        avg = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Sugar_g', 'Sodium_mg']].mean()

        fig, ax = plt.subplots(figsize=(8, 4))
        avg.plot(kind='bar', ax=ax)
        ax.set_title("Perbandingan Gula & Natrium", fontsize=11)
        ax.tick_params(axis='x', rotation=45, labelsize=9)
        ax.tick_params(axis='y', labelsize=9)
        ax.legend(fontsize=9)
        st.pyplot(fig)

    with tab3:
        corr = df_preprocessed_numeric[
            ['Energy_kcal', 'Protein_g', 'Fat_g',
             'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
        ].corr()

        fig, ax = plt.subplots(figsize=(8, 6))
        sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax, fmt='.2f',
                   annot_kws={"size": 8}, cbar_kws={"shrink": 0.8})
        ax.set_title("Heatmap Korelasi", fontsize=11)
        st.pyplot(fig)

    with tab4:
        fig, ax = plt.subplots(figsize=(7, 3))
        ax.hist(df_numeric_capped["Energy_kcal"], bins=20, edgecolor='black')
        ax.set_title("Distribusi Energy (kcal)", fontsize=11)
        ax.set_xlabel("Energy (kcal)", fontsize=9)
        ax.set_ylabel("Frekuensi", fontsize=9)
        ax.tick_params(labelsize=8)
        st.pyplot(fig)

# =========================
# 3. ANALISIS TEKS
# =========================
elif page == "Analisis Teks":
    st.header("Analisis Teks")

    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    st.subheader("☁️ Word Cloud")

    label_option = st.selectbox(
        "Pilih Label:",
        ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat'],
        key="wordcloud_label"
    )

    if label_option == 'Semua':
        text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
    else:
        text_data = " ".join(
            df_text[df_text['Label_Kesehatan'] == label_option]
            ['Food_Text'].dropna().astype(str)
        )

    if text_data.strip():
        fig, ax = plt.subplots(figsize=(6, 3))
        wc = WordCloud(
            background_color="white",
            width=400,
            height=200,
            max_words=50
        ).generate(text_data)
        ax.imshow(wc, interpolation='bilinear')
        ax.axis("off")
        ax.set_title(f"Word Cloud - {label_option}", fontsize=10)
        st.pyplot(fig)

        # Informasi tambahan
        word_count = len(text_data.split())
        st.info(f"**Jumlah kata dalam Word Cloud:** {word_count:,} kata")
    else:
        st.warning("Tidak ada data teks untuk ditampilkan")

# =========================
# 4. TOP 10 MAKANAN
# =========================
elif page == "Top 10 Makanan":
    st.header("Top 10 Makanan")

    nutrient_options = {
        "Protein (g)": "Protein_g",
        "Lemak (g)": "Fat_g",
        "Gula (g)": "Sugar_g",
        "Natrium (mg)": "Sodium_mg",
        "Energi (kcal)": "Energy_kcal",
        "Karbohidrat (g)": "Carbohydrate_g"
    }

    selected_nutrient = st.selectbox(
        "Pilih Kandungan Nutrisi:",
        list(nutrient_options.keys())
    )

    col_name = nutrient_options[selected_nutrient]

    n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 20, 10)

    top_foods = (
        df.sort_values(col_name, ascending=False)
        .head(n_top)
    )

    fig, ax = plt.subplots(figsize=(8, 4))
    bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
    ax.set_xlabel(selected_nutrient, fontsize=9)
    ax.set_title(f"Top {n_top} Makanan {selected_nutrient} Tertinggi", fontsize=11)
    ax.invert_yaxis()
    ax.tick_params(labelsize=8)

    for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
        if label == "Sehat":
            bar.set_color('green')
        elif label == "Cukup Sehat":
            bar.set_color('orange')
        else:
            bar.set_color('red')

    import matplotlib.patches as mpatches
    healthy_patch = mpatches.Patch(color='green', label='Sehat')
    moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
    unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
    ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch],
              fontsize=8, loc='lower right')

    st.pyplot(fig)

    st.subheader("Data Detail")
    display_cols = ['Food_Name', 'Label_Kesehatan', col_name, 'Food_Text']
    st.dataframe(top_foods[display_cols], use_container_width=True, hide_index=True)

# =========================
# 5. ANALISIS MULTI-DIMENSI
# =========================
elif page == "Analisis Multi-Dimensi":
    st.header("Analisis Multi-Dimensi")

    st.subheader("🔍 Insight Pola Nutrisi")

    categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']
    nutrients = ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg', 'Energy_kcal']
    nutrient_names = ['Protein', 'Lemak', 'Gula', 'Natrium', 'Energi']
    units = ['g', 'g', 'g', 'mg', 'kcal']

    for idx, category in enumerate(categories):
        with st.expander(f"**{category.upper()}**", expanded=(idx==0)):
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]

            # Metrik utama
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Jumlah Makanan", f"{len(subset)}")
            with col2:
                top_protein = subset.nlargest(1, 'Protein_g')
                if not top_protein.empty:
                    st.metric("Protein Tertinggi",
                             f"{top_protein['Protein_g'].values[0]:.1f}g",
                             top_protein['Food_Name'].values[0])
            with col3:
                top_sugar = subset.nlargest(1, 'Sugar_g')
                if not top_sugar.empty:
                    st.metric("Gula Tertinggi",
                             f"{top_sugar['Sugar_g'].values[0]:.1f}g",
                             top_sugar['Food_Name'].values[0])

            # Rata-rata nutrisi
            st.markdown("**📊 Rata-rata Kandungan Nutrisi:**")
            avg_values = []
            for nutrient, name, unit in zip(nutrients, nutrient_names, units):
                avg_val = subset[nutrient].mean()
                avg_values.append({
                    'Nutrisi': name,
                    'Rata_Rata': avg_val,
                    'Unit': unit
                })

            avg_df = pd.DataFrame(avg_values)
            avg_df = avg_df.sort_values('Rata_Rata', ascending=False)

            # Tampilkan metrik nutrisi
            cols = st.columns(len(avg_df))
            for i, row in avg_df.iterrows():
                with cols[i]:
                    st.metric(
                        label=row['Nutrisi'],
                        value=f"{row['Rata_Rata']:.1f}",
                        delta=row['Unit'],
                        delta_color="off"
                    )

            # Karakteristik pola
            st.markdown("**🎯 Karakteristik Pola:**")

            if category == 'Sehat':
                st.markdown("""
                - **Protein tinggi**, gula rendah
                - **Lemak dalam jumlah sedang**
                - **Natrium terkontrol**
                - **Energi seimbang**
                - **Contoh makanan:** Ikan, sayuran, biji-bijian
                """)
            elif category == 'Cukup Sehat':
                st.markdown("""
                - **Nutrisi seimbang**
                - **Protein dan karbohidrat cukup**
                - **Gula dan natrium sedang**
                - **Variasi kandungan lemak**
                - **Contoh makanan:** Olahan tradisional, makanan dengan bumbu
                """)
            elif category == 'Kurang Sehat':
                st.markdown("""
                - **Gula tinggi**
                - **Lemak jenuh tinggi**
                - **Natrium tinggi**
                - **Energi tinggi**
                - **Contoh makanan:** Makanan cepat saji, makanan olahan, dessert
                """)

            # Contoh makanan representatif
            st.markdown("**🍽️ Contoh Makanan Representatif:**")
            if len(subset) >= 3:
                sample_foods = subset.sample(3, random_state=42)
                for _, food in sample_foods.iterrows():
                    st.markdown(f"- **{food['Food_Name']}**")
                    st.markdown(f"  Protein: {food['Protein_g']:.1f}g | Lemak: {food['Fat_g']:.1f}g | Gula: {food['Sugar_g']:.1f}g")

    st.divider()

    # Perbandingan antar kategori
    st.subheader("📈 Perbandingan Antar Kategori")

    selected_nutrient = st.selectbox(
        "Pilih Nutrisi untuk Perbandingan:",
        nutrient_names,
        key="compare_nutrient"
    )

    nutrient_map = dict(zip(nutrient_names, nutrients))
    selected_col = nutrient_map[selected_nutrient]

    comparison_data = []
    for category in categories:
        subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
        avg_val = subset[selected_col].mean()
        comparison_data.append({
            'Kategori': category,
            'Rata_rata': avg_val
        })

    comparison_df = pd.DataFrame(comparison_data)

    # Plot perbandingan
    fig, ax = plt.subplots(figsize=(6, 3))
    colors = ['green', 'orange', 'red']
    bars = ax.bar(comparison_df['Kategori'], comparison_df['Rata_rata'], color=colors)

    ax.set_title(f'Perbandingan {selected_nutrient}', fontsize=11)
    ax.set_ylabel(f'Rata-rata {selected_nutrient}', fontsize=9)
    ax.tick_params(labelsize=8)

    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
               f'{height:.1f}', ha='center', va='bottom', fontsize=8)

    st.pyplot(fig)

    # Insight perbandingan
    st.markdown("### 📊 Insight Perbandingan")

    unit = units[nutrient_names.index(selected_nutrient)]
    sorted_df = comparison_df.sort_values('Rata_rata', ascending=False)
    highest = sorted_df.iloc[0]
    lowest = sorted_df.iloc[-1]
    difference = abs(highest['Rata_rata'] - lowest['Rata_rata'])

    col1, col2 = st.columns(2)
    with col1:
        st.info(f"""
        **🏆 Tertinggi:**
        **{highest['Kategori']}**
        {highest['Rata_rata']:.1f} {unit}
        """)

    with col2:
        st.info(f"""
        **📉 Terendah:**
        **{lowest['Kategori']}**
        {lowest['Rata_rata']:.1f} {unit}
        """)

    st.info(f"""
    **📏 Perbedaan:**
    {difference:.1f} {unit}
    *({highest['Kategori']} memiliki {selected_nutrient} {difference:.1f} {unit} lebih tinggi dari {lowest['Kategori']})*
    """)

# =========================
# 6. WORD CLOUD BERDASARKAN LEVEL PROTEIN
# =========================
elif page == "Word Cloud Protein":
    st.header("Word Cloud Berdasarkan Level Protein")

    # Preprocessing teks untuk word cloud
    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()
    df_text['tokens'] = df_text['text_lower'].str.split()

    custom_stopwords = {'and', 'or', 'with', 'of', 'the'}
    df_text['tokens_clean'] = df_text['tokens'].apply(
        lambda x: [word for word in x if word not in custom_stopwords]
    )
    df_text['clean_text'] = df_text['tokens_clean'].apply(lambda x: ' '.join(x))

    # Bagi makanan berdasarkan kuartil protein
    protein_quartiles = pd.qcut(df_preprocessed_numeric['Protein_g'], 4,
                                labels=['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi'])

    st.subheader("Word Cloud berdasarkan Kuartil Protein")

    # Buat 4 kolom untuk display
    cols = st.columns(2)

    for idx, quartile in enumerate(['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi']):
        with cols[idx % 2]:
            # Ambil indeks untuk kuartil ini
            idx_quartile = protein_quartiles[protein_quartiles == quartile].index

            # Ambil clean_text untuk makanan di kuartil ini
            quartile_texts = df_text.loc[idx_quartile, 'clean_text'].dropna()

            if len(quartile_texts) > 0:
                all_text = ' '.join(quartile_texts.astype(str))

                if len(all_text.strip()) > 0:
                    # UKURAN DIUBAH: menjadi 60% dari (2, 1.5) = (1.2, 0.9)
                    fig, ax = plt.subplots(figsize=(1.2, 0.9))
                    wc = WordCloud(
                        width=90,  # 60% dari 150 = 90
                        height=60,  # 60% dari 100 = 60
                        background_color='white',
                        colormap='viridis',
                        max_words=15,  # Diperkecil
                        contour_width=1,
                        contour_color='steelblue'
                    ).generate(all_text)

                    ax.imshow(wc, interpolation='bilinear')
                    ax.set_title(f'Protein: {quartile}\n({len(quartile_texts)} makanan)',
                                fontsize=5, fontweight='bold')  # Font lebih kecil
                    ax.axis('off')

                    # Tambahkan info statistik
                    mean_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].mean()
                    ax.text(0.5, -0.1, f'Rata-rata: {mean_protein:.1f}g',
                           transform=ax.transAxes, ha='center', fontsize=4,  # Font lebih kecil
                           bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

                    st.pyplot(fig)

                    # Tampilkan data ringkas
                    with st.expander(f"Lihat makanan pada kategori {quartile}"):
                        foods_in_quartile = df_preprocessed_numeric.loc[idx_quartile, ['Food_Name', 'Protein_g', 'Label_Kesehatan']]
                        st.dataframe(foods_in_quartile.sort_values('Protein_g', ascending=False).head(10),
                                   use_container_width=True, height=200)
                else:
                    st.info(f"Tidak ada data teks untuk kategori {quartile}")
            else:
                st.info(f"Tidak ada data untuk kategori {quartile}")

    # Statistik ringkas
    st.divider()
    st.subheader("Statistik Kuartil Protein")

    quartile_stats = []
    for quartile in ['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi']:
        idx_quartile = protein_quartiles[protein_quartiles == quartile].index
        if len(idx_quartile) > 0:
            mean_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].mean()
            min_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].min()
            max_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].max()
            count = len(idx_quartile)

            quartile_stats.append({
                'Kuartil Protein': quartile,
                'Jumlah Makanan': count,
                'Protein Rata-rata (g)': f"{mean_protein:.1f}",
                'Protein Min (g)': f"{min_protein:.1f}",
                'Protein Max (g)': f"{max_protein:.1f}"
            })

    stats_df = pd.DataFrame(quartile_stats)
    st.dataframe(stats_df, use_container_width=True, height=200)

# =========================
# 7. SCATTER PLOT
# =========================
elif page == "Scatter Plot":
    st.header("Scatter Plot Analisis Hubungan Nutrisi")

    col1, col2 = st.columns(2)

    with col1:
        x_axis = st.selectbox(
            "Pilih sumbu X:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=3
        )

    with col2:
        y_axis = st.selectbox(
            "Pilih sumbu Y:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=0
        )

    # Buat scatter plot dengan ukuran yang sesuai
    fig, ax = plt.subplots(figsize=(2.1, 1.2))  # 60% dari (3.5, 2) = (2.1, 1.2)

    scatter = sns.scatterplot(
        data=df_preprocessed_numeric,
        x=x_axis,
        y=y_axis,
        hue='Label_Kesehatan',
        palette={'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'},
        alpha=0.7,
        s=18,  # 60% dari 30 = 18
        ax=ax
    )

    ax.set_title(f'Hubungan {x_axis} dan {y_axis}', fontsize=7, fontweight='bold')  # Font lebih kecil
    ax.set_xlabel(x_axis.replace('_', ' '), fontsize=6)  # Font lebih kecil
    ax.set_ylabel(y_axis.replace('_', ' '), fontsize=6)  # Font lebih kecil
    ax.tick_params(labelsize=5)  # Font lebih kecil
    ax.grid(True, alpha=0.3)

    ax.legend(title='Label Kesehatan', fontsize=5, title_fontsize=6)  # Font lebih kecil

    st.pyplot(fig)

    # Analisis korelasi
    st.divider()
    st.subheader("Analisis Korelasi")

    correlation = df_preprocessed_numeric[x_axis].corr(df_preprocessed_numeric[y_axis])

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Koefisien Korelasi", f"{correlation:.3f}", help="Nilai antara -1 sampai 1")

    with col2:
        if abs(correlation) > 0.7:
            strength = "Kuat"
            color = "red" if correlation > 0 else "blue"
        elif abs(correlation) > 0.3:
            strength = "Sedang"
            color = "orange"
        else:
            strength = "Lemah"
            color = "gray"
        st.metric("Kekuatan Hubungan", strength, delta_color="off")

    with col3:
        if correlation > 0:
            direction = "Positif"
            delta_sign = "+"
        else:
            direction = "Negatif"
            delta_sign = "-"
        st.metric("Arah Hubungan", direction, delta_sign, delta_color="off")

    # Interpretasi korelasi
    with st.container():
        st.info(f"""
        **Interpretasi:**
        - **Koefisien Korelasi:** {correlation:.3f}
        - **Hubungan:** {direction} ({strength.lower()})
        - **Artinya:** {f"Jika {x_axis.replace('_', ' ')} meningkat, {y_axis.replace('_', ' ')} cenderung " + ("meningkat" if correlation > 0 else "menurun")}
        """)

    # Data point outlier
    st.divider()

    with st.expander("📊 Lihat Data Point dengan Nilai Ekstrem", expanded=False):
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**5 Data dengan Nilai Tertinggi pada Sumbu X:**")
            top_x = df_preprocessed_numeric.nlargest(5, x_axis)[['Food_Name', 'Label_Kesehatan', x_axis, y_axis]]
            st.dataframe(top_x, use_container_width=True, height=200)

        with col2:
            st.markdown("**5 Data dengan Nilai Tertinggi pada Sumbu Y:**")
            top_y = df_preprocessed_numeric.nlargest(5, y_axis)[['Food_Name', 'Label_Kesehatan', x_axis, y_axis]]
            st.dataframe(top_y, use_container_width=True, height=200)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray; font-size: 0.9em;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv
    </div>
    """,
    unsafe_allow_html=True
)