# -*- coding: utf-8 -*-
"""datvis_uas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2Bi9I66Xo6QURGk8zis3ZxWDfIhRXB-
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
from wordcloud import WordCloud

# =====================================================
# KONFIGURASI HALAMAN
# =====================================================
st.set_page_config(page_title="Datvis UAS", layout="wide")
st.title("📊 Dashboard Analisis Nutrisi & Teks Makanan")

# =====================================================
# SIDEBAR
# =====================================================
menu = st.sidebar.radio(
    "📌 Navigasi",
    ["Dataset", "Analisis Gizi", "Analisis Teks", "Integrasi Analisis"]
)

# =====================================================
# LOAD DATA
# =====================================================
df = pd.read_csv("dataset_nutrisi_text_300.csv")
df.columns = df.columns.str.strip()

numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']

for col in numeric_cols:
    df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

df_numeric = df[numeric_cols].copy()
for col in numeric_cols:
    df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

# =====================================================
# PREPROCESSING TEKS
# =====================================================
df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
df_text['clean_text'] = df_text['Food_Text'].astype(str).str.lower()

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df_text['clean_text'])
tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

y = df_text['Label_Kesehatan'].map({'Sehat': 1, 'Tidak Sehat': 0})
mi_scores = mutual_info_classif(tfidf_df, y)

mi_df = pd.DataFrame({
    "Fitur": tfidf_df.columns,
    "Information Gain": mi_scores
}).sort_values(by="Information Gain", ascending=False)

# =====================================================
# MENU 1 — DATASET
# =====================================================
if menu == "Dataset":
    st.header("📄 Dataset Awal")
    st.dataframe(df.head(10))

# =====================================================
# MENU 2 — ANALISIS GIZI
# =====================================================
elif menu == "Analisis Gizi":
    st.header("🧮 Analisis Gizi")

    # --- Bar Chart
    col1, col2 = st.columns(2)

    with col1:
        fig, ax = plt.subplots()
        df.groupby("Food_Name")["Protein_g"].mean().plot(kind="bar", ax=ax)
        ax.set_title("Rata-rata Protein")
        st.pyplot(fig)

    with col2:
        fig, ax = plt.subplots()
        df.groupby("Label_Kesehatan")[["Sugar_g","Sodium_mg"]].mean().plot(kind="bar", ax=ax)
        ax.set_title("Gula & Natrium")
        st.pyplot(fig)

    # --- Scatter & Histogram
    col1, col2 = st.columns(2)

    with col1:
        fig, ax = plt.subplots()
        sns.scatterplot(data=df, x="Protein_g", y="Fat_g", hue="Label_Kesehatan", ax=ax)
        ax.set_title("Protein vs Lemak")
        st.pyplot(fig)

    with col2:
        fig, ax = plt.subplots()
        ax.hist(df["Energy_kcal"], bins=20)
        ax.set_title("Distribusi Energi")
        st.pyplot(fig)

    # --- Korelasi
    with st.expander("📊 Lihat Korelasi Kandungan Gizi"):
        fig, ax = plt.subplots()
        sns.heatmap(
            df[["Protein_g","Fat_g","Sugar_g","Sodium_mg","Energy_kcal"]].corr(),
            annot=True, cmap="coolwarm", fmt=".2f", ax=ax
        )
        st.pyplot(fig)

# =====================================================
# MENU 3 — ANALISIS TEKS
# =====================================================
elif menu == "Analisis Teks":
    st.header("📝 Analisis Teks")

    col1, col2 = st.columns(2)

    with col1:
        wc = WordCloud(background_color="white").generate(
            " ".join(df[df["Label_Kesehatan"]=="Sehat"]["Food_Text"].astype(str))
        )
        fig, ax = plt.subplots()
        ax.imshow(wc); ax.axis("off")
        ax.set_title("WordCloud Sehat")
        st.pyplot(fig)

    with col2:
        wc = WordCloud(background_color="white").generate(
            " ".join(df[df["Label_Kesehatan"]=="Tidak Sehat"]["Food_Text"].astype(str))
        )
        fig, ax = plt.subplots()
        ax.imshow(wc); ax.axis("off")
        ax.set_title("WordCloud Tidak Sehat")
        st.pyplot(fig)

    st.subheader("🔑 Fitur Teks Paling Berpengaruh")
    fig, ax = plt.subplots()
    sns.barplot(data=mi_df.head(20), x="Information Gain", y="Fitur", ax=ax)
    st.pyplot(fig)

# =====================================================
# MENU 4 — INTEGRASI
# =====================================================
else:
    st.header("🔗 Integrasi Analisis Gizi & Teks")

    fig, axes = plt.subplots(1,2, figsize=(14,5))

    sns.scatterplot(
        data=df, x="Protein_g", y="Fat_g",
        hue="Label_Kesehatan", ax=axes[0]
    )
    axes[0].set_title("Protein vs Lemak")

    sns.barplot(
        data=mi_df.head(10),
        x="Information Gain", y="Fitur", ax=axes[1]
    )
    axes[1].set_title("Top 10 Information Gain")

    st.pyplot(fig)