# -*- coding: utf-8 -*-
"""Datvis Final Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oo_fHrKdxc8K-HtHlxhMiz3xM69v1msn
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN - DIUBAH KE CENTERED
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="centered",  # DIUBAH: dari "wide" ke "centered"
    initial_sidebar_state="expanded"
)

# =========================
# GLOBAL VISUAL CONFIG - DIPERKECIL LAGI
# =========================

# Skala global diperkecil lagi
VIS_SCALE = 0.35  # DIUBAH: dari 0.5 ke 0.35

import matplotlib as mpl
mpl.rcParams.update({
    "figure.figsize": (6 * VIS_SCALE, 3 * VIS_SCALE),  # DIUBAH: lebih kecil lagi
    "axes.titlesize": 10 * VIS_SCALE,
    "axes.labelsize": 8 * VIS_SCALE,
    "xtick.labelsize": 7 * VIS_SCALE,
    "ytick.labelsize": 7 * VIS_SCALE,
    "legend.fontsize": 7 * VIS_SCALE,
    "font.size": 8 * VIS_SCALE,
    "lines.linewidth": 1.2 * VIS_SCALE,
    "lines.markersize": 4 * VIS_SCALE,
})

sns.set_context(
    "notebook",  # DIUBAH: dari "paper" ke "notebook" (lebih kecil)
    font_scale=VIS_SCALE
)

st.title("📊 Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan', 'Food_Text']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped


df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("📌 Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    [
        "📊 Overview Data",
        "🔢 Analisis Numerik",
        "📝 Analisis Teks",
        "🏆 Top 10 Makanan",
        "🎯 Analisis Multi-Dimensi",
        "☁️ Word Cloud Protein",
        "📈 Scatter Plot"
    ]
)

# =========================
# 1. OVERVIEW DATA
# =========================
if page == "📊 Overview Data":
    st.header("📊 Overview Data")

    # Container utama untuk batas lebar
    with st.container():
        # Tab navigation untuk Overview Data
        tab1, tab2, tab3, tab4, tab5 = st.tabs([
            "📈 Metrik Utama",
            "📋 Data Sample",
            "📊 Distribusi",
            "🔍 Missing Values",
            "ℹ️ Informasi Dataset"
        ])

        with tab1:
            st.subheader("📈 Metrik Utama Dataset")

            # Container untuk metrik ringkas - lebih kompak
            col1, col2, col3, col4 = st.columns(4)

            with col1:
                total_data = len(df)
                st.metric("Total Data", f"{total_data:,}",
                         help="Jumlah total baris data dalam dataset")

            with col2:
                total_cols = len(df.columns)
                st.metric("Total Kolom", total_cols,
                         help="Jumlah total kolom/fitur dalam dataset")

            with col3:
                missing_total = df.isnull().sum().sum()
                missing_percent = (missing_total / (total_data * total_cols) * 100)
                st.metric("Missing Values", f"{missing_total:,}",
                         delta=f"{missing_percent:.1f}%",
                         delta_color="inverse" if missing_percent > 5 else "normal",
                         help="Total nilai yang hilang (missing) dalam dataset")

            with col4:
                sehat_count = len(df[df['Label_Kesehatan'] == 'Sehat'])
                sehat_percent = (sehat_count / total_data * 100)
                st.metric("Makanan Sehat", f"{sehat_count:,}",
                         delta=f"{sehat_percent:.1f}%",
                         help="Jumlah makanan dengan label 'Sehat'")

            # Metrik tambahan - baris kedua
            col5, col6, col7, col8 = st.columns(4)

            with col5:
                cukup_sehat = len(df[df['Label_Kesehatan'] == 'Cukup Sehat'])
                st.metric("Cukup Sehat", f"{cukup_sehat:,}",
                         delta=f"{(cukup_sehat/total_data*100):.1f}%")

            with col6:
                kurang_sehat = len(df[df['Label_Kesehatan'] == 'Kurang Sehat'])
                st.metric("Kurang Sehat", f"{kurang_sehat:,}",
                         delta=f"{(kurang_sehat/total_data*100):.1f}%")

            with col7:
                unique_foods = df['Food_Name'].nunique()
                st.metric("Makanan Unik", f"{unique_foods:,}",
                         help="Jumlah nama makanan yang berbeda")

            with col8:
                avg_energy = df['Energy_kcal'].mean()
                st.metric("Rata-rata Energi", f"{avg_energy:.0f} kcal",
                         help="Rata-rata kandungan energi dalam dataset")

            # Statistik ringkas numerik
            st.divider()
            st.subheader("📊 Statistik Numerik Ringkas")

            numeric_stats = df.select_dtypes(include=[np.number]).describe().T
            numeric_stats = numeric_stats[['mean', 'std', 'min', '50%', 'max']]
            numeric_stats.columns = ['Rata-rata', 'Std Dev', 'Minimum', 'Median', 'Maksimum']

            st.dataframe(
                numeric_stats.round(2),
                use_container_width=True,
                height=200,  # DIPERKECIL
                hide_index=True
            )

        with tab2:
            st.subheader("📋 Data Sample Dataset")

            # Kontrol untuk jumlah data yang ditampilkan
            col_control1, col_control2 = st.columns(2)
            with col_control1:
                num_rows = st.slider("Jumlah baris yang ditampilkan:", 5, 50, 10, key="sample_rows")
            with col_control2:
                show_all_cols = st.checkbox("Tampilkan semua kolom", value=False, key="show_all")

            # Pilih kolom yang akan ditampilkan
            if not show_all_cols:
                default_cols = ['Food_Name', 'Label_Kesehatan', 'Energy_kcal',
                              'Protein_g', 'Fat_g', 'Sugar_g']
                selected_cols = st.multiselect(
                    "Pilih kolom yang ditampilkan:",
                    df.columns.tolist(),
                    default=default_cols,
                    key="col_select"
                )
                display_df = df[selected_cols] if selected_cols else df[default_cols]
            else:
                display_df = df

            # Tampilkan data sample
            st.dataframe(
                display_df.head(num_rows),
                use_container_width=True,
                height=350,  # DIPERKECIL
                hide_index=True
            )

        with tab3:
            st.subheader("📊 Distribusi Data")

            # Distribusi Label Kesehatan
            st.markdown("#### 🏷️ Distribusi Label Kesehatan")

            counts = df['Label_Kesehatan'].value_counts()
            colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}
            bar_colors = [colors.get(label, 'gray') for label in counts.index]

            # Layout untuk chart dan tabel - lebih kecil
            chart_col, table_col = st.columns([2, 1])

            with chart_col:
                # GRAFIK LEBIH KECIL
                fig, ax = plt.subplots(figsize=(5, 2.5))  # DIPERKECIL
                bars = ax.bar(counts.index, counts.values, color=bar_colors)
                ax.set_title("Distribusi Label Kesehatan", fontsize=10)
                ax.set_xlabel("Label Kesehatan", fontsize=8)
                ax.set_ylabel("Jumlah", fontsize=8)
                ax.grid(axis='y', alpha=0.3)
                ax.tick_params(labelsize=7)

                # Tambah nilai di atas bar
                for bar in bars:
                    height = bar.get_height()
                    ax.text(bar.get_x() + bar.get_width()/2., height,
                           f'{int(height):,}', ha='center', va='bottom', fontsize=8)

                # TAMPILKAN DENGAN UKURAN TERKONTROL
                st.pyplot(fig, use_container_width=False)

            with table_col:
                distribusi_df = pd.DataFrame({
                    'Label': counts.index,
                    'Jumlah': counts.values,
                    'Persentase': (counts.values / len(df) * 100).round(1)
                })
                st.dataframe(
                    distribusi_df,
                    use_container_width=True,
                    height=150,  # DIPERKECIL
                    hide_index=True
                )

            # Distribusi Kolom Numerik
            st.divider()
            st.markdown("#### 📈 Distribusi Kolom Numerik")

            numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
            selected_numeric = st.selectbox(
                "Pilih kolom numerik untuk melihat distribusi:",
                numeric_cols,
                key="dist_numeric"
            )

            if selected_numeric in df.columns:
                # GRAFIK LEBIH KECIL
                fig2, ax2 = plt.subplots(figsize=(5, 2.5))  # DIPERKECIL
                ax2.hist(df[selected_numeric].dropna(), bins=20, edgecolor='black', alpha=0.7)  # bins dikurangi
                ax2.set_title(f"Distribusi {selected_numeric}", fontsize=10)
                ax2.set_xlabel(selected_numeric, fontsize=8)
                ax2.set_ylabel("Frekuensi", fontsize=8)
                ax2.grid(alpha=0.3)
                ax2.tick_params(labelsize=7)

                # Tambah statistik pada plot
                mean_val = df[selected_numeric].mean()
                median_val = df[selected_numeric].median()
                ax2.axvline(mean_val, color='red', linestyle='--', label=f'Mean: {mean_val:.1f}', linewidth=1)
                ax2.axvline(median_val, color='green', linestyle='--', label=f'Median: {median_val:.1f}', linewidth=1)
                ax2.legend(fontsize=7)

                # TAMPILKAN DENGAN UKURAN TERKONTROL
                st.pyplot(fig2, use_container_width=False)

                # Statistik untuk kolom terpilih
                col_stats = df[selected_numeric].describe()
                st.dataframe(
                    pd.DataFrame({
                        'Statistik': col_stats.index,
                        'Nilai': col_stats.values.round(2)
                    }),
                    use_container_width=True,
                    height=250,  # DIPERKECIL
                    hide_index=True
                )

        with tab4:
            st.subheader("🔍 Analisis Missing Values")

            # Hitung missing values
            missing_data = pd.DataFrame({
                'Kolom': df.columns,
                'Missing Values': df.isnull().sum(),
                'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
            }).sort_values('Missing Values', ascending=False)

            # Tampilkan hanya yang ada missing values
            missing_filtered = missing_data[missing_data['Missing Values'] > 0]

            if len(missing_filtered) > 0:
                st.warning(f"⚠️ **Ditemukan {len(missing_filtered)} kolom dengan missing values**")

                # Tampilkan tabel missing values
                st.dataframe(
                    missing_filtered,
                    use_container_width=True,
                    height=250,  # DIPERKECIL
                    hide_index=True
                )

                # Visualisasi missing values
                st.markdown("#### 📊 Visualisasi Missing Values")

                # GRAFIK LEBIH KECIL
                fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 2.5))  # DIPERKECIL

                # Bar chart
                missing_bars = missing_filtered.set_index('Kolom')['Missing Values']
                missing_bars.plot(kind='bar', ax=ax1, color='coral')
                ax1.set_title("Missing Values per Kolom", fontsize=9)
                ax1.set_ylabel("Jumlah Missing", fontsize=7)
                ax1.tick_params(axis='x', rotation=45, labelsize=6)
                ax1.tick_params(axis='y', labelsize=6)
                ax1.grid(axis='y', alpha=0.3)

                # Pie chart untuk persentase
                total_missing = missing_filtered['Missing Values'].sum()
                total_cells = len(df) * len(df.columns)
                present_cells = total_cells - total_missing

                sizes = [present_cells, total_missing]
                labels = ['Data Valid', 'Missing']
                colors_pie = ['lightgreen', 'coral']

                ax2.pie(sizes, labels=labels, colors=colors_pie, autopct='%1.1f%%',
                       startangle=90, explode=(0.1, 0))
                ax2.set_title(f"Persentase Missing Values", fontsize=9)

                plt.tight_layout()
                # TAMPILKAN DENGAN UKURAN TERKONTROL
                st.pyplot(fig, use_container_width=False)

            else:
                st.success("✅ **Tidak ada missing values pada dataset!**")
                st.info("Dataset sudah bersih dan siap untuk dianalisis lebih lanjut.")

        with tab5:
            st.subheader("ℹ️ Informasi Dataset")

            # Informasi dasar dataset
            st.markdown("#### 📁 Informasi Umum")

            info_data = {
                'Attribute': ['Nama File', 'Total Baris', 'Total Kolom',
                             'Tipe Data', 'Ukuran Memori', 'Range Tanggal'],
                'Value': ['nilai_gizi.csv', f"{len(df):,}", f"{len(df.columns)}",
                         'CSV (Comma Separated Values)',
                         f"{df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB",
                         'Tidak tersedia']
            }

            info_df = pd.DataFrame(info_data)
            st.dataframe(info_df, use_container_width=True, height=200, hide_index=True)

            st.divider()

            # Informasi kolom
            st.markdown("#### 📋 Daftar Kolom Dataset")

            col_info = []
            for col in df.columns:
                dtype = str(df[col].dtype)
                non_null = df[col].count()
                unique = df[col].nunique()
                sample = str(df[col].iloc[0])[:20] + "..." if len(str(df[col].iloc[0])) > 20 else str(df[col].iloc[0])

                col_info.append({
                    'Kolom': col,
                    'Tipe Data': dtype,
                    'Non-Null': non_null,
                    'Unique': unique,
                    'Contoh Nilai': sample
                })

            col_info_df = pd.DataFrame(col_info)
            st.dataframe(
                col_info_df,
                use_container_width=True,
                height=350,  # DIPERKECIL
                hide_index=True
            )

# =========================
# 2. ANALISIS NUMERIK - DIPERKECIL
# =========================
elif page == "🔢 Analisis Numerik":
    st.header("🔢 Analisis Numerik")

    # Gunakan container untuk batas lebar
    with st.container():
        tab1, tab2, tab3, tab4 = st.tabs(
            ["📊 Distribusi", "📈 Perbandingan", "🔗 Korelasi", "📉 Histogram"]
        )

        with tab1:
            avg_nutrisi = df_preprocessed_numeric.groupby(
                'Label_Kesehatan'
            )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

            # GRAFIK LEBIH KECIL
            fig, axes = plt.subplots(2, 2, figsize=(7, 4))  # DIPERKECIL
            nutrients = [
                ('Protein_g', 'Protein (g)'),
                ('Fat_g', 'Lemak (g)'),
                ('Sugar_g', 'Gula (g)'),
                ('Sodium_mg', 'Natrium (mg)')
            ]

            colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

            for idx, (col, title) in enumerate(nutrients):
                ax = axes[idx // 2, idx % 2]
                values = avg_nutrisi[col]
                bars = ax.bar(
                    values.index,
                    values.values,
                    color=[colors[label] for label in values.index]
                )
                ax.set_title(f'Rata-rata {title}', fontsize=8)
                ax.tick_params(axis='x', rotation=45, labelsize=6)
                ax.tick_params(axis='y', labelsize=6)

                for bar in bars:
                    h = bar.get_height()
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        h,
                        f"{h:.1f}",
                        ha='center',
                        va='bottom',
                        fontsize=6
                    )

            plt.tight_layout()
            # TAMPILKAN DENGAN UKURAN TERKONTROL
            st.pyplot(fig, use_container_width=False)

        with tab2:
            avg = df_preprocessed_numeric.groupby(
                'Label_Kesehatan'
            )[['Sugar_g', 'Sodium_mg']].mean()

            # GRAFIK LEBIH KECIL
            fig, ax = plt.subplots(figsize=(5, 2.5))  # DIPERKECIL
            avg.plot(kind='bar', ax=ax)
            ax.set_title("Perbandingan Gula & Natrium", fontsize=9)
            ax.tick_params(axis='x', rotation=45, labelsize=7)
            ax.tick_params(axis='y', labelsize=7)
            ax.legend(fontsize=7)
            # TAMPILKAN DENGAN UKURAN TERKONTROL
            st.pyplot(fig, use_container_width=False)

        with tab3:
            corr = df_preprocessed_numeric[
                ['Energy_kcal', 'Protein_g', 'Fat_g',
                 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
            ].corr()

            # GRAFIK LEBIH KECIL
            fig, ax = plt.subplots(figsize=(5, 3))  # DIPERKECIL
            sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax, fmt='.2f',
                       annot_kws={"size": 6}, cbar_kws={"shrink": 0.7})
            ax.set_title("Heatmap Korelasi", fontsize=9)
            # TAMPILKAN DENGAN UKURAN TERKONTROL
            st.pyplot(fig, use_container_width=False)

        with tab4:
            # GRAFIK LEBIH KECIL
            fig, ax = plt.subplots(figsize=(4, 2))  # DIPERKECIL
            ax.hist(df_numeric_capped["Energy_kcal"], bins=15, edgecolor='black')  # bins dikurangi
            ax.set_title("Distribusi Energy (kcal)", fontsize=9)
            ax.set_xlabel("Energy (kcal)", fontsize=7)
            ax.set_ylabel("Frekuensi", fontsize=7)
            ax.tick_params(labelsize=6)
            # TAMPILKAN DENGAN UKURAN TERKONTROL
            st.pyplot(fig, use_container_width=False)

# =========================
# 3. ANALISIS TEKS - DIPERKECIL
# =========================
elif page == "📝 Analisis Teks":
    st.header("📝 Analisis Teks")

    # Gunakan container untuk batas lebar
    with st.container():
        df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
        df_text['text_lower'] = df_text['Food_Text'].str.lower()

        st.subheader("☁️ Word Cloud")

        label_option = st.selectbox(
            "Pilih Label:",
            ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat'],
            key="wordcloud_label"
        )

        if label_option == 'Semua':
            text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
        else:
            text_data = " ".join(
                df_text[df_text['Label_Kesehatan'] == label_option]
                ['Food_Text'].dropna().astype(str)
            )

        if text_data.strip():
            # WORLCLOUD LEBIH KECIL
            fig, ax = plt.subplots(figsize=(4, 2))  # DIPERKECIL
            wc = WordCloud(
                background_color="white",
                width=300,
                height=150,
                max_words=30
            ).generate(text_data)
            ax.imshow(wc, interpolation='bilinear')
            ax.axis("off")
            ax.set_title(f"Word Cloud - {label_option}", fontsize=9)
            # TAMPILKAN DENGAN UKURAN TERKONTROL
            st.pyplot(fig, use_container_width=False)

            # Informasi tambahan
            word_count = len(text_data.split())
            st.info(f"**Jumlah kata dalam Word Cloud:** {word_count:,} kata")
        else:
            st.warning("Tidak ada data teks untuk ditampilkan")

# =========================
# 4. TOP 10 MAKANAN - DIPERKECIL
# =========================
elif page == "🏆 Top 10 Makanan":
    st.header("🏆 Top 10 Makanan")

    # Gunakan container untuk batas lebar
    with st.container():
        nutrient_options = {
            "Protein (g)": "Protein_g",
            "Lemak (g)": "Fat_g",
            "Gula (g)": "Sugar_g",
            "Natrium (mg)": "Sodium_mg",
            "Energi (kcal)": "Energy_kcal",
            "Karbohidrat (g)": "Carbohydrate_g"
        }

        selected_nutrient = st.selectbox(
            "Pilih Kandungan Nutrisi:",
            list(nutrient_options.keys())
        )

        col_name = nutrient_options[selected_nutrient]

        n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 20, 10, key="top_n")

        top_foods = (
            df.sort_values(col_name, ascending=False)
            .head(n_top)
        )

        # GRAFIK LEBIH KECIL
        fig, ax = plt.subplots(figsize=(5, 3))  # DIPERKECIL
        bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
        ax.set_xlabel(selected_nutrient, fontsize=7)
        ax.set_title(f"Top {n_top} Makanan {selected_nutrient} Tertinggi", fontsize=9)
        ax.invert_yaxis()
        ax.tick_params(labelsize=6)

        for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
            if label == "Sehat":
                bar.set_color('green')
            elif label == "Cukup Sehat":
                bar.set_color('orange')
            else:
                bar.set_color('red')

        import matplotlib.patches as mpatches
        healthy_patch = mpatches.Patch(color='green', label='Sehat')
        moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
        unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
        ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch],
                  fontsize=6, loc='lower right')

        # TAMPILKAN DENGAN UKURAN TERKONTROL
        st.pyplot(fig, use_container_width=False)

        st.subheader("Data Detail")
        display_cols = ['Food_Name', 'Label_Kesehatan', col_name, 'Food_Text']
        st.dataframe(top_foods[display_cols], use_container_width=True,
                    height=250, hide_index=True)  # DIPERKECIL

# =========================
# 5. ANALISIS MULTI-DIMENSI - DIPERKECIL
# =========================
elif page == "🎯 Analisis Multi-Dimensi":
    st.header("🎯 Analisis Multi-Dimensi")

    # Gunakan container untuk batas lebar
    with st.container():
        st.subheader("🔍 Insight Pola Nutrisi")

        categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']
        nutrients = ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg', 'Energy_kcal']
        nutrient_names = ['Protein', 'Lemak', 'Gula', 'Natrium', 'Energi']
        units = ['g', 'g', 'g', 'mg', 'kcal']

        for idx, category in enumerate(categories):
            with st.expander(f"**{category.upper()}**", expanded=(idx==0)):
                subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]

                # Metrik utama - lebih kompak
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Jumlah Makanan", f"{len(subset)}")
                with col2:
                    top_protein = subset.nlargest(1, 'Protein_g')
                    if not top_protein.empty:
                        st.metric("Protein Tertinggi",
                                 f"{top_protein['Protein_g'].values[0]:.1f}g")
                with col3:
                    top_sugar = subset.nlargest(1, 'Sugar_g')
                    if not top_sugar.empty:
                        st.metric("Gula Tertinggi",
                                 f"{top_sugar['Sugar_g'].values[0]:.1f}g")

                # Rata-rata nutrisi dalam dataframe kecil
                avg_values = []
                for nutrient, name, unit in zip(nutrients, nutrient_names, units):
                    avg_val = subset[nutrient].mean()
                    avg_values.append({
                        'Nutrisi': name,
                        'Rata_Rata': avg_val,
                        'Unit': unit
                    })

                avg_df = pd.DataFrame(avg_values)
                avg_df = avg_df.sort_values('Rata_Rata', ascending=False)

                # Tampilkan dalam dataframe kecil
                st.dataframe(
                    avg_df.round(2),
                    use_container_width=True,
                    height=200,
                    hide_index=True
                )

        st.divider()

        # Perbandingan antar kategori
        st.subheader("📈 Perbandingan Antar Kategori")

        selected_nutrient = st.selectbox(
            "Pilih Nutrisi untuk Perbandingan:",
            nutrient_names,
            key="compare_nutrient"
        )

        nutrient_map = dict(zip(nutrient_names, nutrients))
        selected_col = nutrient_map[selected_nutrient]

        comparison_data = []
        for category in categories:
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
            avg_val = subset[selected_col].mean()
            comparison_data.append({
                'Kategori': category,
                'Rata_rata': avg_val
            })

        comparison_df = pd.DataFrame(comparison_data)

        # Plot perbandingan - LEBIH KECIL
        fig, ax = plt.subplots(figsize=(4, 2))  # DIPERKECIL
        colors = ['green', 'orange', 'red']
        bars = ax.bar(comparison_df['Kategori'], comparison_df['Rata_rata'], color=colors)

        ax.set_title(f'Perbandingan {selected_nutrient}', fontsize=9)
        ax.set_ylabel(f'Rata-rata {selected_nutrient}', fontsize=7)
        ax.tick_params(labelsize=6)

        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
                   f'{height:.1f}', ha='center', va='bottom', fontsize=6)

        # TAMPILKAN DENGAN UKURAN TERKONTROL
        st.pyplot(fig, use_container_width=False)

# =========================
# 6. WORD CLOUD BERDASARKAN LEVEL PROTEIN - DIPERKECIL
# =========================
elif page == "☁️ Word Cloud Protein":
    st.header("☁️ Word Cloud Berdasarkan Level Protein")

    # Gunakan container untuk batas lebar
    with st.container():
        # Preprocessing teks untuk word cloud
        df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
        df_text['text_lower'] = df_text['Food_Text'].str.lower()
        df_text['tokens'] = df_text['text_lower'].str.split()

        custom_stopwords = {'and', 'or', 'with', 'of', 'the'}
        df_text['tokens_clean'] = df_text['tokens'].apply(
            lambda x: [word for word in x if word not in custom_stopwords]
        )
        df_text['clean_text'] = df_text['tokens_clean'].apply(lambda x: ' '.join(x))

        # Bagi makanan berdasarkan kuartil protein
        protein_quartiles = pd.qcut(df_preprocessed_numeric['Protein_g'], 4,
                                    labels=['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi'])

        st.subheader("Word Cloud berdasarkan Kuartil Protein")

        # Gunakan layout 2x2 yang lebih kecil
        cols = st.columns(2)

        for idx, quartile in enumerate(['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi']):
            with cols[idx % 2]:
                st.markdown(f"**{quartile}**")

                # Ambil indeks untuk kuartil ini
                idx_quartile = protein_quartiles[protein_quartiles == quartile].index

                # Ambil clean_text untuk makanan di kuartil ini
                quartile_texts = df_text.loc[idx_quartile, 'clean_text'].dropna()

                if len(quartile_texts) > 0:
                    all_text = ' '.join(quartile_texts.astype(str))

                    if len(all_text.strip()) > 0:
                        # WordCloud yang lebih kecil
                        wc = WordCloud(
                            width=200,
                            height=120,
                            background_color='white',
                            colormap='viridis',
                            max_words=15,
                            min_font_size=6,
                            max_font_size=20,
                            random_state=42
                        ).generate(all_text)

                        # Figure yang lebih kecil
                        fig, ax = plt.subplots(figsize=(3, 1.8))
                        ax.imshow(wc, interpolation='bilinear')
                        ax.axis("off")

                        # TAMPILKAN DENGAN UKURAN TERKONTROL
                        st.pyplot(fig, use_container_width=False)

                        # Info statistik
                        mean_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].mean()
                        st.caption(f"Rata-rata: {mean_protein:.1f}g | {len(quartile_texts)} makanan")

                    else:
                        st.info("Tidak ada data teks")
                else:
                    st.info("Tidak ada data")

        # Statistik ringkas
        st.divider()
        st.subheader("📊 Statistik Ringkas")

        quartile_stats = []
        for quartile in ['Sangat Rendah', 'Rendah', 'Tinggi', 'Sangat Tinggi']:
            idx_quartile = protein_quartiles[protein_quartiles == quartile].index
            if len(idx_quartile) > 0:
                mean_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].mean()
                min_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].min()
                max_protein = df_preprocessed_numeric.loc[idx_quartile, 'Protein_g'].max()
                count = len(idx_quartile)

                quartile_stats.append({
                    'Kuartil': quartile,
                    'Jml Makanan': count,
                    'Rata2 (g)': f"{mean_protein:.1f}",
                    'Min (g)': f"{min_protein:.1f}",
                    'Max (g)': f"{max_protein:.1f}"
                })

        stats_df = pd.DataFrame(quartile_stats)
        st.dataframe(stats_df, use_container_width=True, height=120)

# =========================
# 7. SCATTER PLOT - DIPERKECIL
# =========================
elif page == "📈 Scatter Plot":
    st.header("📈 Scatter Plot Analisis Hubungan Nutrisi")

    # Gunakan container untuk batas lebar
    with st.container():
        col1, col2 = st.columns(2)

        with col1:
            x_axis = st.selectbox(
                "Pilih sumbu X:",
                ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
                index=3
            )

        with col2:
            y_axis = st.selectbox(
                "Pilih sumbu Y:",
                ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
                index=0
            )

        # Scatter plot dengan ukuran yang lebih kompak
        fig, ax = plt.subplots(figsize=(4, 2.5))  # DIPERKECIL

        # Hitung korelasi terlebih dahulu
        correlation = df_preprocessed_numeric[x_axis].corr(df_preprocessed_numeric[y_axis])

        scatter = sns.scatterplot(
            data=df_preprocessed_numeric,
            x=x_axis,
            y=y_axis,
            hue='Label_Kesehatan',
            palette={'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'},
            alpha=0.7,
            s=20,  # DIPERKECIL
            ax=ax,
            legend='brief'
        )

        # Format visual yang minimalis
        ax.set_title(f'Hubungan {x_axis} dan {y_axis}', fontsize=9, pad=3)
        ax.set_xlabel(x_axis.replace('_', ' '), fontsize=7, labelpad=1)
        ax.set_ylabel(y_axis.replace('_', ' '), fontsize=7, labelpad=1)
        ax.tick_params(labelsize=6)
        ax.grid(True, alpha=0.2, linewidth=0.5)

        # Legend yang lebih kecil
        ax.legend(title='Label Kesehatan',
                 fontsize=6,
                 title_fontsize=7,
                 loc='upper left' if correlation > 0 else 'upper right',
                 frameon=True,
                 framealpha=0.8)

        # TAMPILKAN DENGAN UKURAN TERKONTROL
        st.pyplot(fig, use_container_width=False)

        # Analisis korelasi dalam layout yang kompak
        st.divider()

        # Tampilkan metrik dalam baris yang kompak
        st.subheader("Analisis Korelasi")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("Koefisien Korelasi",
                     f"{correlation:.3f}",
                     help="Nilai antara -1 sampai 1")

        with col2:
            if abs(correlation) > 0.7:
                strength = "Kuat"
            elif abs(correlation) > 0.3:
                strength = "Sedang"
            else:
                strength = "Lemah"
            st.metric("Kekuatan", strength)

        with col3:
            direction = "Positif" if correlation > 0 else "Negatif"
            st.metric("Arah", direction)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray; font-size: 0.8em;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv
    </div>
    """,
    unsafe_allow_html=True
)