# -*- coding: utf-8 -*-
"""datvis_uas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2Bi9I66Xo6QURGk8zis3ZxWDfIhRXB-
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
from wordcloud import WordCloud

st.set_page_config(page_title="Datvis UAS", layout="wide")
st.title("Dashboard Analisis Nutrisi & Teks Makanan")

# =====================================================
# 1. LOAD DATA
# =====================================================
df = pd.read_csv("dataset_nutrisi_text_300.csv")
df.columns = df.columns.str.strip()

st.header("Dataset Awal")
st.dataframe(df.head())

# =====================================================
# 2. PREPROCESSING NUMERIK
# =====================================================
numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']

for col in numeric_cols:
    df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

df_numeric = df[numeric_cols].copy()
for col in numeric_cols:
    df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

scaler = StandardScaler()
df_scaled = pd.DataFrame(
    scaler.fit_transform(df_numeric),
    columns=[f"{c}_scaled" for c in numeric_cols]
)

# =====================================================
# 3. PREPROCESSING TEKS
# =====================================================
df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
df_text['clean_text'] = df_text['Food_Text'].astype(str).str.lower()

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df_text['clean_text'])
tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

y = df_text['Label_Kesehatan'].map({'Sehat': 1, 'Tidak Sehat': 0})
mi_scores = mutual_info_classif(tfidf_df, y)

mi_df = pd.DataFrame({
    "Fitur": tfidf_df.columns,
    "Information Gain": mi_scores
}).sort_values(by="Information Gain", ascending=False)

# =====================================================
# VISUALISASI 1 — RATA-RATA PROTEIN
# =====================================================
st.header("Rata-rata Kandungan Protein pada Berbagai Jenis Makanan")

fig, ax = plt.subplots(figsize=(8,5))
avg_protein = df.groupby("Food_Name")["Protein_g"].mean()
avg_protein.plot(kind="bar", ax=ax)
ax.set_title("Rata-rata Kandungan Protein pada Berbagai Jenis Makanan")
ax.set_xlabel("Kategori Makanan")
ax.set_ylabel("Protein (gram)")
st.pyplot(fig)

# =====================================================
# VISUALISASI 2 — GULA & NATRIUM
# =====================================================
st.header("Perbandingan Rata-rata Gula dan Natrium")

fig, ax = plt.subplots(figsize=(8,5))
avg_sugar_sodium = df.groupby("Label_Kesehatan")[["Sugar_g", "Sodium_mg"]].mean()
avg_sugar_sodium.plot(kind="bar", ax=ax)
ax.set_title("Perbandingan Rata-rata Gula dan Natrium")
st.pyplot(fig)

# =====================================================
# VISUALISASI 3 — GULA & NATRIUM (ULANG)
# =====================================================
fig, ax = plt.subplots(figsize=(8,5))
avg_sugar_sodium.plot(kind="bar", ax=ax)
ax.set_title("Perbandingan Rata-rata Gula dan Natrium")
st.pyplot(fig)

# =====================================================
# VISUALISASI 4 — SCATTER PROTEIN vs LEMAK
# =====================================================
st.header("Hubungan Kandungan Protein dan Lemak")

fig, ax = plt.subplots(figsize=(7,5))
sns.scatterplot(data=df, x="Protein_g", y="Fat_g", hue="Label_Kesehatan", ax=ax)
st.pyplot(fig)

# =====================================================
# VISUALISASI 5 — HISTOGRAM ENERGI
# =====================================================
st.header("Distribusi Energi (Kalori)")

fig, ax = plt.subplots(figsize=(7,5))
ax.hist(df["Energy_kcal"], bins=20)
st.pyplot(fig)

# =====================================================
# VISUALISASI 6 — WORDCLOUD
# =====================================================
st.header("Word Cloud")

col1, col2 = st.columns(2)

with col1:
    wc = WordCloud(background_color="white").generate(
        " ".join(df[df["Label_Kesehatan"]=="Sehat"]["Food_Text"].astype(str))
    )
    fig, ax = plt.subplots()
    ax.imshow(wc)
    ax.axis("off")
    ax.set_title("Makanan Sehat")
    st.pyplot(fig)

with col2:
    wc = WordCloud(background_color="white").generate(
        " ".join(df[df["Label_Kesehatan"]=="Tidak Sehat"]["Food_Text"].astype(str))
    )
    fig, ax = plt.subplots()
    ax.imshow(wc)
    ax.axis("off")
    ax.set_title("Makanan Tidak Sehat")
    st.pyplot(fig)

# =====================================================
# VISUALISASI 7 — INFORMATION GAIN
# =====================================================
st.header("Fitur Teks Paling Berpengaruh (Information Gain)")

fig, ax = plt.subplots(figsize=(8,5))
sns.barplot(data=mi_df.head(20), x="Information Gain", y="Fitur", ax=ax)
st.pyplot(fig)

# =====================================================
# VISUALISASI 8 — KORELASI GIZI
# =====================================================
st.header("Korelasi Antar Kandungan Gizi")

nutrisi = df[["Protein_g","Fat_g","Sugar_g","Sodium_mg","Energy_kcal"]]
corr = nutrisi.corr()

fig, ax = plt.subplots(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", ax=ax)
st.pyplot(fig)

# =====================================================
# VISUALISASI 9 — INTEGRASI GIZI & TEKS
# =====================================================
st.header("Integrasi Analisis Gizi & Teks")

fig, axes = plt.subplots(1,2, figsize=(14,5))

sns.scatterplot(
    data=df,
    x="Protein_g",
    y="Fat_g",
    hue="Label_Kesehatan",
    ax=axes[0]
)

sns.barplot(
    data=mi_df.head(10),
    x="Information Gain",
    y="Fitur",
    ax=axes[1]
)

st.pyplot(fig)