# -*- coding: utf-8 -*-
"""Datvis benar 00

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oo_fHrKdxc8K-HtHlxhMiz3xM69v1msn
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="centered",
    initial_sidebar_state="expanded"
)

# =========================
# GLOBAL VISUAL CONFIG
# =========================
VIS_SCALE = 0.5

mpl.rcParams.update({
    "figure.figsize": (8 * VIS_SCALE, 4 * VIS_SCALE),
    "axes.titlesize": 12 * VIS_SCALE,
    "axes.labelsize": 10 * VIS_SCALE,
    "xtick.labelsize": 9 * VIS_SCALE,
    "ytick.labelsize": 9 * VIS_SCALE,
    "legend.fontsize": 9 * VIS_SCALE,
    "font.size": 10 * VIS_SCALE,
    "lines.linewidth": 1.5 * VIS_SCALE,
    "lines.markersize": 6 * VIS_SCALE,
})

sns.set_context("paper", font_scale=VIS_SCALE)

st.title("Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan', 'Food_Text']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped

df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi",
        "Scatter Plot"
    ]
)

# =========================
# 1. OVERVIEW DATA
# =========================
if page == "Overview Data":
    st.header("Overview Data")

    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "Metrik Utama", "Data Sample", "Distribusi",
        "Missing Values", "Informasi Dataset"
    ])

    with tab1:
        st.subheader("Metrik Utama Dataset")

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            total_data = len(df)
            st.metric("Total Data", f"{total_data:,}")
        with col2:
            total_cols = len(df.columns)
            st.metric("Total Kolom", total_cols)
        with col3:
            missing_total = df.isnull().sum().sum()
            st.metric("Missing Values", f"{missing_total:,}")
        with col4:
            sehat_count = len(df[df['Label_Kesehatan'] == 'Sehat'])
            st.metric("Makanan Sehat", f"{sehat_count:,}")

        col5, col6, col7, col8 = st.columns(4)
        with col5:
            cukup_sehat = len(df[df['Label_Kesehatan'] == 'Cukup Sehat'])
            st.metric("Cukup Sehat", f"{cukup_sehat:,}")
        with col6:
            kurang_sehat = len(df[df['Label_Kesehatan'] == 'Kurang Sehat'])
            st.metric("Kurang Sehat", f"{kurang_sehat:,}")
        with col7:
            unique_foods = df['Food_Name'].nunique()
            st.metric("Makanan Unik", f"{unique_foods:,}")
        with col8:
            avg_energy = df['Energy_kcal'].mean()
            st.metric("Rata-rata Energi", f"{avg_energy:.0f} kcal")

        st.divider()
        st.subheader("Statistik Numerik Ringkas")
        numeric_stats = df.select_dtypes(include=[np.number]).describe().T
        numeric_stats = numeric_stats[['mean', 'std', 'min', '50%', 'max']]
        numeric_stats.columns = ['Rata-rata', 'Std Dev', 'Minimum', 'Median', 'Maksimum']
        st.dataframe(numeric_stats.round(2), use_container_width=True, height=200, hide_index=True)

    with tab2:
        st.subheader("Data Sample Dataset")

        col_control1, col_control2 = st.columns(2)
        with col_control1:
            num_rows = st.slider("Jumlah baris:", 5, 50, 10, key="sample_rows")
        with col_control2:
            show_all_cols = st.checkbox("Tampilkan semua kolom", value=False, key="show_all")

        if not show_all_cols:
            default_cols = ['Food_Name', 'Label_Kesehatan', 'Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g']
            selected_cols = st.multiselect("Pilih kolom:", df.columns.tolist(), default=default_cols, key="col_select")
            display_df = df[selected_cols] if selected_cols else df[default_cols]
        else:
            display_df = df

        st.dataframe(display_df.head(num_rows), use_container_width=True, height=350, hide_index=True)

    with tab3:
        st.subheader("Distribusi Data")

        st.markdown("#### Distribusi Label Kesehatan")
        counts = df['Label_Kesehatan'].value_counts()
        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}
        bar_colors = [colors.get(label, 'gray') for label in counts.index]

        chart_col, table_col = st.columns([2, 1])

        with chart_col:
            fig, ax = plt.subplots(figsize=(5, 3))
            bars = ax.bar(counts.index, counts.values, color=bar_colors)
            ax.set_title("Distribusi Label Kesehatan", fontsize=10)
            ax.set_xlabel("Label Kesehatan", fontsize=8)
            ax.set_ylabel("Jumlah", fontsize=8)
            ax.grid(axis='y', alpha=0.3)
            ax.tick_params(labelsize=7)

            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height,
                       f'{int(height):,}', ha='center', va='bottom', fontsize=8)

            st.pyplot(fig, use_container_width=False)

        with table_col:
            distribusi_df = pd.DataFrame({
                'Label': counts.index,
                'Jumlah': counts.values,
                'Persentase': (counts.values / len(df) * 100).round(1)
            })
            st.dataframe(distribusi_df, use_container_width=True, height=150, hide_index=True)

        st.divider()
        st.markdown("#### Distribusi Kolom Numerik")

        numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
        selected_numeric = st.selectbox("Pilih kolom numerik:", numeric_cols, key="dist_numeric")

        if selected_numeric in df.columns:
            fig2, ax2 = plt.subplots(figsize=(5, 3))
            ax2.hist(df[selected_numeric].dropna(), bins=20, edgecolor='black', alpha=0.7)
            ax2.set_title(f"Distribusi {selected_numeric}", fontsize=10)
            ax2.set_xlabel(selected_numeric, fontsize=8)
            ax2.set_ylabel("Frekuensi", fontsize=8)
            ax2.grid(alpha=0.3)
            ax2.tick_params(labelsize=7)

            mean_val = df[selected_numeric].mean()
            median_val = df[selected_numeric].median()
            ax2.axvline(mean_val, color='red', linestyle='--', label=f'Mean: {mean_val:.1f}', linewidth=1)
            ax2.axvline(median_val, color='green', linestyle='--', label=f'Median: {median_val:.1f}', linewidth=1)
            ax2.legend(fontsize=7)

            st.pyplot(fig2, use_container_width=False)

            col_stats = df[selected_numeric].describe()
            st.dataframe(
                pd.DataFrame({
                    'Statistik': col_stats.index,
                    'Nilai': col_stats.values.round(2)
                }),
                use_container_width=True,
                height=250,
                hide_index=True
            )

    with tab4:
        st.subheader("Analisis Missing Values")

        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum(),
            'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
        }).sort_values('Missing Values', ascending=False)

        missing_filtered = missing_data[missing_data['Missing Values'] > 0]

        if len(missing_filtered) > 0:
            st.warning(f"Ditemukan {len(missing_filtered)} kolom dengan missing values")
            st.dataframe(missing_filtered, use_container_width=True, height=250, hide_index=True)

            st.markdown("#### Visualisasi Missing Values")
            fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 3))

            missing_bars = missing_filtered.set_index('Kolom')['Missing Values']
            missing_bars.plot(kind='bar', ax=ax1, color='coral')
            ax1.set_title("Missing Values per Kolom", fontsize=9)
            ax1.set_ylabel("Jumlah Missing", fontsize=7)
            ax1.tick_params(axis='x', rotation=45, labelsize=6)
            ax1.tick_params(axis='y', labelsize=6)
            ax1.grid(axis='y', alpha=0.3)

            total_missing = missing_filtered['Missing Values'].sum()
            total_cells = len(df) * len(df.columns)
            present_cells = total_cells - total_missing

            sizes = [present_cells, total_missing]
            labels = ['Data Valid', 'Missing']
            colors_pie = ['lightgreen', 'coral']

            ax2.pie(sizes, labels=labels, colors=colors_pie, autopct='%1.1f%%',
                   startangle=90, explode=(0.1, 0))
            ax2.set_title(f"Persentase Missing Values", fontsize=9)

            plt.tight_layout()
            st.pyplot(fig, use_container_width=False)
        else:
            st.success("Tidak ada missing values pada dataset")

    with tab5:
        st.subheader("Informasi Dataset")

        st.markdown("#### Informasi Umum")
        info_data = {
            'Attribute': ['Nama File', 'Total Baris', 'Total Kolom', 'Tipe Data', 'Ukuran Memori'],
            'Value': ['nilai_gizi.csv', f"{len(df):,}", f"{len(df.columns)}",
                     'CSV', f"{df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB"]
        }
        info_df = pd.DataFrame(info_data)
        st.dataframe(info_df, use_container_width=True, height=200, hide_index=True)

        st.divider()
        st.markdown("#### Daftar Kolom Dataset")

        col_info = []
        for col in df.columns:
            dtype = str(df[col].dtype)
            non_null = df[col].count()
            unique = df[col].nunique()
            sample = str(df[col].iloc[0])[:20] + "..." if len(str(df[col].iloc[0])) > 20 else str(df[col].iloc[0])

            col_info.append({
                'Kolom': col,
                'Tipe Data': dtype,
                'Non-Null': non_null,
                'Unique': unique,
                'Contoh Nilai': sample
            })

        col_info_df = pd.DataFrame(col_info)
        st.dataframe(col_info_df, use_container_width=True, height=350, hide_index=True)

# =========================
# 2. ANALISIS NUMERIK
# =========================
elif page == "Analisis Numerik":
    st.header("Analisis Numerik")

    tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
        "Distribusi", "Perbandingan", "Korelasi",
        "Histogram Energy", "Distribusi Energy Preprocessing", "Nilai Maksimum"
    ])

    with tab1:
        avg_nutrisi = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

        fig, axes = plt.subplots(2, 2, figsize=(7, 4))
        nutrients = [
            ('Protein_g', 'Protein (g)'),
            ('Fat_g', 'Lemak (g)'),
            ('Sugar_g', 'Gula (g)'),
            ('Sodium_mg', 'Natrium (mg)')
        ]

        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for idx, (col, title) in enumerate(nutrients):
            ax = axes[idx // 2, idx % 2]
            values = avg_nutrisi[col]
            bars = ax.bar(
                values.index,
                values.values,
                color=[colors[label] for label in values.index]
            )
            ax.set_title(f'Rata-rata {title}', fontsize=8)
            ax.tick_params(axis='x', rotation=45, labelsize=6)
            ax.tick_params(axis='y', labelsize=6)

            for bar in bars:
                h = bar.get_height()
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    h,
                    f"{h:.1f}",
                    ha='center',
                    va='bottom',
                    fontsize=6
                )

        plt.tight_layout()
        st.pyplot(fig, use_container_width=False)

    with tab2:
        avg = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Sugar_g', 'Sodium_mg']].mean()

        fig, ax = plt.subplots(figsize=(5, 3))
        avg.plot(kind='bar', ax=ax)
        ax.set_title("Perbandingan Gula & Natrium", fontsize=9)
        ax.tick_params(axis='x', rotation=45, labelsize=7)
        ax.tick_params(axis='y', labelsize=7)
        ax.legend(fontsize=7)
        st.pyplot(fig, use_container_width=False)

    with tab3:
        corr = df_preprocessed_numeric[
            ['Energy_kcal', 'Protein_g', 'Fat_g',
             'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
        ].corr()

        fig, ax = plt.subplots(figsize=(5, 3))
        sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax, fmt='.2f',
                   annot_kws={"size": 6}, cbar_kws={"shrink": 0.7})
        ax.set_title("Heatmap Korelasi", fontsize=9)
        st.pyplot(fig, use_container_width=False)

    with tab4:
        # Distribusi Energy diperkecil 2/3 dari ukuran asli
        fig, ax = plt.subplots(figsize=(3.3, 2))  # (7*0.47, 3*0.67) ≈ (3.3, 2)
        ax.hist(df_numeric_capped["Energy_kcal"], bins=15, edgecolor='black')
        ax.set_title("Distribusi Energy (kcal)", fontsize=9)
        ax.set_xlabel("Energy (kcal)", fontsize=7)
        ax.set_ylabel("Frekuensi", fontsize=7)
        ax.tick_params(labelsize=6)
        st.pyplot(fig, use_container_width=False)

    with tab5:
        st.subheader("Distribusi Energi (Kalori) Makanan (Data Setelah Preprocessing)")

        fig, ax = plt.subplots(figsize=(7, 5))
        ax.hist(df_numeric_capped["Energy_kcal"], bins=20, edgecolor='black', alpha=0.7)
        ax.set_title("Distribusi Energi (Kalori) Makanan (Data Setelah Preprocessing)", fontsize=12)
        ax.set_xlabel("Energi (kcal)", fontsize=10)
        ax.set_ylabel("Frekuensi", fontsize=10)
        ax.grid(True, alpha=0.3)
        ax.tick_params(labelsize=9)

        st.pyplot(fig, use_container_width=False)

        st.info("""
        **Interpretasi:**
        Histogram ini menunjukkan distribusi energi (kalori) dari makanan setelah preprocessing data.
        Preprocessing termasuk penanganan missing values, outlier, dan scaling data.
        """)

    with tab6:
        st.subheader("Nilai Maksimum Kandungan Nutrisi")

        max_values = {
            "Lemak (g)": df["Fat_g"].max(),
            "Gula (g)": df["Sugar_g"].max(),
            "Protein (g)": df["Protein_g"].max(),
            "Natrium (mg)": df["Sodium_mg"].max(),
            "Energi (kcal)": df["Energy_kcal"].max(),
            "Karbohidrat (g)": df["Carbohydrate_g"].max()
        }

        fig, ax = plt.subplots(figsize=(7, 5))
        bars = ax.bar(max_values.keys(), max_values.values())
        ax.set_title("Nilai Maksimum Kandungan Nutrisi", fontsize=12)
        ax.set_ylabel("Nilai", fontsize=10)
        ax.tick_params(axis='x', rotation=45, labelsize=9)
        ax.tick_params(axis='y', labelsize=9)
        ax.grid(True, alpha=0.3, axis='y')

        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height + 5,
                   f'{height:.1f}', ha='center', va='bottom', fontsize=10)

        st.pyplot(fig, use_container_width=False)

        # Tampilkan nilai maksimum dalam tabel
        max_df = pd.DataFrame({
            'Nutrisi': list(max_values.keys()),
            'Nilai Maksimum': list(max_values.values()),
            'Unit': ['g', 'g', 'g', 'mg', 'kcal', 'g']
        })
        st.dataframe(max_df, use_container_width=True, height=200, hide_index=True)

# =========================
# 3. ANALISIS TEKS
# =========================
elif page == "Analisis Teks":
    st.header("Analisis Teks")

    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    st.subheader("Word Cloud")

    label_option = st.selectbox(
        "Pilih Label:",
        ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat'],
        key="wordcloud_label"
    )

    if label_option == 'Semua':
        text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
    else:
        text_data = " ".join(
            df_text[df_text['Label_Kesehatan'] == label_option]
            ['Food_Text'].dropna().astype(str)
        )

    if text_data.strip():
        fig, ax = plt.subplots(figsize=(4, 2))
        wc = WordCloud(
            background_color="white",
            width=300,
            height=150,
            max_words=30
        ).generate(text_data)
        ax.imshow(wc, interpolation='bilinear')
        ax.axis("off")
        ax.set_title(f"Word Cloud - {label_option}", fontsize=9)
        st.pyplot(fig, use_container_width=False)

        word_count = len(text_data.split())
        st.info(f"Jumlah kata dalam Word Cloud: {word_count:,} kata")
    else:
        st.warning("Tidak ada data teks untuk ditampilkan")

# =========================
# 4. TOP 10 MAKANAN
# =========================
elif page == "Top 10 Makanan":
    st.header("Top 10 Makanan")

    tab1, tab2 = st.tabs(["Top 10 per Nutrisi", "Top 10 per Kategori"])

    with tab1:
        nutrient_options = {
            "Protein (g)": "Protein_g",
            "Lemak (g)": "Fat_g",
            "Gula (g)": "Sugar_g",
            "Natrium (mg)": "Sodium_mg",
            "Energi (kcal)": "Energy_kcal",
            "Karbohidrat (g)": "Carbohydrate_g"
        }

        selected_nutrient = st.selectbox(
            "Pilih Kandungan Nutrisi:",
            list(nutrient_options.keys())
        )

        col_name = nutrient_options[selected_nutrient]

        n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 20, 10, key="top_n")

        top_foods = (
            df.sort_values(col_name, ascending=False)
            .head(n_top)
        )

        fig, ax = plt.subplots(figsize=(5, 3))
        bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
        ax.set_xlabel(selected_nutrient, fontsize=7)
        ax.set_title(f"Top {n_top} Makanan {selected_nutrient} Tertinggi", fontsize=9)
        ax.invert_yaxis()
        ax.tick_params(labelsize=6)

        for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
            if label == "Sehat":
                bar.set_color('green')
            elif label == "Cukup Sehat":
                bar.set_color('orange')
            else:
                bar.set_color('red')

        import matplotlib.patches as mpatches
        healthy_patch = mpatches.Patch(color='green', label='Sehat')
        moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
        unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
        ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch],
                  fontsize=6, loc='lower right')

        st.pyplot(fig, use_container_width=False)

        st.subheader("Data Detail")
        display_cols = ['Food_Name', 'Label_Kesehatan', col_name, 'Food_Text']
        st.dataframe(top_foods[display_cols], use_container_width=True,
                    height=250, hide_index=True)

    with tab2:
        st.subheader("Top 10 Makanan Berdasarkan Data yang Sudah Dipreprocessing")

        st.write("Analisis Top 10 makanan berdasarkan kategori kesehatan dan jenis nutrisi:")

        # Gunakan df_preprocessed_numeric untuk konsistensi
        fig, axes = plt.subplots(3, 2, figsize=(10, 12))

        # Protein - Sehat
        sehat_high_protein = (
            df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == 'Sehat']
            .sort_values('Protein_g', ascending=False)
            .head(10)
        )

        axes[0, 0].barh(range(len(sehat_high_protein)), sehat_high_protein['Protein_g'],
                       color='green', alpha=0.7)
        axes[0, 0].set_yticks(range(len(sehat_high_protein)))
        axes[0, 0].set_yticklabels([f"{name[:18]}..." if len(name) > 20 else name
                                  for name in sehat_high_protein['Food_Name']], fontsize=8)
        axes[0, 0].set_xlabel('Protein (g)', fontsize=9)
        axes[0, 0].set_title('TOP 10 PROTEIN - MAKANAN SEHAT', fontsize=10, fontweight='bold')
        axes[0, 0].invert_yaxis()
        axes[0, 0].grid(True, alpha=0.3, axis='x')

        # Gula - Kurang Sehat
        kurang_sehat_high_sugar = (
            df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == 'Kurang Sehat']
            .sort_values('Sugar_g', ascending=False)
            .head(10)
        )

        axes[0, 1].barh(range(len(kurang_sehat_high_sugar)), kurang_sehat_high_sugar['Sugar_g'],
                       color='red', alpha=0.7)
        axes[0, 1].set_yticks(range(len(kurang_sehat_high_sugar)))
        axes[0, 1].set_yticklabels([f"{name[:18]}..." if len(name) > 20 else name
                                  for name in kurang_sehat_high_sugar['Food_Name']], fontsize=8)
        axes[0, 1].set_xlabel('Gula (g)', fontsize=9)
        axes[0, 1].set_title('TOP 10 GULA - MAKANAN KURANG SEHAT', fontsize=10, fontweight='bold')
        axes[0, 1].invert_yaxis()
        axes[0, 1].grid(True, alpha=0.3, axis='x')

        # Lemak - Cukup Sehat
        cukup_sehat_high_fat = (
            df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == 'Cukup Sehat']
            .sort_values('Fat_g', ascending=False)
            .head(10)
        )

        axes[1, 0].barh(range(len(cukup_sehat_high_fat)), cukup_sehat_high_fat['Fat_g'],
                       color='orange', alpha=0.7)
        axes[1, 0].set_yticks(range(len(cukup_sehat_high_fat)))
        axes[1, 0].set_yticklabels([f"{name[:18]}..." if len(name) > 20 else name
                                  for name in cukup_sehat_high_fat['Food_Name']], fontsize=8)
        axes[1, 0].set_xlabel('Lemak (g)', fontsize=9)
        axes[1, 0].set_title('TOP 10 LEMAK - MAKANAN CUKUP SEHAT', fontsize=10, fontweight='bold')
        axes[1, 0].invert_yaxis()
        axes[1, 0].grid(True, alpha=0.3, axis='x')

        # Karbohidrat - Sehat
        sehat_high_carbo = (
            df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == 'Sehat']
            .sort_values('Carbohydrate_g', ascending=False)
            .head(10)
        )

        axes[1, 1].barh(range(len(sehat_high_carbo)), sehat_high_carbo['Carbohydrate_g'],
                       color='green', alpha=0.7)
        axes[1, 1].set_yticks(range(len(sehat_high_carbo)))
        axes[1, 1].set_yticklabels([f"{name[:18]}..." if len(name) > 20 else name
                                  for name in sehat_high_carbo['Food_Name']], fontsize=8)
        axes[1, 1].set_xlabel('Karbohidrat (g)', fontsize=9)
        axes[1, 1].set_title('TOP 10 KARBOHIDRAT - MAKANAN SEHAT', fontsize=10, fontweight='bold')
        axes[1, 1].invert_yaxis()
        axes[1, 1].grid(True, alpha=0.3, axis='x')

        # Energi - Kurang Sehat
        kurang_sehat_high_energy = (
            df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == 'Kurang Sehat']
            .sort_values('Energy_kcal', ascending=False)
            .head(10)
        )

        axes[2, 0].barh(range(len(kurang_sehat_high_energy)), kurang_sehat_high_energy['Energy_kcal'],
                       color='red', alpha=0.7)
        axes[2, 0].set_yticks(range(len(kurang_sehat_high_energy)))
        axes[2, 0].set_yticklabels([f"{name[:18]}..." if len(name) > 20 else name
                                  for name in kurang_sehat_high_energy['Food_Name']], fontsize=8)
        axes[2, 0].set_xlabel('Energi (kcal)', fontsize=9)
        axes[2, 0].set_title('TOP 10 ENERGI - MAKANAN KURANG SEHAT', fontsize=10, fontweight='bold')
        axes[2, 0].invert_yaxis()
        axes[2, 0].grid(True, alpha=0.3, axis='x')

        # Natrium - Kurang Sehat
        kurang_sehat_high_sodium = (
            df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == 'Kurang Sehat']
            .sort_values('Sodium_mg', ascending=False)
            .head(10)
        )

        axes[2, 1].barh(range(len(kurang_sehat_high_sodium)), kurang_sehat_high_sodium['Sodium_mg'],
                       color='red', alpha=0.7)
        axes[2, 1].set_yticks(range(len(kurang_sehat_high_sodium)))
        axes[2, 1].set_yticklabels([f"{name[:18]}..." if len(name) > 20 else name
                                  for name in kurang_sehat_high_sodium['Food_Name']], fontsize=8)
        axes[2, 1].set_xlabel('Natrium (mg)', fontsize=9)
        axes[2, 1].set_title('TOP 10 NATRIUM - MAKANAN KURANG SEHAT', fontsize=10, fontweight='bold')
        axes[2, 1].invert_yaxis()
        axes[2, 1].grid(True, alpha=0.3, axis='x')

        plt.suptitle('TOP 10 MAKANAN BERDASARKAN DATA YANG SUDAH DIPREPROCESSING',
                     fontsize=12, fontweight='bold', y=1.02)
        plt.tight_layout()
        st.pyplot(fig, use_container_width=False)

        st.info("""
        **Keterangan:**
        - **Hijau:** Makanan dengan label 'Sehat'
        - **Oranye:** Makanan dengan label 'Cukup Sehat'
        - **Merah:** Makanan dengan label 'Kurang Sehat'

        Visualisasi ini menunjukkan makanan dengan kandungan nutrisi tertinggi
        untuk setiap kategori kesehatan.
        """)

# =========================
# 5. ANALISIS MULTI-DIMENSI
# =========================
elif page == "Analisis Multi-Dimensi":
    st.header("Analisis Multi-Dimensi")

    st.subheader("Insight Pola Nutrisi")

    categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']
    nutrients = ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg', 'Energy_kcal']
    nutrient_names = ['Protein', 'Lemak', 'Gula', 'Natrium', 'Energi']
    units = ['g', 'g', 'g', 'mg', 'kcal']

    for idx, category in enumerate(categories):
        with st.expander(f"{category.upper()}", expanded=(idx==0)):
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]

            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Jumlah Makanan", f"{len(subset)}")
            with col2:
                top_protein = subset.nlargest(1, 'Protein_g')
                if not top_protein.empty:
                    st.metric("Protein Tertinggi",
                             f"{top_protein['Protein_g'].values[0]:.1f}g")
            with col3:
                top_sugar = subset.nlargest(1, 'Sugar_g')
                if not top_sugar.empty:
                    st.metric("Gula Tertinggi",
                             f"{top_sugar['Sugar_g'].values[0]:.1f}g")

            avg_values = []
            for nutrient, name, unit in zip(nutrients, nutrient_names, units):
                avg_val = subset[nutrient].mean()
                avg_values.append({
                    'Nutrisi': name,
                    'Rata_Rata': avg_val,
                    'Unit': unit
                })

            avg_df = pd.DataFrame(avg_values)
            avg_df = avg_df.sort_values('Rata_Rata', ascending=False)
            st.dataframe(avg_df.round(2), use_container_width=True, height=200, hide_index=True)

    st.divider()
    st.subheader("Perbandingan Antar Kategori")

    selected_nutrient = st.selectbox(
        "Pilih Nutrisi untuk Perbandingan:",
        nutrient_names,
        key="compare_nutrient"
    )

    nutrient_map = dict(zip(nutrient_names, nutrients))
    selected_col = nutrient_map[selected_nutrient]

    comparison_data = []
    for category in categories:
        subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
        avg_val = subset[selected_col].mean()
        comparison_data.append({
            'Kategori': category,
            'Rata_rata': avg_val
        })

    comparison_df = pd.DataFrame(comparison_data)

    # Grafik perbandingan diperkecil 2/3 dari ukuran asli
    fig, ax = plt.subplots(figsize=(4, 2))  # (6*0.67, 3*0.67) = (4, 2)
    colors = ['green', 'orange', 'red']
    bars = ax.bar(comparison_df['Kategori'], comparison_df['Rata_rata'], color=colors)

    ax.set_title(f'Perbandingan {selected_nutrient}', fontsize=9)
    ax.set_ylabel(f'Rata-rata {selected_nutrient}', fontsize=7)
    ax.tick_params(labelsize=6)

    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
               f'{height:.1f}', ha='center', va='bottom', fontsize=6)

    st.pyplot(fig, use_container_width=False)

# =========================
# 6. SCATTER PLOT
# =========================
elif page == "Scatter Plot":
    st.header("Scatter Plot Analisis Hubungan Nutrisi")

    col1, col2 = st.columns(2)

    with col1:
        x_axis = st.selectbox(
            "Pilih sumbu X:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=3
        )

    with col2:
        y_axis = st.selectbox(
            "Pilih sumbu Y:",
            ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'],
            index=0
        )

    fig, ax = plt.subplots(figsize=(5, 3))

    correlation = df_preprocessed_numeric[x_axis].corr(df_preprocessed_numeric[y_axis])

    scatter = sns.scatterplot(
        data=df_preprocessed_numeric,
        x=x_axis,
        y=y_axis,
        hue='Label_Kesehatan',
        palette={'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'},
        alpha=0.7,
        s=30,
        ax=ax,
        legend='brief'
    )

    ax.set_title(f'Hubungan {x_axis} dan {y_axis}', fontsize=10, pad=5)
    ax.set_xlabel(x_axis.replace('_', ' '), fontsize=8, labelpad=2)
    ax.set_ylabel(y_axis.replace('_', ' '), fontsize=8, labelpad=2)
    ax.tick_params(labelsize=7)
    ax.grid(True, alpha=0.2, linewidth=0.5)

    ax.legend(title='Label Kesehatan',
             fontsize=7,
             title_fontsize=8,
             loc='upper left' if correlation > 0 else 'upper right',
             frameon=True,
             framealpha=0.8)

    st.pyplot(fig, use_container_width=False)

    st.divider()
    st.subheader("Analisis Korelasi")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Koefisien Korelasi", f"{correlation:.3f}")

    with col2:
        if abs(correlation) > 0.7:
            strength = "Kuat"
        elif abs(correlation) > 0.3:
            strength = "Sedang"
        else:
            strength = "Lemah"
        st.metric("Kekuatan", strength)

    with col3:
        direction = "Positif" if correlation > 0 else "Negatif"
        st.metric("Arah", direction)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray; font-size: 0.8em;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv
    </div>
    """,
    unsafe_allow_html=True
)