# -*- coding: utf-8 -*-
"""Datvis_UAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RvKp5BkbRmUROJHceP5cjDs2gUKa40DT
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
from wordcloud import WordCloud

# =====================================================
# KONFIGURASI HALAMAN
# =====================================================
st.set_page_config(page_title="Datvis UAS", layout="wide")
st.title("Dashboard Analisis Nutrisi & Teks Makanan")

st.caption(
    "Dashboard ini menyajikan analisis kandungan gizi dan teks deskripsi makanan "
    "untuk membedakan karakteristik makanan sehat dan tidak sehat."
)

# =====================================================
# SIDEBAR
# =====================================================
menu = st.sidebar.radio(
    "Navigasi",
    [
        "Dataset",
        "Analisis Gizi",
        "Analisis Teks",
        "Integrasi Analisis"
    ]
)

# =====================================================
# LOAD DATA
# =====================================================
@st.cache_data
def load_data():
    df = pd.read_csv("dataset_nutrisi_text_300.csv")
    df.columns = df.columns.str.strip()
    return df

df = load_data()

# =====================================================
# PREPROCESSING NUMERIK
# =====================================================
numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']

for col in numeric_cols:
    df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

df_numeric = df[numeric_cols].copy()
for col in numeric_cols:
    df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

# =====================================================
# PREPROCESSING TEKS
# =====================================================
df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
df_text['clean_text'] = df_text['Food_Text'].astype(str).str.lower()

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df_text['clean_text'])
tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

y = df_text['Label_Kesehatan'].map({'Sehat': 1, 'Tidak Sehat': 0})
mi_scores = mutual_info_classif(tfidf_df, y)

mi_df = pd.DataFrame({
    "Fitur": tfidf_df.columns,
    "Information Gain": mi_scores
}).sort_values(by="Information Gain", ascending=False)

# =====================================================
# MENU 1 — DATASET
# =====================================================
if menu == "Dataset":
    st.header("Dataset")
    st.caption(
        "Menampilkan sebagian data nutrisi dan teks makanan "
        "yang digunakan sebagai dasar analisis."
    )
    st.dataframe(df.head(10))

# =====================================================
# MENU 2 — ANALISIS GIZI
# =====================================================
elif menu == "Analisis Gizi":
    st.header("Analisis Gizi")

    st.info(
        "Analisis ini membandingkan kandungan gizi utama seperti protein, "
        "lemak, gula, natrium, dan energi pada makanan."
    )

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Rata-rata Kandungan Protein")
        fig, ax = plt.subplots()
        df.groupby("Food_Name")["Protein_g"].mean().plot(kind="bar", ax=ax)
        ax.set_ylabel("Protein (gram)")
        st.pyplot(fig)
        st.caption("Perbedaan kandungan protein dapat mengindikasikan kualitas gizi makanan.")

    with col2:
        st.subheader("Perbandingan Gula dan Natrium")
        fig, ax = plt.subplots()
        df.groupby("Label_Kesehatan")[["Sugar_g","Sodium_mg"]].mean().plot(kind="bar", ax=ax)
        st.pyplot(fig)
        st.caption(
            "Makanan tidak sehat cenderung memiliki kadar gula dan natrium lebih tinggi."
        )

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Hubungan Protein dan Lemak")
        fig, ax = plt.subplots()
        sns.scatterplot(data=df, x="Protein_g", y="Fat_g", hue="Label_Kesehatan", ax=ax)
        st.pyplot(fig)

    with col2:
        st.subheader("Distribusi Energi (Kalori)")
        fig, ax = plt.subplots()
        ax.hist(df["Energy_kcal"], bins=20)
        st.pyplot(fig)

    with st.expander("Korelasi Antar Kandungan Gizi"):
        fig, ax = plt.subplots()
        sns.heatmap(
            df[numeric_cols].corr(),
            annot=True, cmap="coolwarm", fmt=".2f", ax=ax
        )
        st.pyplot(fig)

# =====================================================
# MENU 3 — ANALISIS TEKS
# =====================================================
elif menu == "Analisis Teks":
    st.header("Analisis Teks")

    st.info(
        "Analisis teks digunakan untuk mengidentifikasi kata-kata "
        "yang sering muncul dan paling berpengaruh dalam klasifikasi kesehatan makanan."
    )

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("WordCloud Makanan Sehat")
        wc = WordCloud(background_color="white").generate(
            " ".join(df[df["Label_Kesehatan"]=="Sehat"]["Food_Text"].astype(str))
        )
        fig, ax = plt.subplots()
        ax.imshow(wc); ax.axis("off")
        st.pyplot(fig)

    with col2:
        st.subheader("WordCloud Makanan Tidak Sehat")
        wc = WordCloud(background_color="white").generate(
            " ".join(df[df["Label_Kesehatan"]=="Tidak Sehat"]["Food_Text"].astype(str))
        )
        fig, ax = plt.subplots()
        ax.imshow(wc); ax.axis("off")
        st.pyplot(fig)

    st.subheader("Fitur Teks Paling Berpengaruh (Information Gain)")
    fig, ax = plt.subplots(figsize=(8,5))
    sns.barplot(data=mi_df.head(20), x="Information Gain", y="Fitur", ax=ax)
    st.pyplot(fig)

# =====================================================
# MENU 4 — INTEGRASI ANALISIS
# =====================================================
else:
    st.header("Integrasi Analisis Gizi & Teks")

    st.info(
        "Bagian ini menggabungkan analisis numerik dan teks "
        "untuk memberikan interpretasi yang lebih komprehensif."
    )

    fig, axes = plt.subplots(1, 2, figsize=(14,5))

    sns.scatterplot(
        data=df,
        x="Protein_g",
        y="Fat_g",
        hue="Label_Kesehatan",
        ax=axes[0]
    )
    axes[0].set_title("Protein vs Lemak")

    sns.barplot(
        data=mi_df.head(10),
        x="Information Gain",
        y="Fitur",
        ax=axes[1]
    )
    axes[1].set_title("Top 10 Fitur Teks")

    st.pyplot(fig)

    st.caption(
        "Visualisasi ini menunjukkan hubungan antara kandungan gizi "
        "dan fitur teks yang paling berpengaruh dalam menentukan label kesehatan."
    )