# -*- coding: utf-8 -*-
"""Final Datvis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ctHcFosLBrA0qgVBEhS7i-d1BrD4L3D
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="wide"
)

st.title("Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped


df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi"
    ]
)

# =========================
# 1. OVERVIEW DATA
# =========================
if page == "Overview Data":
    st.header("Overview Data")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Data Sample")
        st.dataframe(
            df.head(10),
            use_container_width=True,
            height=320
        )

        st.subheader("Statistik Deskriptif")
        st.dataframe(
            df.describe(),
            use_container_width=True,
            height=320
        )

    with col2:
        st.subheader("Distribusi Label Kesehatan")
        fig, ax = plt.subplots(figsize=(6, 4))
        df['Label_Kesehatan'].value_counts().plot(
            kind='bar',
            ax=ax,
            color=['green', 'orange', 'red']
        )
        ax.set_title("Distribusi Label Kesehatan")
        ax.set_xlabel("Label")
        ax.set_ylabel("Jumlah")
        st.pyplot(fig)

        st.subheader("Informasi Dataset")
        st.metric("Total Data", len(df))
        st.metric("Total Kolom", len(df.columns))

        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum(),
            'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
        })

        st.dataframe(
            missing_data[missing_data['Missing Values'] > 0],
            use_container_width=True,
            height=250
        )

# =========================
# 2. ANALISIS NUMERIK
# =========================
elif page == "Analisis Numerik":
    st.header("Analisis Numerik")

    tab1, tab2, tab3, tab4 = st.tabs(
        ["Distribusi", "Perbandingan", "Korelasi", "Histogram"]
    )

    with tab1:
        avg_nutrisi = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

        fig, axes = plt.subplots(2, 2, figsize=(12, 8))
        nutrients = [
            ('Protein_g', 'Protein (g)'),
            ('Fat_g', 'Lemak (g)'),
            ('Sugar_g', 'Gula (g)'),
            ('Sodium_mg', 'Natrium (mg)')
        ]

        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for idx, (col, title) in enumerate(nutrients):
            ax = axes[idx // 2, idx % 2]
            values = avg_nutrisi[col]
            bars = ax.bar(
                values.index,
                values.values,
                color=[colors[label] for label in values.index]
            )
            ax.set_title(f'Rata-rata {title}')
            ax.tick_params(axis='x', rotation=45)

            for bar in bars:
                h = bar.get_height()
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    h,
                    f"{h:.1f}",
                    ha='center',
                    va='bottom'
                )

        st.pyplot(fig)

    with tab2:
        avg = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Sugar_g', 'Sodium_mg']].mean()

        fig, ax = plt.subplots(figsize=(10, 6))
        avg.plot(kind='bar', ax=ax)
        ax.set_title("Perbandingan Gula & Natrium")
        st.pyplot(fig)

    with tab3:
        corr = df_preprocessed_numeric[
            ['Energy_kcal', 'Protein_g', 'Fat_g',
             'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
        ].corr()

        fig, ax = plt.subplots(figsize=(10, 8))
        sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax)
        st.pyplot(fig)

    with tab4:
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.hist(df_numeric_capped["Energy_kcal"], bins=20)
        st.pyplot(fig)

# =========================
# 3. ANALISIS TEKS
# =========================
elif page == "Analisis Teks":
    st.header("Analisis Teks")

    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    tab1, tab2 = st.tabs(["☁️ Word Cloud", "Information Gain"])

    with tab1:
        label_option = st.selectbox(
            "Pilih Label:",
            ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat']
        )

        if label_option == 'Semua':
            text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
        else:
            text_data = " ".join(
                df_text[df_text['Label_Kesehatan'] == label_option]
                ['Food_Text'].dropna().astype(str)
            )

        if text_data.strip():
            fig, ax = plt.subplots(figsize=(8, 4))
            wc = WordCloud(background_color="white").generate(text_data)
            ax.imshow(wc)
            ax.axis("off")
            st.pyplot(fig)

    with tab2:
        vectorizer = TfidfVectorizer(max_features=30, stop_words="english")
        X = vectorizer.fit_transform(df["Food_Text"].astype(str))

        label_map = {'Kurang Sehat': 0, 'Cukup Sehat': 1, 'Sehat': 2}
        y = df['Label_Kesehatan'].map(label_map)
        valid = y.notnull()

        ig = mutual_info_classif(
            X[valid.values],
            y[valid],
            random_state=42
        )

        ig_df = pd.DataFrame({
            'Fitur': vectorizer.get_feature_names_out(),
            'Information_Gain': ig
        }).sort_values('Information_Gain', ascending=False).head(15)

        # ❌ TIDAK ADA VISUALISASI TF-IDF
        st.dataframe(
            ig_df,
            use_container_width=True,
            height=350
        )

# 4. Halaman Top 10 Makanan
elif page == "Top 10 Makanan":
    st.header("Top 10 Makanan")

    # Pilih nutrisi untuk ditampilkan
    nutrient_options = {
        "Protein (g)": "Protein_g",
        "Lemak (g)": "Fat_g",
        "Gula (g)": "Sugar_g",
        "Natrium (mg)": "Sodium_mg",
        "Energi (kcal)": "Energy_kcal",
        "Karbohidrat (g)": "Carbohydrate_g"
    }

    selected_nutrient = st.selectbox(
        "Pilih Kandungan Nutrisi:",
        list(nutrient_options.keys())
    )

    col_name = nutrient_options[selected_nutrient]

    # Pilih jumlah data
    n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 20, 10)

    # Ambil top makanan
    top_foods = (
        df.sort_values(col_name, ascending=False)
        .head(n_top)
    )

    # Plot
    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
    ax.set_xlabel(selected_nutrient)
    ax.set_title(f"Top {n_top} Makanan dengan Kandungan {selected_nutrient} Tertinggi")
    ax.invert_yaxis()

    # Warna berdasarkan label kesehatan
    for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
        if label == "Sehat":
            bar.set_color('green')
        elif label == "Cukup Sehat":
            bar.set_color('orange')
        else:
            bar.set_color('red')

    # Tambahkan legend
    import matplotlib.patches as mpatches
    healthy_patch = mpatches.Patch(color='green', label='Sehat')
    moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
    unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
    ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch])

    st.pyplot(fig)

    # Tampilkan data dalam tabel
    st.subheader("Data Detail")
    display_cols = ['Food_Name', 'Label_Kesehatan', col_name, 'Food_Text']
    st.dataframe(top_foods[display_cols], use_container_width=True)

# 5. Halaman Analisis Multi-Dimensi
elif page == "Analisis Multi-Dimensi":
    st.header("Analisis Multi-Dimensi")

    # Tab untuk analisis multi-dimensi
    tab1, tab2, tab3 = st.tabs([
        "Scatter Plot",
        "Radar Chart",
        "Insight Pola"
    ])

    with tab1:
        st.subheader("Scatter Plot: Hubungan Protein vs Lemak")

        # Agregasi data
        df_food = (
            df_preprocessed_numeric
            .groupby(["Food_Name", "Label_Kesehatan"], as_index=False)[
                ["Protein_g", "Fat_g"]
            ]
            .mean()
        )

        fig, ax = plt.subplots(figsize=(10, 6))

        # Plot dengan warna berdasarkan label
        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for label, color in colors.items():
            subset = df_food[df_food['Label_Kesehatan'] == label]
            ax.scatter(subset["Protein_g"], subset["Fat_g"],
                      c=color, s=80, alpha=0.7, label=label)

        ax.set_title("Hubungan Kandungan Protein dan Lemak", fontsize=14, fontweight='bold')
        ax.set_xlabel("Protein (gram)")
        ax.set_ylabel("Lemak (gram)")
        ax.legend(title="Label Kesehatan")
        ax.grid(True, alpha=0.3)

        st.pyplot(fig)

        # Insight scatter plot
        st.markdown("### Insight Scatter Plot:")
        st.markdown("""
        - **Makanan Sehat**: Cenderung memiliki protein tinggi dan lemak rendah
        - **Makanan Cukup Sehat**: Variasi protein dan lemak yang lebih beragam
        - **Makanan Kurang Sehat**: Cenderung memiliki lemak tinggi dengan variasi protein
        """)

    with tab2:
        st.subheader("Radar Chart: Profil Nutrisi per Kategori")

        # Data untuk radar chart
        categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']
        nutrients_for_radar = ['Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg', 'Energy_kcal']
        nutrient_labels = ['Protein', 'Lemak', 'Gula', 'Karbohidrat', 'Natrium', 'Energi']

        # Hitung rata-rata dan normalisasi
        category_profiles = {}
        category_means_raw = {}  # Untuk menyimpan nilai rata-rata asli

        for category in categories:
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
            means = []
            raw_means = []

            for nutrient in nutrients_for_radar:
                mean_val = subset[nutrient].mean()
                raw_means.append(mean_val)
                means.append(mean_val)

            means_array = np.array(means)
            raw_means_array = np.array(raw_means)

            # Normalisasi min-max per kategori
            if means_array.max() - means_array.min() > 0:
                normalized = (means_array - means_array.min()) / (means_array.max() - means_array.min())
            else:
                normalized = np.zeros_like(means_array)

            category_profiles[category] = normalized
            category_means_raw[category] = raw_means_array

        # Buat radar chart
        angles = np.linspace(0, 2*np.pi, len(nutrients_for_radar), endpoint=False).tolist()
        angles += angles[:1]  # Tutup lingkaran

        fig, ax = plt.subplots(figsize=(10, 8), subplot_kw=dict(projection='polar'))

        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for category, color in colors.items():
            values = category_profiles[category].tolist()
            values += values[:1]  # Tutup lingkaran

            ax.plot(angles, values, 'o-', linewidth=2, label=category, color=color)
            ax.fill(angles, values, alpha=0.2, color=color)

        ax.set_xticks(angles[:-1])
        ax.set_xticklabels(nutrient_labels, fontsize=10)
        ax.set_ylim(0, 1)
        ax.set_title('PROFIL NUTRISI NORMALISASI\n(Perbandingan Relatif Antar Kategori)',
                    fontsize=14, fontweight='bold', pad=30)
        ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.0))
        ax.grid(True)

        st.pyplot(fig)

        # Tabel nilai rata-rata asli
        st.subheader("Rata-rata Nilai Asli per Kategori")

        # Buat DataFrame untuk nilai asli
        raw_data = []
        for category in categories:
            raw_means = category_means_raw[category]
            row = [category] + list(raw_means)
            raw_data.append(row)

        df_raw_means = pd.DataFrame(
            raw_data,
            columns=['Kategori'] + nutrient_labels
        )

        # Format angka
        for col in nutrient_labels:
            if col in ['Protein', 'Lemak', 'Gula', 'Karbohidrat']:
                df_raw_means[col] = df_raw_means[col].round(1)
            elif col == 'Natrium':
                df_raw_means[col] = df_raw_means[col].round(0)
            else:  # Energi
                df_raw_means[col] = df_raw_means[col].round(0)

        st.dataframe(df_raw_means, use_container_width=True)

    with tab3:
        st.subheader("Insight Pola Nutrisi")

        # Hitung statistik per kategori
        categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']
        nutrients = ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg', 'Energy_kcal']
        nutrient_names = ['Protein', 'Lemak', 'Gula', 'Natrium', 'Energi']
        units = ['g', 'g', 'g', 'mg', 'kcal']

        # Container untuk setiap kategori
        for idx, category in enumerate(categories):
            with st.expander(f"🔍 **{category.upper()}**", expanded=(idx==0)):
                # Filter data
                subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]

                col1, col2, col3 = st.columns(3)

                with col1:
                    st.metric(
                        label="Jumlah Makanan",
                        value=f"{len(subset)}",
                        help=f"Total makanan dalam kategori {category}"
                    )

                with col2:
                    # Makanan dengan protein tertinggi
                    top_protein = subset.nlargest(1, 'Protein_g')
                    if not top_protein.empty:
                        st.metric(
                            label="Protein Tertinggi",
                            value=f"{top_protein['Protein_g'].values[0]:.1f}g",
                            help=f"{top_protein['Food_Name'].values[0]}"
                        )

                with col3:
                    # Makanan dengan gula tertinggi
                    top_sugar = subset.nlargest(1, 'Sugar_g')
                    if not top_sugar.empty:
                        st.metric(
                            label="Gula Tertinggi",
                            value=f"{top_sugar['Sugar_g'].values[0]:.1f}g",
                            help=f"{top_sugar['Food_Name'].values[0]}"
                        )

                # Rata-rata nutrisi
                st.subheader("Rata-rata Kandungan Nutrisi")

                # Buat DataFrame untuk rata-rata
                avg_values = []
                for nutrient, name, unit in zip(nutrients, nutrient_names, units):
                    avg_val = subset[nutrient].mean()
                    avg_values.append({
                        'Nutrisi': name,
                        'Rata_Rata': avg_val,  # Simpan sebagai float
                        'Unit': unit
                    })

                # Sort berdasarkan nilai
                avg_df = pd.DataFrame(avg_values)
                avg_df = avg_df.sort_values('Rata_Rata', ascending=False)

                # Tampilkan sebagai metrik dalam grid
                cols = st.columns(len(avg_df))
                for i, row in avg_df.iterrows():
                    with cols[i]:
                        st.metric(
                            label=row['Nutrisi'],
                            value=f"{row['Rata_Rata']:.1f}",
                            delta=row['Unit'],
                            delta_color="off"
                        )

                # Pola khusus per kategori
                st.subheader("Karakteristik Pola")

                if category == 'Sehat':
                    st.markdown("""
                    **Karakteristik Utama:**
                    - Protein tinggi, gula rendah
                    - Lemak dalam jumlah sedang
                    - Natrium terkontrol
                    - Energi seimbang

                    **Contoh Makanan Khas:** Ikan, sayuran, biji-bijian
                    """)

                elif category == 'Cukup Sehat':
                    st.markdown("""
                    **Karakteristik Utama:**
                    - Nutrisi seimbang
                    - Protein dan karbohidrat cukup
                    - Gula dan natrium sedang
                    - Variasi kandungan lemak

                    **Contoh Makanan Khas:** Olahan tradisional, makanan dengan bumbu
                    """)

                elif category == 'Kurang Sehat':
                    st.markdown("""
                    **Karakteristik Utama:**
                    - Gula tinggi
                    - Lemak jenuh tinggi
                    - Natrium tinggi
                    - Energi tinggi
                    - Protein biasanya rendah atau tinggi lemak

                    **Contoh Makanan Khas:** Makanan cepat saji, makanan olahan, dessert
                    """)

                # Contoh makanan representatif
                st.subheader("Contoh Makanan Representatif")

                # Ambil 3 makanan representatif
                if len(subset) >= 3:
                    sample_foods = subset.sample(3, random_state=42)
                    for _, food in sample_foods.iterrows():
                        st.markdown(f"**{food['Food_Name']}**")
                        st.markdown(f"Protein: {food['Protein_g']:.1f}g | Lemak: {food['Fat_g']:.1f}g | Gula: {food['Sugar_g']:.1f}g")

        # Perbandingan antar kategori
        st.subheader("Perbandingan Antar Kategori")

        # Pilih nutrisi untuk perbandingan
        selected_nutrient = st.selectbox(
            "Pilih Nutrisi untuk Perbandingan:",
            nutrient_names,
            key="compare_nutrient"
        )

        # Map nama nutrisi ke kolom
        nutrient_map = dict(zip(nutrient_names, nutrients))
        selected_col = nutrient_map[selected_nutrient]

        # Hitung rata-rata per kategori
        comparison_data = []
        for category in categories:
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
            avg_val = subset[selected_col].mean()
            comparison_data.append({
                'Kategori': category,
                'Rata_rata': avg_val
            })

        comparison_df = pd.DataFrame(comparison_data)

        # Plot perbandingan
        fig, ax = plt.subplots(figsize=(8, 5))
        colors = ['green', 'orange', 'red']
        bars = ax.bar(comparison_df['Kategori'], comparison_df['Rata_rata'], color=colors)

        ax.set_title(f'Perbandingan {selected_nutrient} per Kategori', fontsize=14)
        ax.set_ylabel(f'Rata-rata {selected_nutrient}')

        # Tambahkan nilai di atas bar
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
                   f'{height:.1f}', ha='center', va='bottom')

        st.pyplot(fig)

        # Insight perbandingan
        st.markdown("### Insight Perbandingan")

        # Tentukan satuan
        unit_map = dict(zip(nutrient_names, units))
        unit = unit_map[selected_nutrient]

        # Urutkan dari tertinggi ke terendah
        sorted_df = comparison_df.sort_values('Rata_rata', ascending=False)

        highest = sorted_df.iloc[0]
        lowest = sorted_df.iloc[-1]

        st.info(f"""
        **{selected_nutrient} tertinggi** ditemukan pada kategori **{highest['Kategori']}**
        dengan rata-rata **{highest['Rata_rata']:.1f} {unit}**

        **{selected_nutrient} terendah** ditemukan pada kategori **{lowest['Kategori']}**
        dengan rata-rata **{lowest['Rata_rata']:.1f} {unit}**

        **Perbedaan:** {abs(highest['Rata_rata'] - lowest['Rata_rata']):.1f} {unit}
        """)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv •
    Dibuat dengan Streamlit
    </div>
    """,
    unsafe_allow_html=True
)