# -*- coding: utf-8 -*-
"""Final Datvis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ctHcFosLBrA0qgVBEhS7i-d1BrD4L3D
"""

# ===============================
# IMPORT LIBRARY
# ===============================
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from collections import Counter
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
import warnings
warnings.filterwarnings("ignore")

# ===============================
# KONFIGURASI HALAMAN
# ===============================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="wide"
)

st.title("Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# ===============================
# LOAD & PREPROCESS DATA
# ===============================
@st.cache_data
def load_data():
    df = pd.read_csv("nilai_gizi.csv", sep=";")
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = (
            df[col].astype(str)
            .str.replace(',', '.', regex=False)
        )
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col].fillna(df[col].median(), inplace=True)

        # Capping IQR
        Q1, Q3 = df[col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        df[col] = df[col].clip(Q1 - 1.5 * IQR, Q3 + 1.5 * IQR)

    # Scaling
    scaler = StandardScaler()
    scaled = scaler.fit_transform(df[numeric_cols])
    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols]
    )

    df_final = pd.concat([df, df_scaled], axis=1)
    return df_final

df = load_data()

# ===============================
# SIDEBAR NAVIGASI
# ===============================
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi"
    ]
)

# ===============================
# 1. OVERVIEW DATA
# ===============================
if page == "Overview Data":
    st.header("Overview Data")

    st.dataframe(df.head(10), use_container_width=True)

    st.subheader("Distribusi Label Kesehatan")
    fig, ax = plt.subplots(figsize=(8,5))
    df['Label_Kesehatan'].value_counts().plot(
        kind='bar',
        color=['green','orange','red'],
        ax=ax
    )
    ax.set_xlabel("Label")
    ax.set_ylabel("Jumlah")
    st.pyplot(fig, use_container_width=True)

# ===============================
# 2. ANALISIS NUMERIK
# ===============================
elif page == "Analisis Numerik":
    st.header("Analisis Numerik")

    avg_nutrisi = df.groupby("Label_Kesehatan")[
        ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
    ].mean()

    fig, ax = plt.subplots(figsize=(10,6))
    avg_nutrisi.plot(kind='bar', ax=ax)
    ax.set_ylabel("Rata-rata")
    ax.set_title("Rata-rata Kandungan Nutrisi per Label Kesehatan")
    st.pyplot(fig, use_container_width=True)

# ===============================
# 3. ANALISIS TEKS (OPS 2 + IG)
# ===============================
elif page == "Analisis Teks":
    st.header("Analisis Teks")

    # ===== TOKEN ANALYSIS =====
    st.subheader("Analisis Token Teks")

    text_data = " ".join(df['Food_Text'].dropna().astype(str)).lower()
    tokens = re.findall(r'\b\w+\b', text_data)

    stopwords = {
        'dan','yang','dengan','untuk','atau',
        'tanpa','mengandung','tinggi','rendah'
    }

    tokens = [
        t for t in tokens
        if t not in stopwords and not t.isdigit() and len(t) > 2
    ]

    token_df = pd.DataFrame(
        Counter(tokens).most_common(15),
        columns=['Token','Frekuensi']
    )

    fig, ax = plt.subplots(figsize=(8,4))
    ax.barh(token_df['Token'], token_df['Frekuensi'])
    ax.invert_yaxis()
    ax.set_title("Top 15 Token Paling Sering Muncul")
    st.pyplot(fig, use_container_width=True)

    # ===== INFORMATION GAIN =====
st.subheader("Information Gain Teks")

vectorizer = TfidfVectorizer(
    max_features=20,
    stop_words="english"
)

X = vectorizer.fit_transform(df['Food_Text'].astype(str))

label_map = {
    'Kurang Sehat': 0,
    'Cukup Sehat': 1,
    'Sehat': 2
}

y = df['Label_Kesehatan'].map(label_map)

# 🔑 FIX UTAMA DI SINI
mask = y.notna().values   # numpy boolean array
X_valid = X[mask]
y_valid = y[mask].values

ig = mutual_info_classif(
    X_valid,
    y_valid,
    random_state=42
)

ig_df = pd.DataFrame({
    'Fitur': vectorizer.get_feature_names_out(),
    'Information Gain': ig
}).sort_values(by='Information Gain', ascending=False)

fig, ax = plt.subplots(figsize=(8,4))
sns.barplot(
    data=ig_df.head(10),
    x='Information Gain',
    y='Fitur',
    ax=ax
)
ax.set_title("Top 10 Fitur Teks (Information Gain)")
st.pyplot(fig, use_container_width=True)


# ===============================
# 4. TOP 10 MAKANAN
# ===============================
elif page == "Top 10 Makanan":
    st.header("Top 10 Makanan")

    top_protein = df.sort_values("Protein_g", ascending=False).head(10)

    fig, ax = plt.subplots(figsize=(8,5))
    ax.barh(top_protein['Food_Name'], top_protein['Protein_g'])
    ax.invert_yaxis()
    ax.set_xlabel("Protein (g)")
    ax.set_title("Top 10 Makanan dengan Protein Tertinggi")
    st.pyplot(fig, use_container_width=True)

    st.dataframe(
        top_protein[['Food_Name','Protein_g','Label_Kesehatan']],
        use_container_width=True
    )

# ===============================
# 5. ANALISIS MULTI-DIMENSI
# ===============================
elif page == "Analisis Multi-Dimensi":
    st.header("Analisis Multi-Dimensi")

    fig, ax = plt.subplots(figsize=(8,5))
    colors = {'Sehat':'green','Cukup Sehat':'orange','Kurang Sehat':'red'}

    for label, color in colors.items():
        subset = df[df['Label_Kesehatan'] == label]
        ax.scatter(
            subset['Protein_g'],
            subset['Fat_g'],
            color=color,
            label=label,
            alpha=0.7
        )

    ax.set_xlabel("Protein (g)")
    ax.set_ylabel("Lemak (g)")
    ax.set_title("Scatter Plot Protein vs Lemak")
    ax.legend()
    ax.grid(alpha=0.3)
    st.pyplot(fig, use_container_width=True)

# ===============================
# FOOTER
# ===============================
st.markdown("---")
st.markdown(
    "<center>Dashboard Analisis Nutrisi Makanan • Streamlit</center>",
    unsafe_allow_html=True
)