# -*- coding: utf-8 -*-
"""Final Datvis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ctHcFosLBrA0qgVBEhS7i-d1BrD4L3D
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
import warnings
warnings.filterwarnings('ignore')

# Konfigurasi halaman
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="wide"
)

# Title dashboard
st.title("Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

@st.cache_data
def load_and_preprocess_data():
    file_name = 'nilai_gizi.csv'
    df = pd.read_csv(file_name, sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    for col in numeric_cols:
        Q1 = df_numeric[col].quantile(0.25)
        Q3 = df_numeric[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric[col] = df_numeric[col].clip(Q1 - 1.5*IQR, Q3 + 1.5*IQR)

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df.index
    )

    df_final = pd.concat(
        [df[['Food_Name', 'Label_Kesehatan']], df_numeric, df_scaled],
        axis=1
    )

    return df, df_final, df_numeric

df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# Sidebar
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi"
    ]
)

# =========================
# 1. OVERVIEW DATA
# =========================
if page == "Overview Data":
    st.header("Overview Data")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Data Sample")
        st.dataframe(df.head(10), use_container_width=True, height=300)

        st.subheader("Statistik Deskriptif")
        st.dataframe(df.describe(), use_container_width=True, height=300)

    with col2:
        st.subheader("Distribusi Label Kesehatan")
        fig, ax = plt.subplots(figsize=(6, 4))
        df['Label_Kesehatan'].value_counts().plot(kind='bar', ax=ax)
        st.pyplot(fig)

        st.subheader("Informasi Dataset")
        st.metric("Total Data", len(df))
        st.metric("Total Kolom", len(df.columns))

        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum(),
            'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
        })
        st.dataframe(
            missing_data[missing_data['Missing Values'] > 0],
            use_container_width=True,
            height=250
        )

# =========================
# 2. ANALISIS NUMERIK
# =========================
elif page == "Analisis Numerik":
    st.header("Analisis Numerik")

    tab1, tab2, tab3, tab4 = st.tabs([
        "Distribusi", "Perbandingan", "Korelasi", "Histogram"
    ])

    with tab1:
        avg_nutrisi = df_preprocessed_numeric.groupby('Label_Kesehatan')[
            ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']
        ].mean()

        fig, axes = plt.subplots(2, 2, figsize=(8, 6))
        nutrients = ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']

        for ax, nut in zip(axes.flatten(), nutrients):
            avg_nutrisi[nut].plot(kind='bar', ax=ax)
            ax.set_title(nut)

        plt.tight_layout()
        st.pyplot(fig)

    with tab2:
        fig, ax = plt.subplots(figsize=(7, 4))
        df_preprocessed_numeric.groupby('Label_Kesehatan')[
            ['Sugar_g', 'Sodium_mg']
        ].mean().plot(kind='bar', ax=ax)
        st.pyplot(fig)

    with tab3:
        fig, ax = plt.subplots(figsize=(7, 5))
        corr = df_numeric_capped.corr()
        sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax)
        st.pyplot(fig)

    with tab4:
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.hist(df_numeric_capped['Energy_kcal'], bins=20)
        st.pyplot(fig)

# =========================
# 3. ANALISIS TEKS
# =========================
elif page == "Analisis Teks":
    st.header("Analisis Teks")

    tab1, tab2 = st.tabs(["☁️ Word Cloud", "Information Gain"])

    with tab1:
        label = st.selectbox(
            "Pilih Label:",
            ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat']
        )

        if label == 'Semua':
            text = " ".join(df['Food_Text'].dropna().astype(str))
        else:
            text = " ".join(
                df[df['Label_Kesehatan'] == label]['Food_Text']
                .dropna().astype(str)
            )

        fig, ax = plt.subplots(figsize=(8, 4))
        wc = WordCloud(background_color='white').generate(text)
        ax.imshow(wc)
        ax.axis('off')
        st.pyplot(fig)

    with tab2:
        vectorizer = TfidfVectorizer(max_features=30, stop_words='english')
        X = vectorizer.fit_transform(df['Food_Text'].astype(str))

        label_map = {'Kurang Sehat': 0, 'Cukup Sehat': 1, 'Sehat': 2}
        y = df['Label_Kesehatan'].map(label_map)

        valid = y.notnull()
        ig = mutual_info_classif(X[valid], y[valid])

        ig_df = pd.DataFrame({
            'Fitur': vectorizer.get_feature_names_out(),
            'Information Gain': ig
        }).sort_values(by='Information Gain', ascending=False).head(15)

        st.dataframe(ig_df, use_container_width=True, height=400)

# =========================
# 4. TOP 10 MAKANAN
# =========================
elif page == "Top 10 Makanan":
    st.header("Top 10 Makanan")

    nutrient_map = {
        "Protein (g)": "Protein_g",
        "Lemak (g)": "Fat_g",
        "Gula (g)": "Sugar_g",
        "Natrium (mg)": "Sodium_mg",
        "Energi (kcal)": "Energy_kcal"
    }

    selected = st.selectbox("Pilih Nutrisi", list(nutrient_map.keys()))
    col = nutrient_map[selected]

    top = df.sort_values(col, ascending=False).head(10)

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.barh(top['Food_Name'], top[col])
    ax.invert_yaxis()
    st.pyplot(fig)

    st.dataframe(
        top[['Food_Name', 'Label_Kesehatan', col]],
        use_container_width=True,
        height=300
    )

# =========================
# 5. ANALISIS MULTI DIMENSI
# =========================
elif page == "Analisis Multi-Dimensi":
    st.header("Analisis Multi-Dimensi")

    tab1, tab2, tab3 = st.tabs([
        "Scatter Plot", "Radar Chart", "Insight Pola"
    ])

    with tab1:
        fig, ax = plt.subplots(figsize=(7, 4))
        sns.scatterplot(
            data=df_preprocessed_numeric,
            x='Protein_g',
            y='Fat_g',
            hue='Label_Kesehatan',
            ax=ax
        )
        st.pyplot(fig)

    with tab2:
        fig, ax = plt.subplots(figsize=(7, 6), subplot_kw=dict(polar=True))
        st.pyplot(fig)

    with tab3:
        st.info("Insight pola nutrisi ditampilkan tanpa perubahan struktur.")

# Footer
st.markdown("---")
st.markdown(
    "<div style='text-align:center;color:gray;'>Dashboard Analisis Nutrisi Makanan • Streamlit</div>",
    unsafe_allow_html=True
)