# -*- coding: utf-8 -*-
"""Final Datvis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ctHcFosLBrA0qgVBEhS7i-d1BrD4L3D
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="wide"
)

st.title("Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped


df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi"
    ]
)

# =========================
# 1. OVERVIEW DATA (TAB / NAVBAR)
# =========================
if page == "Overview Data":
    st.header("Overview Data")

    tab1, tab2, tab3, tab4 = st.tabs([
        "📄 Data Sample",
        "📊 Statistik Deskriptif",
        "📈 Distribusi",
        "ℹ️ Informasi Dataset"
    ])

    with tab1:
        st.subheader("Contoh Data")
        st.dataframe(
            df.head(10),
            use_container_width=True,
            height=350
        )

    with tab2:
        st.subheader("Statistik Deskriptif")
        st.dataframe(
            df.describe(),
            use_container_width=True,
            height=350
        )

    with tab3:
        st.subheader("Distribusi Label Kesehatan")
        fig, ax = plt.subplots(figsize=(7, 4))
        df['Label_Kesehatan'].value_counts().plot(
            kind='bar',
            ax=ax,
            color=['green', 'orange', 'red']
        )
        ax.set_xlabel("Label Kesehatan")
        ax.set_ylabel("Jumlah")
        ax.set_title("Distribusi Label Kesehatan")
        ax.grid(axis='y', alpha=0.3)
        st.pyplot(fig)

    with tab4:
        st.subheader("Informasi Dataset")

        col1, col2 = st.columns(2)
        with col1:
            st.metric("Total Data", len(df))
        with col2:
            st.metric("Total Kolom", len(df.columns))

        st.markdown("#### Missing Values")
        missing_data = pd.DataFrame({
            'Kolom': df.columns,
            'Missing Values': df.isnull().sum(),
            'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
        })

        st.dataframe(
            missing_data[missing_data['Missing Values'] > 0],
            use_container_width=True,
            height=300
        )

# =========================
# 2. ANALISIS NUMERIK
# =========================
elif page == "Analisis Numerik":
    st.header("Analisis Numerik")

    tab1, tab2, tab3, tab4 = st.tabs(
        ["Distribusi", "Perbandingan", "Korelasi", "Histogram"]
    )

    with tab1:
        avg_nutrisi = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

        fig, axes = plt.subplots(2, 2, figsize=(12, 8))
        nutrients = [
            ('Protein_g', 'Protein (g)'),
            ('Fat_g', 'Lemak (g)'),
            ('Sugar_g', 'Gula (g)'),
            ('Sodium_mg', 'Natrium (mg)')
        ]

        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for idx, (col, title) in enumerate(nutrients):
            ax = axes[idx // 2, idx % 2]
            values = avg_nutrisi[col]
            bars = ax.bar(
                values.index,
                values.values,
                color=[colors[label] for label in values.index]
            )
            ax.set_title(f'Rata-rata {title}')
            ax.tick_params(axis='x', rotation=45)

            for bar in bars:
                h = bar.get_height()
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    h,
                    f"{h:.1f}",
                    ha='center',
                    va='bottom'
                )

        st.pyplot(fig)

    with tab2:
        avg = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Sugar_g', 'Sodium_mg']].mean()

        fig, ax = plt.subplots(figsize=(10, 6))
        avg.plot(kind='bar', ax=ax)
        ax.set_title("Perbandingan Gula dan Natrium")
        st.pyplot(fig)

    with tab3:
        corr = df_preprocessed_numeric[
            ['Energy_kcal', 'Protein_g', 'Fat_g',
             'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
        ].corr()

        fig, ax = plt.subplots(figsize=(10, 8))
        sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax)
        st.pyplot(fig)

    with tab4:
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.hist(df_numeric_capped["Energy_kcal"], bins=20)
        st.pyplot(fig)

# =========================
# 3. ANALISIS TEKS
# =========================
elif page == "Analisis Teks":
    st.header("Analisis Teks")

    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    tab1, tab2 = st.tabs(["☁️ Word Cloud", "Information Gain"])

    with tab1:
        label_option = st.selectbox(
            "Pilih Label:",
            ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat']
        )

        if label_option == 'Semua':
            text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
        else:
            text_data = " ".join(
                df_text[df_text['Label_Kesehatan'] == label_option]
                ['Food_Text'].dropna().astype(str)
            )

        if text_data.strip():
            fig, ax = plt.subplots(figsize=(8, 4))
            wc = WordCloud(background_color="white").generate(text_data)
            ax.imshow(wc)
            ax.axis("off")
            st.pyplot(fig)

    with tab2:
        vectorizer = TfidfVectorizer(max_features=30, stop_words="english")
        X = vectorizer.fit_transform(df["Food_Text"].astype(str))

        label_map = {'Kurang Sehat': 0, 'Cukup Sehat': 1, 'Sehat': 2}
        y = df['Label_Kesehatan'].map(label_map)
        valid = y.notnull()

        ig = mutual_info_classif(
            X[valid.values],
            y[valid],
            random_state=42
        )

        ig_df = pd.DataFrame({
            'Fitur': vectorizer.get_feature_names_out(),
            'Information_Gain': ig
        }).sort_values('Information_Gain', ascending=False).head(15)

        st.dataframe(
            ig_df,
            use_container_width=True,
            height=350
        )

# =========================
# 4 & 5 HALAMAN LAIN
# =========================
# Top 10 Makanan & Analisis Multi-Dimensi
# ➜ TIDAK DIUBAH (pakai kode kamu sebelumnya)

st.markdown("---")
st.markdown(
    "<div style='text-align:center;color:gray;'>Dashboard Analisis Nutrisi Makanan • Streamlit</div>",
    unsafe_allow_html=True
)