# -*- coding: utf-8 -*-
"""Final Datvis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ctHcFosLBrA0qgVBEhS7i-d1BrD4L3D
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
warnings.filterwarnings('ignore')

# =========================
# KONFIGURASI HALAMAN
# =========================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi Makanan",
    layout="wide"
)

st.title("Dashboard Analisis Nutrisi Makanan")
st.markdown("---")

# =========================
# LOAD & PREPROCESS DATA
# =========================
@st.cache_data
def load_and_preprocess_data():
    df = pd.read_csv('nilai_gizi.csv', sep=';')
    df.columns = df.columns.str.strip()

    numeric_cols = [
        'Energy_kcal', 'Protein_g', 'Fat_g',
        'Sugar_g', 'Carbohydrate_g', 'Sodium_mg'
    ]

    for col in numeric_cols:
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df_numeric = df[numeric_cols].copy()
    for col in numeric_cols:
        df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

    df_numeric_capped = df_numeric.copy()
    for col in numeric_cols:
        Q1 = df_numeric_capped[col].quantile(0.25)
        Q3 = df_numeric_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        df_numeric_capped[col] = df_numeric_capped[col].clip(
            Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        )

    scaler = StandardScaler()
    scaled = scaler.fit_transform(df_numeric_capped)

    df_scaled = pd.DataFrame(
        scaled,
        columns=[f"{c}_scaled" for c in numeric_cols],
        index=df_numeric_capped.index
    )

    df_preprocessed = pd.concat(
        [
            df[['Food_Name', 'Label_Kesehatan']],
            df_numeric_capped,
            df_scaled
        ],
        axis=1
    )

    return df, df_preprocessed, df_numeric_capped


df, df_preprocessed_numeric, df_numeric_capped = load_and_preprocess_data()

# =========================
# SIDEBAR
# =========================
st.sidebar.title("Navigasi")
page = st.sidebar.radio(
    "Pilih Halaman:",
    [
        "Overview Data",
        "Analisis Numerik",
        "Analisis Teks",
        "Top 10 Makanan",
        "Analisis Multi-Dimensi"
    ]
)

# =========================
# 1. OVERVIEW DATA
# =========================
if page == "Overview Data":
    st.header("📊 Overview Data")

    # Container untuk metrik ringkas
    st.subheader("📈 Metrik Utama")
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Total Data", f"{len(df):,}")

    with col2:
        st.metric("Total Kolom", len(df.columns))

    with col3:
        missing_total = df.isnull().sum().sum()
        st.metric("Total Missing Values", f"{missing_total:,}")

    with col4:
        sehat_count = len(df[df['Label_Kesehatan'] == 'Sehat'])
        st.metric("Makanan Sehat", f"{sehat_count:,}")

    st.divider()

    # 1. Data Sample - FULL WIDTH
    st.subheader("📋 Data Sample (10 baris pertama)")
    # Gunakan container dengan width penuh dan tinggi yang cukup
    st.dataframe(
        df.head(10),
        use_container_width=True,
        height=300,
        hide_index=True
    )

    st.divider()

    # 2. Statistik Deskriptif - FULL WIDTH
    st.subheader("📊 Statistik Deskriptif")
    st.dataframe(
        df.describe(),
        use_container_width=True,
        height=350,
        hide_index=True
    )

    st.divider()

    # 3. Distribusi Label Kesehatan
    st.subheader("🏷️ Distribusi Label Kesehatan")

    # Bar chart distribusi
    fig, ax = plt.subplots(figsize=(10, 4))
    counts = df['Label_Kesehatan'].value_counts()
    colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}
    bar_colors = [colors.get(label, 'gray') for label in counts.index]

    bars = ax.bar(counts.index, counts.values, color=bar_colors)
    ax.set_title("Distribusi Label Kesehatan", fontsize=12)
    ax.set_xlabel("Label", fontsize=10)
    ax.set_ylabel("Jumlah", fontsize=10)

    # Tambah nilai di atas bar
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{int(height):,}', ha='center', va='bottom', fontsize=9)

    st.pyplot(fig)

    # Tampilkan tabel distribusi juga
    distribusi_df = pd.DataFrame({
        'Label': counts.index,
        'Jumlah': counts.values,
        'Persentase': (counts.values / len(df) * 100).round(1)
    })

    col1, col2, col3 = st.columns(3)
    for idx, (label, count, percentage) in enumerate(zip(distribusi_df['Label'],
                                                          distribusi_df['Jumlah'],
                                                          distribusi_df['Persentase'])):
        with [col1, col2, col3][idx]:
            st.metric(label=f"{label}", value=f"{count:,}", delta=f"{percentage}%")

    st.divider()

    # 4. Informasi Missing Values
    st.subheader("🔍 Informasi Missing Values")

    missing_data = pd.DataFrame({
        'Kolom': df.columns,
        'Missing Values': df.isnull().sum(),
        'Persentase (%)': (df.isnull().sum() / len(df) * 100).round(2)
    }).sort_values('Missing Values', ascending=False)

    # Tampilkan hanya yang ada missing values
    missing_filtered = missing_data[missing_data['Missing Values'] > 0]

    if len(missing_filtered) > 0:
        st.dataframe(
            missing_filtered,
            use_container_width=True,
            height=min(250, len(missing_filtered) * 40),
            hide_index=True
        )

        # Visualisasi missing values
        fig2, ax2 = plt.subplots(figsize=(10, 3))
        missing_bars = missing_filtered.set_index('Kolom')['Missing Values']
        missing_bars.plot(kind='bar', ax=ax2, color='coral')
        ax2.set_title("Missing Values per Kolom", fontsize=11)
        ax2.set_ylabel("Jumlah Missing", fontsize=9)
        ax2.tick_params(axis='x', rotation=45, labelsize=8)
        st.pyplot(fig2)
    else:
        st.success("✅ Tidak ada missing values pada dataset")

    st.divider()

    # 5. Preview Kolom
    st.subheader("📋 Informasi Kolom Dataset")

    # Tampilkan informasi tipe data
    col_info = pd.DataFrame({
        'Kolom': df.columns,
        'Tipe Data': df.dtypes.values,
        'Contoh Nilai': df.iloc[0].values if len(df) > 0 else [''] * len(df.columns)
    })

    st.dataframe(
        col_info,
        use_container_width=True,
        height=min(350, len(col_info) * 40),
        hide_index=True
    )

# =========================
# 2. ANALISIS NUMERIK
# =========================
elif page == "Analisis Numerik":
    st.header("Analisis Numerik")

    tab1, tab2, tab3, tab4 = st.tabs(
        ["Distribusi", "Perbandingan", "Korelasi", "Histogram"]
    )

    with tab1:
        avg_nutrisi = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']].mean()

        fig, axes = plt.subplots(2, 2, figsize=(10, 6))
        nutrients = [
            ('Protein_g', 'Protein (g)'),
            ('Fat_g', 'Lemak (g)'),
            ('Sugar_g', 'Gula (g)'),
            ('Sodium_mg', 'Natrium (mg)')
        ]

        colors = {'Sehat': 'green', 'Cukup Sehat': 'orange', 'Kurang Sehat': 'red'}

        for idx, (col, title) in enumerate(nutrients):
            ax = axes[idx // 2, idx % 2]
            values = avg_nutrisi[col]
            bars = ax.bar(
                values.index,
                values.values,
                color=[colors[label] for label in values.index]
            )
            ax.set_title(f'Rata-rata {title}', fontsize=10)
            ax.tick_params(axis='x', rotation=45, labelsize=8)
            ax.tick_params(axis='y', labelsize=8)

            for bar in bars:
                h = bar.get_height()
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    h,
                    f"{h:.1f}",
                    ha='center',
                    va='bottom',
                    fontsize=8
                )

        plt.tight_layout()
        st.pyplot(fig)

    with tab2:
        avg = df_preprocessed_numeric.groupby(
            'Label_Kesehatan'
        )[['Sugar_g', 'Sodium_mg']].mean()

        fig, ax = plt.subplots(figsize=(8, 4))
        avg.plot(kind='bar', ax=ax)
        ax.set_title("Perbandingan Gula & Natrium", fontsize=11)
        ax.tick_params(axis='x', rotation=45, labelsize=9)
        ax.tick_params(axis='y', labelsize=9)
        ax.legend(fontsize=9)
        st.pyplot(fig)

    with tab3:
        corr = df_preprocessed_numeric[
            ['Energy_kcal', 'Protein_g', 'Fat_g',
             'Sugar_g', 'Carbohydrate_g', 'Sodium_mg']
        ].corr()

        fig, ax = plt.subplots(figsize=(8, 6))
        sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax, fmt='.2f',
                   annot_kws={"size": 8}, cbar_kws={"shrink": 0.8})
        ax.set_title("Heatmap Korelasi", fontsize=11)
        st.pyplot(fig)

    with tab4:
        fig, ax = plt.subplots(figsize=(7, 3))
        ax.hist(df_numeric_capped["Energy_kcal"], bins=20, edgecolor='black')
        ax.set_title("Distribusi Energy (kcal)", fontsize=11)
        ax.set_xlabel("Energy (kcal)", fontsize=9)
        ax.set_ylabel("Frekuensi", fontsize=9)
        ax.tick_params(labelsize=8)
        st.pyplot(fig)

# =========================
# 3. ANALISIS TEKS - HANYA WORD CLOUD
# =========================
elif page == "Analisis Teks":
    st.header("Analisis Teks")

    df_text = df[['Food_Text', 'Label_Kesehatan']].copy()
    df_text['text_lower'] = df_text['Food_Text'].str.lower()

    st.subheader("☁️ Word Cloud")

    label_option = st.selectbox(
        "Pilih Label:",
        ['Semua', 'Sehat', 'Cukup Sehat', 'Kurang Sehat'],
        key="wordcloud_label"
    )

    if label_option == 'Semua':
        text_data = " ".join(df_text['Food_Text'].dropna().astype(str))
    else:
        text_data = " ".join(
            df_text[df_text['Label_Kesehatan'] == label_option]
            ['Food_Text'].dropna().astype(str)
        )

    if text_data.strip():
        fig, ax = plt.subplots(figsize=(6, 3))
        wc = WordCloud(
            background_color="white",
            width=400,
            height=200,
            max_words=50
        ).generate(text_data)
        ax.imshow(wc, interpolation='bilinear')
        ax.axis("off")
        ax.set_title(f"Word Cloud - {label_option}", fontsize=10)
        st.pyplot(fig)

        # Informasi tambahan
        word_count = len(text_data.split())
        st.info(f"**Jumlah kata dalam Word Cloud:** {word_count:,} kata")
    else:
        st.warning("Tidak ada data teks untuk ditampilkan")

# =========================
# 4. TOP 10 MAKANAN
# =========================
elif page == "Top 10 Makanan":
    st.header("Top 10 Makanan")

    nutrient_options = {
        "Protein (g)": "Protein_g",
        "Lemak (g)": "Fat_g",
        "Gula (g)": "Sugar_g",
        "Natrium (mg)": "Sodium_mg",
        "Energi (kcal)": "Energy_kcal",
        "Karbohidrat (g)": "Carbohydrate_g"
    }

    selected_nutrient = st.selectbox(
        "Pilih Kandungan Nutrisi:",
        list(nutrient_options.keys())
    )

    col_name = nutrient_options[selected_nutrient]

    n_top = st.slider("Jumlah Makanan Tertinggi:", 5, 20, 10)

    top_foods = (
        df.sort_values(col_name, ascending=False)
        .head(n_top)
    )

    fig, ax = plt.subplots(figsize=(8, 4))
    bars = ax.barh(top_foods["Food_Name"], top_foods[col_name])
    ax.set_xlabel(selected_nutrient, fontsize=9)
    ax.set_title(f"Top {n_top} Makanan {selected_nutrient} Tertinggi", fontsize=11)
    ax.invert_yaxis()
    ax.tick_params(labelsize=8)

    for bar, label in zip(bars, top_foods["Label_Kesehatan"]):
        if label == "Sehat":
            bar.set_color('green')
        elif label == "Cukup Sehat":
            bar.set_color('orange')
        else:
            bar.set_color('red')

    import matplotlib.patches as mpatches
    healthy_patch = mpatches.Patch(color='green', label='Sehat')
    moderate_patch = mpatches.Patch(color='orange', label='Cukup Sehat')
    unhealthy_patch = mpatches.Patch(color='red', label='Kurang Sehat')
    ax.legend(handles=[healthy_patch, moderate_patch, unhealthy_patch],
              fontsize=8, loc='lower right')

    st.pyplot(fig)

    st.subheader("Data Detail")
    display_cols = ['Food_Name', 'Label_Kesehatan', col_name, 'Food_Text']
    st.dataframe(top_foods[display_cols], use_container_width=True, hide_index=True)

# =========================
# 5. ANALISIS MULTI-DIMENSI - HANYA INSIGHT POLA
# =========================
elif page == "Analisis Multi-Dimensi":
    st.header("Analisis Multi-Dimensi")

    st.subheader("🔍 Insight Pola Nutrisi")

    categories = ['Sehat', 'Cukup Sehat', 'Kurang Sehat']
    nutrients = ['Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg', 'Energy_kcal']
    nutrient_names = ['Protein', 'Lemak', 'Gula', 'Natrium', 'Energi']
    units = ['g', 'g', 'g', 'mg', 'kcal']

    for idx, category in enumerate(categories):
        with st.expander(f"**{category.upper()}**", expanded=(idx==0)):
            subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]

            # Metrik utama
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Jumlah Makanan", f"{len(subset)}")
            with col2:
                top_protein = subset.nlargest(1, 'Protein_g')
                if not top_protein.empty:
                    st.metric("Protein Tertinggi",
                             f"{top_protein['Protein_g'].values[0]:.1f}g",
                             top_protein['Food_Name'].values[0])
            with col3:
                top_sugar = subset.nlargest(1, 'Sugar_g')
                if not top_sugar.empty:
                    st.metric("Gula Tertinggi",
                             f"{top_sugar['Sugar_g'].values[0]:.1f}g",
                             top_sugar['Food_Name'].values[0])

            # Rata-rata nutrisi
            st.markdown("**📊 Rata-rata Kandungan Nutrisi:**")
            avg_values = []
            for nutrient, name, unit in zip(nutrients, nutrient_names, units):
                avg_val = subset[nutrient].mean()
                avg_values.append({
                    'Nutrisi': name,
                    'Rata_Rata': avg_val,
                    'Unit': unit
                })

            avg_df = pd.DataFrame(avg_values)
            avg_df = avg_df.sort_values('Rata_Rata', ascending=False)

            # Tampilkan metrik nutrisi
            cols = st.columns(len(avg_df))
            for i, row in avg_df.iterrows():
                with cols[i]:
                    st.metric(
                        label=row['Nutrisi'],
                        value=f"{row['Rata_Rata']:.1f}",
                        delta=row['Unit'],
                        delta_color="off"
                    )

            # Karakteristik pola
            st.markdown("**🎯 Karakteristik Pola:**")

            if category == 'Sehat':
                st.markdown("""
                - **Protein tinggi**, gula rendah
                - **Lemak dalam jumlah sedang**
                - **Natrium terkontrol**
                - **Energi seimbang**
                - **Contoh makanan:** Ikan, sayuran, biji-bijian
                """)
            elif category == 'Cukup Sehat':
                st.markdown("""
                - **Nutrisi seimbang**
                - **Protein dan karbohidrat cukup**
                - **Gula dan natrium sedang**
                - **Variasi kandungan lemak**
                - **Contoh makanan:** Olahan tradisional, makanan dengan bumbu
                """)
            elif category == 'Kurang Sehat':
                st.markdown("""
                - **Gula tinggi**
                - **Lemak jenuh tinggi**
                - **Natrium tinggi**
                - **Energi tinggi**
                - **Contoh makanan:** Makanan cepat saji, makanan olahan, dessert
                """)

            # Contoh makanan representatif
            st.markdown("**🍽️ Contoh Makanan Representatif:**")
            if len(subset) >= 3:
                sample_foods = subset.sample(3, random_state=42)
                for _, food in sample_foods.iterrows():
                    st.markdown(f"- **{food['Food_Name']}**")
                    st.markdown(f"  Protein: {food['Protein_g']:.1f}g | Lemak: {food['Fat_g']:.1f}g | Gula: {food['Sugar_g']:.1f}g")

    st.divider()

    # Perbandingan antar kategori
    st.subheader("📈 Perbandingan Antar Kategori")

    selected_nutrient = st.selectbox(
        "Pilih Nutrisi untuk Perbandingan:",
        nutrient_names,
        key="compare_nutrient"
    )

    nutrient_map = dict(zip(nutrient_names, nutrients))
    selected_col = nutrient_map[selected_nutrient]

    comparison_data = []
    for category in categories:
        subset = df_preprocessed_numeric[df_preprocessed_numeric['Label_Kesehatan'] == category]
        avg_val = subset[selected_col].mean()
        comparison_data.append({
            'Kategori': category,
            'Rata_rata': avg_val
        })

    comparison_df = pd.DataFrame(comparison_data)

    # Plot perbandingan
    fig, ax = plt.subplots(figsize=(6, 3))
    colors = ['green', 'orange', 'red']
    bars = ax.bar(comparison_df['Kategori'], comparison_df['Rata_rata'], color=colors)

    ax.set_title(f'Perbandingan {selected_nutrient}', fontsize=11)
    ax.set_ylabel(f'Rata-rata {selected_nutrient}', fontsize=9)
    ax.tick_params(labelsize=8)

    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.1,
               f'{height:.1f}', ha='center', va='bottom', fontsize=8)

    st.pyplot(fig)

    # Insight perbandingan
    st.markdown("### 📊 Insight Perbandingan")

    unit = units[nutrient_names.index(selected_nutrient)]
    sorted_df = comparison_df.sort_values('Rata_rata', ascending=False)
    highest = sorted_df.iloc[0]
    lowest = sorted_df.iloc[-1]
    difference = abs(highest['Rata_rata'] - lowest['Rata_rata'])

    col1, col2 = st.columns(2)
    with col1:
        st.info(f"""
        **🏆 Tertinggi:**
        **{highest['Kategori']}**
        {highest['Rata_rata']:.1f} {unit}
        """)

    with col2:
        st.info(f"""
        **📉 Terendah:**
        **{lowest['Kategori']}**
        {lowest['Rata_rata']:.1f} {unit}
        """)

    st.info(f"""
    **📏 Perbedaan:**
    {difference:.1f} {unit}
    *({highest['Kategori']} memiliki {selected_nutrient} {difference:.1f} {unit} lebih tinggi dari {lowest['Kategori']})*
    """)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray; font-size: 0.9em;'>
    Dashboard Analisis Nutrisi Makanan • Data: nilai_gizi.csv
    </div>
    """,
    unsafe_allow_html=True
)