# -*- coding: utf-8 -*-
"""of Datvis_UAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXu9nXOizYjVhrgqMyhuMrryMdTcTxnd
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import mutual_info_classif
from wordcloud import WordCloud

# =====================================================
# KONFIGURASI HALAMAN
# =====================================================
st.set_page_config(
    page_title="Dashboard Analisis Nutrisi",
    layout="wide"
)

st.title("🥗 Dashboard Analisis Nutrisi & Teks Makanan")
st.write("Visualisasi & preprocessing data nutrisi menggunakan Streamlit Cloud")

# =====================================================
# LOAD DATA
# =====================================================
@st.cache_data
def load_data():
    df = pd.read_csv("dataset_nutrisi_text_300.csv")
    df.columns = df.columns.str.strip()
    return df

df = load_data()

st.subheader("📄 Dataset Awal")
st.dataframe(df.head(10))

# =====================================================
# PREPROCESSING NUMERIK
# =====================================================
st.header("🧹 Preprocessing Data Numerik")

numeric_cols = ['Energy_kcal', 'Protein_g', 'Fat_g', 'Sugar_g', 'Sodium_mg']

for col in numeric_cols:
    df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

df_numeric = df[numeric_cols].copy()

for col in numeric_cols:
    df_numeric[col] = df_numeric[col].fillna(df_numeric[col].median())

scaler = StandardScaler()
df_scaled = pd.DataFrame(
    scaler.fit_transform(df_numeric),
    columns=[f"{col}_scaled" for col in numeric_cols]
)

st.write("Data Numerik Setelah Scaling:")
st.dataframe(df_scaled.head())

# =====================================================
# VISUALISASI NUMERIK
# =====================================================
st.header("📊 Visualisasi Data Gizi")

col1, col2 = st.columns(2)

with col1:
    avg_protein = df.groupby("Label_Kesehatan")["Protein_g"].mean()
    fig, ax = plt.subplots()
    avg_protein.plot(kind="bar", ax=ax)
    ax.set_title("Rata-rata Protein")
    st.pyplot(fig)

with col2:
    avg_sugar_sodium = df.groupby("Label_Kesehatan")[["Sugar_g", "Sodium_mg"]].mean()
    fig, ax = plt.subplots()
    avg_sugar_sodium.plot(kind="bar", ax=ax)
    ax.set_title("Gula & Natrium")
    st.pyplot(fig)

# =====================================================
# SCATTER & HISTOGRAM
# =====================================================
st.header("🔍 Analisis Distribusi")

fig, ax = plt.subplots()
sns.scatterplot(
    data=df,
    x="Protein_g",
    y="Fat_g",
    hue="Label_Kesehatan",
    ax=ax
)
ax.set_title("Protein vs Lemak")
st.pyplot(fig)

fig, ax = plt.subplots()
ax.hist(df["Energy_kcal"], bins=20)
ax.set_title("Distribusi Energi (Kalori)")
st.pyplot(fig)

# =====================================================
# PREPROCESSING TEKS
# =====================================================
st.header("📝 Analisis Teks (TF-IDF)")

df_text = df[["Food_Text", "Label_Kesehatan"]].copy()
df_text["clean_text"] = df_text["Food_Text"].astype(str).str.lower()

tfidf = TfidfVectorizer(max_features=20, stop_words="english")
X = tfidf.fit_transform(df_text["clean_text"])

y = df_text["Label_Kesehatan"].map({"Sehat": 0, "Tidak Sehat": 1})

ig = mutual_info_classif(X, y)
features = tfidf.get_feature_names_out()

ig_df = pd.DataFrame({
    "Fitur": features,
    "Information Gain": ig
}).sort_values(by="Information Gain", ascending=False)

st.subheader("🔑 Fitur Teks Paling Berpengaruh")
st.dataframe(ig_df)

# =====================================================
# WORDCLOUD
# =====================================================
st.header("☁️ Word Cloud")

col1, col2 = st.columns(2)

with col1:
    text_sehat = " ".join(
        df[df["Label_Kesehatan"] == "Sehat"]["Food_Text"].astype(str)
    )
    wc = WordCloud(background_color="white").generate(text_sehat)
    fig, ax = plt.subplots()
    ax.imshow(wc)
    ax.axis("off")
    ax.set_title("Makanan Sehat")
    st.pyplot(fig)

with col2:
    text_tidak = " ".join(
        df[df["Label_Kesehatan"] == "Tidak Sehat"]["Food_Text"].astype(str)
    )
    wc = WordCloud(background_color="white").generate(text_tidak)
    fig, ax = plt.subplots()
    ax.imshow(wc)
    ax.axis("off")
    ax.set_title("Makanan Tidak Sehat")
    st.pyplot(fig)